"""Remaining repository Protocols — cross-cutting concerns not yet in sub-packages.

These will be migrated to domain/agent/ and domain/crm/ when those
sub-packages are created.
"""

from __future__ import annotations

from typing import Protocol as TypingProtocol


class ToolEventRepository(TypingProtocol):
    """Persistence interface for agent tool event tracking."""

    async def log_tool_event(
        self,
        partner_id: str,
        tool_name: str,
        entity_id: str | None,
        query: str | None,
        result_count: int | None,
    ) -> None: ...

    async def get_entity_usage_stats(
        self,
        partner_id: str,
        days: int = 30,
    ) -> list[dict]: ...


class UsageLogRepository(TypingProtocol):
    """Persistence interface for LLM usage logging."""

    async def write_usage_log(
        self,
        partner_id: str,
        feature: str,
        tokens_in: int,
        tokens_out: int,
        model: str,
    ) -> None: ...


class CrmRepository(TypingProtocol):
    """Persistence interface for CRM operations."""

    async def create_company(self, company: object) -> object: ...
    async def update_company(self, company: object) -> object: ...
    async def get_company(self, partner_id: str, company_id: str) -> object | None: ...
    async def list_companies(self, partner_id: str) -> list: ...
    async def create_contact(self, contact: object) -> object: ...
    async def update_contact(self, contact: object) -> object: ...
    async def get_contact(self, partner_id: str, contact_id: str) -> object | None: ...
    async def list_contacts(self, partner_id: str, company_id: str | None = None) -> list: ...
    async def create_deal(self, deal: object) -> object: ...
    async def update_deal(self, deal: object) -> object: ...
    async def get_deal(self, partner_id: str, deal_id: str) -> object | None: ...
    async def list_deals(self, partner_id: str, include_inactive: bool = False) -> list: ...
    async def create_activity(self, activity: object) -> object: ...
    async def list_activities(self, partner_id: str, deal_id: str) -> list: ...
    async def get_setting(self, partner_id: str, key: str) -> dict | None: ...
    async def upsert_setting(self, partner_id: str, key: str, value: dict) -> None: ...
    async def create_ai_insight(self, insight: object) -> object: ...
    async def list_ai_insights_by_deal(self, partner_id: str, deal_id: str, insight_type: str | None = None) -> list: ...
    async def update_ai_insight_status(self, partner_id: str, insight_id: str, status: str) -> object | None: ...
