"""AC test stubs generated from ADR-047 / PLAN-l1-level-ssot-refactor.

Auto-generated by Architect — Developer / QA fills implementation as each
subtask lands. Red = gap, Green = verified.

AC IDs cover: domain judgement, CRM-company-as-L1, legacy-alias rejection,
governance prompt hygiene, UI surface, data completeness, strict level check.
"""
from __future__ import annotations

from types import SimpleNamespace

import pytest

from zenos.domain.knowledge.collaboration_roots import is_collaboration_root_entity


# --- P0: Domain judgement ---

@pytest.mark.spec("AC-L1SSOT-01")
def test_ac_l1ssot_01_any_type_with_level_1_is_l1():
    """AC-L1SSOT-01: Given an entity with level=1 AND parent_id=None,
    When is_collaboration_root_entity is called,
    Then it returns True regardless of entity.type (product / company / person / deal)."""
    for entity_type in ("product", "company", "person", "deal"):
        entity = SimpleNamespace(type=entity_type, level=1, parent_id=None)
        assert is_collaboration_root_entity(entity) is True, (
            f"Expected L1=True for type={entity_type!r}, level=1, parent_id=None"
        )


@pytest.mark.spec("AC-L1SSOT-07")
def test_ac_l1ssot_07_strict_level_check():
    """AC-L1SSOT-07: Given an entity with level=None (legacy fallback territory),
    When is_collaboration_root_entity is called,
    Then it returns False — the level-null fallback MUST be removed after backfill."""
    # level=None must be rejected (strict mode, ADR-047 D1)
    entity_level_none = SimpleNamespace(type="product", level=None, parent_id=None)
    assert is_collaboration_root_entity(entity_level_none) is False, (
        "level=None should return False — level-null fallback has been removed"
    )
    # Confirm level=1 still works as sanity check
    entity_level_1 = SimpleNamespace(type="product", level=1, parent_id=None)
    assert is_collaboration_root_entity(entity_level_1) is True


# --- P0: CRM integration ---

@pytest.mark.spec("AC-L1SSOT-02")
def test_ac_l1ssot_02_crm_company_accepted_as_product_id():
    """AC-L1SSOT-02: Given a CRM-created entity with type=company and level=1,
    When plan(action="create", product_id=<company_id>) is called,
    Then the plan is created successfully (no INVALID_PRODUCT_ID rejection)."""
    pytest.skip("Pending S03 — Application layer refactor not yet landed")


# --- P0: Legacy alias rejection ---

@pytest.mark.spec("AC-L1SSOT-03")
def test_ac_l1ssot_03_project_id_param_rejected():
    """AC-L1SSOT-03: Given a caller passes project_id parameter to MCP plan/task,
    When the tool is invoked,
    Then server responds with INVALID_INPUT (no silent accept, no alias mapping)."""
    pytest.skip("Pending S04 — MCP interface layer removal of project_id alias")


# --- P0: Governance prompt hygiene ---

@pytest.mark.spec("AC-L1SSOT-04")
def test_ac_l1ssot_04_governance_prompt_clean():
    """AC-L1SSOT-04: Given governance_guide("task") and governance_guide("plan"),
    When the rendered prompt text is inspected,
    Then it contains neither 'type=product' nor 'project_id' substrings."""
    pytest.skip("Pending S04 — governance_rules.py prompt rewrite")


# --- P0: Dashboard surface ---

@pytest.mark.spec("AC-L1SSOT-05")
def test_ac_l1ssot_05_dashboard_projects_shows_all_l1():
    """AC-L1SSOT-05: Given a workspace containing L1 entities of multiple types
    (product, company, person, deal),
    When /projects page renders,
    Then all of them are displayed — UI filter is level-based, not type-based.

    (Verified via vitest on dashboard side; this Python stub asserts the API
    contract that /api/data/entities?level=1 returns all L1 regardless of type.)"""
    pytest.skip("Pending S06 — Dashboard UI isL1Entity helper")


# --- P0: Data completeness ---

@pytest.mark.spec("AC-L1SSOT-06")
def test_ac_l1ssot_06_production_level_no_null():
    """AC-L1SSOT-06: Given production DB post-backfill,
    When SELECT COUNT(*) FROM zenos.entities WHERE level IS NULL is executed,
    Then the count equals 0 — every entity has an explicit level assigned.

    (This AC is verified via backfill_entity_level.py apply-mode report +
    QA independent SQL spot-check during GATE A.)"""
    pytest.skip("Verified out-of-band in GATE A (production SQL check); no in-repo assertion")
