"""
AC test stubs generated from SPEC-mcp-id-ergonomics.
Auto-generated by Architect — Developer fills implementation.

Covers:
- AC-MIDE-01: write entries not-found length diagnostic
- AC-MIDE-02: get/analyze/source/attachment not-found consistent
- AC-MIDE-03: get/search id_prefix param (unique / zero / ambiguous)
- AC-MIDE-04: id_prefix respects partner isolation
- AC-MIDE-05: write/confirm/handoff reject id_prefix
- AC-MIDE-06: dogfood reject-rate scanner output
- AC-MIDE-07: dogfood workflow mentions reject-rate gate
- AC-MIDE-08: agent skills mention full-ID discipline
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Any
from unittest.mock import AsyncMock, MagicMock, patch

import pytest


ROOT = Path(__file__).resolve().parents[2]


# ---------------------------------------------------------------------------
# Domain model stubs for tests (minimal fields needed by serializer)
# ---------------------------------------------------------------------------

def _make_entity(entity_id: str, name: str = "Test Entity", entity_type: str = "module") -> object:
    """Create a minimal Entity-like object for use in mocks."""
    from zenos.domain.knowledge.models import Entity, Tags
    return Entity(
        id=entity_id,
        name=name,
        type=entity_type,
        summary="test summary",
        tags=Tags(what=[], why="", how="", who=[]),
        level=2,
        status="active",
        visibility="public",
        created_at=datetime(2026, 1, 1),
        updated_at=datetime(2026, 1, 1),
    )


def _make_task(task_id: str, title: str = "Test Task") -> object:
    """Create a minimal Task-like object for use in mocks."""
    from zenos.domain.action.models import Task
    return Task(
        id=task_id,
        title=title,
        description="test",
        status="todo",
        priority="medium",
        priority_reason="",
        assignee=None,
        assignee_role_id=None,
        plan_id=None,
        plan_order=None,
        depends_on_task_ids=[],
        created_by="partner-a",
        updated_by=None,
        linked_entities=[],
        linked_protocol=None,
        linked_blindspot=None,
        source_type="",
        source_metadata={},
        context_summary="",
        due_date=None,
        blocked_by=[],
        blocked_reason=None,
        acceptance_criteria=[],
        completed_by=None,
        creator_name=None,
        assignee_name=None,
        confirmed_by_creator=False,
        rejection_reason=None,
        result=None,
        project="zenos",
        project_id=None,
        attachments=[],
        parent_task_id=None,
        dispatcher=None,
        handoff_events=[],
        created_at=datetime(2026, 1, 1),
        updated_at=datetime(2026, 1, 1),
        completed_at=None,
    )


# ---------------------------------------------------------------------------
# Shared helpers
# ---------------------------------------------------------------------------

def _assert_not_found_hint(result: dict, short_id: str) -> None:
    """Assert that a rejected result contains length-diagnostic hints.

    AC-MIDE-01/02 requires:
    (a) actual passed-in length present in rejection message
    (b) expected length 32 present
    (c) search/get suggestion present
    """
    assert result["status"] == "rejected", f"Expected 'rejected', got {result['status']!r}"
    reason = result.get("rejection_reason") or result.get("data", {}).get("message", "")
    assert reason, "rejection_reason must not be empty"

    actual_len = len(short_id)
    assert str(actual_len) in reason, (
        f"rejection_reason must contain actual id length ({actual_len}); got: {reason!r}"
    )
    assert "32" in reason, (
        f"rejection_reason must contain expected length 32; got: {reason!r}"
    )
    assert "search" in reason.lower() or "get" in reason.lower(), (
        f"rejection_reason must suggest search/get; got: {reason!r}"
    )


def _mock_mcp_bootstrap():
    """Return a context manager stack that prevents SQL service bootstrap."""
    return patch("zenos.interface.mcp._ensure_services", new=AsyncMock(return_value=None))


# --- P0: AC-MIDE-01 ---


@pytest.mark.spec("AC-MIDE-01")
@pytest.mark.asyncio
async def test_ac_mide_01_write_entry_not_found_hint():
    """AC-MIDE-01: write(entries, id=<8-char>) rejection_reason must contain length diagnostic + search hint."""
    from zenos.interface.mcp import write
    import zenos.interface.mcp as _mcp

    short_id = "39f160f5"  # 8-char — typical git-style short ID that agents copy

    with _mock_mcp_bootstrap():
        _mcp.entry_repo = MagicMock()
        _mcp.entry_repo.update_status = AsyncMock(return_value=None)

        result = await write(
            collection="entries",
            id=short_id,
            data={"status": "archived", "archive_reason": "manual"},
        )

    _assert_not_found_hint(result, short_id)


# --- P0: AC-MIDE-02 ---


@pytest.mark.spec("AC-MIDE-02")
@pytest.mark.asyncio
async def test_ac_mide_02_get_not_found_hint():
    """AC-MIDE-02: get(entities|documents|blindspots|tasks, id=<invalid>) message must contain length mismatch / non-hex hint."""
    from zenos.interface.mcp import get
    import zenos.interface.mcp as _mcp

    short_id = "abc123"  # 6-char — clearly not 32

    with _mock_mcp_bootstrap():
        # --- entities ---
        _mcp.entity_repo = MagicMock()
        _mcp.entity_repo.get_by_id = AsyncMock(return_value=None)

        result = await get(collection="entities", id=short_id)
        _assert_not_found_hint(result, short_id)

        # --- documents ---
        _mcp.ontology_service = MagicMock()
        _mcp.ontology_service.get_document = AsyncMock(return_value=None)

        result = await get(collection="documents", id=short_id)
        _assert_not_found_hint(result, short_id)

        # --- blindspots ---
        _mcp.blindspot_repo = MagicMock()
        _mcp.blindspot_repo.get_by_id = AsyncMock(return_value=None)

        result = await get(collection="blindspots", id=short_id)
        _assert_not_found_hint(result, short_id)

        # --- tasks ---
        _mcp.task_service = MagicMock()
        _mcp.task_service.get_task_enriched = AsyncMock(return_value=None)

        result = await get(collection="tasks", id=short_id)
        _assert_not_found_hint(result, short_id)


@pytest.mark.spec("AC-MIDE-02")
@pytest.mark.asyncio
async def test_ac_mide_02_analyze_not_found_hint():
    """AC-MIDE-02: analyze(check_type=entity_health, entity_id=<invalid>) message must contain diagnostic."""
    from zenos.interface.mcp import analyze
    import zenos.interface.mcp as _mcp

    short_id = "bad_id_12"  # 9-char

    with _mock_mcp_bootstrap():
        _mcp.entity_repo = MagicMock()
        _mcp.entity_repo.get_by_id = AsyncMock(return_value=None)

        result = await analyze(check_type="entity_health", entity_id=short_id)

    _assert_not_found_hint(result, short_id)


@pytest.mark.spec("AC-MIDE-02")
@pytest.mark.asyncio
async def test_ac_mide_02_source_not_found_hint():
    """AC-MIDE-02: source(action=read, doc_id=<invalid>) message must contain diagnostic."""
    from zenos.interface.mcp import read_source
    import zenos.interface.mcp as _mcp

    short_id = "docshort"  # 8-char

    with _mock_mcp_bootstrap():
        _mcp.ontology_service = MagicMock()
        _mcp.ontology_service.get_document = AsyncMock(return_value=None)

        result = await read_source(doc_id=short_id)

    _assert_not_found_hint(result, short_id)


@pytest.mark.spec("AC-MIDE-02")
@pytest.mark.asyncio
async def test_ac_mide_02_attachment_not_found_hint():
    """AC-MIDE-02: attachment(task_id=<invalid>) message must contain diagnostic."""
    from zenos.interface.mcp import upload_attachment
    from zenos.interface.mcp._auth import _current_partner
    import zenos.interface.mcp as _mcp

    short_id = "tsk12345"  # 8-char

    token = _current_partner.set({"id": "partner-1", "isAdmin": False})
    try:
        with _mock_mcp_bootstrap():
            _mcp.task_service = MagicMock()
            _mcp.task_service._tasks = MagicMock()
            _mcp.task_service._tasks.get_by_id = AsyncMock(return_value=None)

            result = await upload_attachment(
                task_id=short_id,
                filename="report.pdf",
                content_type="application/pdf",
            )
    finally:
        _current_partner.reset(token)

    _assert_not_found_hint(result, short_id)


# --- P0: AC-MIDE-03 ---


@pytest.mark.spec("AC-MIDE-03")
@pytest.mark.asyncio
async def test_ac_mide_03_get_id_prefix_unique():
    """AC-MIDE-03: get(id_prefix=<唯一 prefix>) 回 status=ok + 完整 payload。"""
    from zenos.interface.mcp import get
    from zenos.interface.mcp._auth import _current_partner
    import zenos.interface.mcp as _mcp

    full_id = "abcdef1234567890abcdef1234567890"  # 32-char hex
    prefix = "abcdef12"  # 8-char prefix
    entity = _make_entity(full_id, "Unique Entity")

    token = _current_partner.set({"id": "partner-a", "isAdmin": True})
    try:
        with _mock_mcp_bootstrap():
            _mcp.entity_repo = MagicMock()
            # find_by_id_prefix returns exactly 1 entity
            _mcp.entity_repo.find_by_id_prefix = AsyncMock(return_value=[entity])
            # get_by_id is called on the resolved full id (exact match path)
            _mcp.entity_repo.get_by_id = AsyncMock(return_value=entity)
            # relationship_repo needed for exact-match path
            _mcp.relationship_repo = MagicMock()
            _mcp.relationship_repo.list_by_entity = AsyncMock(return_value=[])
            # ontology_service for impact_chain (include=None → eager dump path)
            _mcp.ontology_service = MagicMock()
            _mcp.ontology_service.compute_impact_chain = AsyncMock(return_value=[])
            _mcp.entry_repo = MagicMock()
            _mcp.entry_repo.list_by_entity = AsyncMock(return_value=[])

            result = await get(collection="entities", id_prefix=prefix)
    finally:
        _current_partner.reset(token)

    assert result["status"] == "ok", f"Expected ok, got {result['status']!r}: {result.get('rejection_reason')}"
    data = result["data"]
    # The full 32-char id should appear in data (either directly or nested under 'entity')
    data_id = data.get("id") or (data.get("entity") or {}).get("id")
    assert data_id == full_id, f"Expected full_id {full_id!r} in response data, got {data_id!r}"


@pytest.mark.spec("AC-MIDE-03")
@pytest.mark.asyncio
async def test_ac_mide_03_get_id_prefix_ambiguous():
    """AC-MIDE-03: get(id_prefix=<匹配 2+ 筆>) 回 rejected + AMBIGUOUS_PREFIX + candidates。"""
    from zenos.interface.mcp import get
    from zenos.interface.mcp._auth import _current_partner
    import zenos.interface.mcp as _mcp

    prefix = "abcd1234"
    entity_a = _make_entity("abcd12340000000000000000aaaaaaaa", "Entity A")
    entity_b = _make_entity("abcd12340000000000000000bbbbbbbb", "Entity B")

    token = _current_partner.set({"id": "partner-a", "isAdmin": True})
    try:
        with _mock_mcp_bootstrap():
            _mcp.entity_repo = MagicMock()
            _mcp.entity_repo.find_by_id_prefix = AsyncMock(return_value=[entity_a, entity_b])

            result = await get(collection="entities", id_prefix=prefix)
    finally:
        _current_partner.reset(token)

    assert result["status"] == "rejected", f"Expected rejected for ambiguous prefix, got {result['status']!r}"
    assert result.get("rejection_reason") == "AMBIGUOUS_PREFIX", (
        f"Expected AMBIGUOUS_PREFIX, got {result.get('rejection_reason')!r}"
    )
    candidates = result.get("data", {}).get("candidates", [])
    assert len(candidates) == 2, f"Expected 2 candidates, got {len(candidates)}"
    candidate_ids = {c["id"] for c in candidates}
    assert entity_a.id in candidate_ids
    assert entity_b.id in candidate_ids


@pytest.mark.spec("AC-MIDE-03")
@pytest.mark.asyncio
async def test_ac_mide_03_search_id_prefix_zero():
    """AC-MIDE-03: search(id_prefix=<匹配 0 筆>) 回 rejected + matches 0 entries。"""
    from zenos.interface.mcp import search
    from zenos.interface.mcp._auth import _current_partner
    import zenos.interface.mcp as _mcp

    prefix = "dead0000"

    token = _current_partner.set({"id": "partner-a", "isAdmin": True})
    try:
        with _mock_mcp_bootstrap():
            _mcp.entry_repo = MagicMock()
            _mcp.entry_repo.find_by_id_prefix = AsyncMock(return_value=[])

            result = await search(collection="entries", id_prefix=prefix)
    finally:
        _current_partner.reset(token)

    assert result["status"] == "rejected", f"Expected rejected for 0 matches, got {result['status']!r}"
    reason = result.get("rejection_reason", "")
    assert "0" in reason or "matches 0" in reason, (
        f"Expected '0' in rejection_reason, got {reason!r}"
    )
    assert prefix in reason, f"Expected prefix {prefix!r} in rejection_reason, got {reason!r}"


# --- P0: AC-MIDE-04 ---


@pytest.mark.spec("AC-MIDE-04")
@pytest.mark.asyncio
async def test_ac_mide_04_id_prefix_workspace_isolation():
    """AC-MIDE-04: partner A 的 id_prefix 不回傳 partner B 的記錄或 metadata。"""
    from zenos.interface.mcp import get
    from zenos.interface.mcp._auth import _current_partner
    import zenos.interface.mcp as _mcp

    prefix = "cafe1234"
    # Partner A has an entity with this prefix; Partner B also has one
    entity_a = _make_entity("cafe12340000000000000000aaaaaaaa", "Partner A Entity")
    entity_b = _make_entity("cafe12340000000000000000bbbbbbbb", "Partner B Entity")

    # Track which partner_id is passed to find_by_id_prefix
    calls: list[str] = []

    async def mock_find_by_prefix(prefix_arg: str, partner_id_arg: str, limit: int = 11) -> list:
        calls.append(partner_id_arg)
        # Only return entities for partner-a
        if partner_id_arg == "partner-a":
            return [entity_a]
        return [entity_b]

    # Test as partner-a: should only see entity_a
    token = _current_partner.set({"id": "partner-a", "isAdmin": True})
    try:
        with _mock_mcp_bootstrap():
            _mcp.entity_repo = MagicMock()
            _mcp.entity_repo.find_by_id_prefix = mock_find_by_prefix
            _mcp.entity_repo.get_by_id = AsyncMock(return_value=entity_a)
            _mcp.relationship_repo = MagicMock()
            _mcp.relationship_repo.list_by_entity = AsyncMock(return_value=[])
            _mcp.ontology_service = MagicMock()
            _mcp.ontology_service.compute_impact_chain = AsyncMock(return_value=[])
            _mcp.entry_repo = MagicMock()
            _mcp.entry_repo.list_by_entity = AsyncMock(return_value=[])

            result_a = await get(collection="entities", id_prefix=prefix)
    finally:
        _current_partner.reset(token)

    # Verify partner-a sees entity_a and not entity_b
    assert result_a["status"] == "ok", f"Expected ok for partner-a, got {result_a['status']!r}"
    data_a = result_a["data"]
    data_id_a = data_a.get("id") or (data_a.get("entity") or {}).get("id")
    assert data_id_a == entity_a.id, f"partner-a should see entity_a, got {data_id_a!r}"
    assert data_id_a != entity_b.id, "partner-a must NOT see entity_b"

    # Verify the correct partner_id was passed to find_by_id_prefix
    assert calls and calls[-1] == "partner-a", (
        f"find_by_id_prefix must be called with partner_id='partner-a', got {calls!r}"
    )


# --- P0: AC-MIDE-05 ---


@pytest.mark.spec("AC-MIDE-05")
@pytest.mark.asyncio
async def test_ac_mide_05_write_rejects_id_prefix():
    """AC-MIDE-05: write(collection, id_prefix=...) 被 reject，reason=id_prefix_not_allowed_for_write_ops。"""
    from zenos.interface.mcp import write

    with _mock_mcp_bootstrap():
        result = await write(
            collection="entries",
            id_prefix="abcd1234",
            data={"status": "archived", "archive_reason": "manual"},
        )

    assert result["status"] == "rejected", f"Expected rejected, got {result['status']!r}"
    assert result.get("rejection_reason") == "id_prefix_not_allowed_for_write_ops", (
        f"Expected id_prefix_not_allowed_for_write_ops, got {result.get('rejection_reason')!r}"
    )


@pytest.mark.spec("AC-MIDE-05")
@pytest.mark.asyncio
async def test_ac_mide_05_handoff_rejects_id_prefix():
    """AC-MIDE-05: task(action=handoff, id_prefix=...) 被 reject。"""
    from zenos.interface.mcp import task

    with _mock_mcp_bootstrap():
        result = await task(
            action="handoff",
            id_prefix="abcd1234",
            to_dispatcher="agent:qa",
            reason="passing to qa",
        )

    assert result["status"] == "rejected", f"Expected rejected, got {result['status']!r}"
    assert result.get("rejection_reason") == "id_prefix_not_allowed_for_write_ops", (
        f"Expected id_prefix_not_allowed_for_write_ops, got {result.get('rejection_reason')!r}"
    )


@pytest.mark.spec("AC-MIDE-05")
@pytest.mark.asyncio
async def test_ac_mide_05_confirm_rejects_id_prefix():
    """AC-MIDE-05: confirm(id_prefix=...) 被 reject。"""
    from zenos.interface.mcp import confirm

    with _mock_mcp_bootstrap():
        result = await confirm(
            collection="tasks",
            id_prefix="abcd1234",
        )

    assert result["status"] == "rejected", f"Expected rejected, got {result['status']!r}"
    assert result.get("rejection_reason") == "id_prefix_not_allowed_for_write_ops", (
        f"Expected id_prefix_not_allowed_for_write_ops, got {result.get('rejection_reason')!r}"
    )


# ---------------------------------------------------------------------------
# QA-added boundary tests for AC-MIDE-03 edge cases
# ---------------------------------------------------------------------------


@pytest.mark.spec("AC-MIDE-03")
@pytest.mark.asyncio
async def test_qa_boundary_prefix_too_short_3_chars():
    """QA: prefix 長度 3 chars should be rejected with 4+ char requirement."""
    from zenos.interface.mcp import get
    from zenos.interface.mcp._auth import _current_partner

    token = _current_partner.set({"id": "partner-a", "isAdmin": True})
    try:
        with _mock_mcp_bootstrap():
            result = await get(collection="entities", id_prefix="abc")
    finally:
        _current_partner.reset(token)

    assert result["status"] == "rejected", f"Expected rejected for 3-char prefix, got {result['status']!r}"
    msg = result.get("rejection_reason") or result.get("data", {}).get("message", "")
    # Should mention the 4+ char requirement
    assert "4" in msg or "4+" in msg, f"Expected mention of 4-char minimum, got: {msg!r}"


@pytest.mark.spec("AC-MIDE-03")
@pytest.mark.asyncio
async def test_qa_boundary_prefix_non_hex():
    """QA: non-hex prefix (e.g. 'zzzz') should be rejected."""
    from zenos.interface.mcp import get
    from zenos.interface.mcp._auth import _current_partner

    token = _current_partner.set({"id": "partner-a", "isAdmin": True})
    try:
        with _mock_mcp_bootstrap():
            result = await get(collection="entities", id_prefix="zzzz")
    finally:
        _current_partner.reset(token)

    assert result["status"] == "rejected", f"Expected rejected for non-hex prefix, got {result['status']!r}"
    msg = result.get("rejection_reason") or result.get("data", {}).get("message", "")
    assert msg, "Expected rejection_reason message"


@pytest.mark.spec("AC-MIDE-03")
@pytest.mark.asyncio
async def test_qa_boundary_id_and_id_prefix_mutual_exclusion():
    """QA: passing both id and id_prefix at the same time should be rejected."""
    from zenos.interface.mcp import get
    from zenos.interface.mcp._auth import _current_partner

    token = _current_partner.set({"id": "partner-a", "isAdmin": True})
    try:
        with _mock_mcp_bootstrap():
            result = await get(
                collection="entities",
                id="abcdef1234567890abcdef1234567890",  # pragma: allowlist secret
                id_prefix="abcdef12",
            )
    finally:
        _current_partner.reset(token)

    assert result["status"] == "rejected", (
        f"Expected rejected when both id and id_prefix are provided, got {result['status']!r}"
    )


@pytest.mark.spec("AC-MIDE-03")
@pytest.mark.asyncio
async def test_qa_boundary_prefix_uppercase_passthrough():
    """QA: uppercase prefix passes validation (lowercased internally) but finds 0 matches.

    _validate_id_prefix matches prefix.lower() against hex regex so uppercase is accepted.
    However, the prefix is NOT lowercased before the SQL LIKE query, meaning uppercase
    input will silently return 0 matches (IDs are stored lowercase). This test documents
    the current behavior — a Minor usability gap (not security issue).
    """
    from zenos.interface.mcp import get
    from zenos.interface.mcp._auth import _current_partner
    import zenos.interface.mcp as _mcp

    token = _current_partner.set({"id": "partner-a", "isAdmin": True})
    try:
        with _mock_mcp_bootstrap():
            _mcp.entity_repo = __import__("unittest.mock", fromlist=["MagicMock"]).MagicMock()
            _mcp.entity_repo.find_by_id_prefix = __import__("unittest.mock", fromlist=["AsyncMock"]).AsyncMock(return_value=[])

            result = await get(collection="entities", id_prefix="ABCD1234")
    finally:
        _current_partner.reset(token)

    # Current behavior: validation passes, repo called, 0 results → rejected with "matches 0"
    # (NOT rejected at validation stage — this is the documented gap)
    assert result["status"] == "rejected", (
        f"Expected rejected (0 matches), got {result['status']!r}"
    )


@pytest.mark.spec("AC-MIDE-03")
@pytest.mark.asyncio
async def test_ac_mide_03_uppercase_prefix_normalized():
    """AC-MIDE-03 / B1 fix: uppercase prefix is lowercased internally and can match lowercase IDs.

    After the B1 fix, ABCD1234 is normalized to abcd1234 before hitting the repo,
    so the repo is always called with the lowercased version.
    """
    from zenos.interface.mcp import get
    from zenos.interface.mcp._auth import _current_partner
    import zenos.interface.mcp as _mcp
    from unittest.mock import MagicMock, AsyncMock

    full_id = "abcd12340000000000000000aaaaaaaa"
    entity = _make_entity(full_id, "Uppercase Test Entity")

    # Track what prefix the repo was actually called with
    called_with: list[str] = []

    async def mock_find_by_prefix(prefix_arg: str, partner_id_arg: str, limit: int = 11) -> list:
        called_with.append(prefix_arg)
        # Simulate: prefix lowercased → matches stored lowercase ID
        if prefix_arg == "abcd1234":
            return [entity]
        return []

    token = _current_partner.set({"id": "partner-a", "isAdmin": True})
    try:
        with _mock_mcp_bootstrap():
            _mcp.entity_repo = MagicMock()
            _mcp.entity_repo.find_by_id_prefix = mock_find_by_prefix
            _mcp.entity_repo.get_by_id = AsyncMock(return_value=entity)
            _mcp.relationship_repo = MagicMock()
            _mcp.relationship_repo.list_by_entity = AsyncMock(return_value=[])
            _mcp.ontology_service = MagicMock()
            _mcp.ontology_service.compute_impact_chain = AsyncMock(return_value=[])
            _mcp.entry_repo = MagicMock()
            _mcp.entry_repo.list_by_entity = AsyncMock(return_value=[])

            result = await get(collection="entities", id_prefix="ABCD1234")
    finally:
        _current_partner.reset(token)

    # The repo must have been called with the lowercased prefix
    assert called_with and called_with[0] == "abcd1234", (
        f"Expected repo called with lowercased 'abcd1234', got {called_with!r}"
    )
    # With the fix, uppercase prefix matches → result is ok
    assert result["status"] == "ok", (
        f"Expected ok (uppercase normalized to match lowercase ID), got {result['status']!r}: "
        f"{result.get('rejection_reason')}"
    )


@pytest.mark.spec("AC-MIDE-03")
@pytest.mark.asyncio
async def test_qa_boundary_search_prefix_ambiguous_11_plus():
    """QA: search(id_prefix=...) with 11+ matches → rejected AMBIGUOUS_PREFIX + hint."""
    from zenos.interface.mcp import search
    from zenos.interface.mcp._auth import _current_partner
    import zenos.interface.mcp as _mcp
    from datetime import datetime

    # Build 11 distinct entries (limit=11 triggers the ">10" branch)
    entries = [
        type("FakeEntry", (), {
            "id": f"abcdef12{str(i).zfill(24)}",
            "content": f"entry {i}",
            "type": "decision",
        })()
        for i in range(11)
    ]

    prefix = "abcdef12"
    token = _current_partner.set({"id": "partner-a", "isAdmin": True})
    try:
        with _mock_mcp_bootstrap():
            _mcp.entry_repo = __import__("unittest.mock", fromlist=["MagicMock"]).MagicMock()
            _mcp.entry_repo.find_by_id_prefix = __import__("unittest.mock", fromlist=["AsyncMock"]).AsyncMock(return_value=entries)

            result = await search(collection="entries", id_prefix=prefix)
    finally:
        _current_partner.reset(token)

    assert result["status"] == "rejected", (
        f"Expected rejected for 11+ matches, got {result['status']!r}"
    )
    assert result.get("rejection_reason") == "AMBIGUOUS_PREFIX", (
        f"Expected AMBIGUOUS_PREFIX for 11+ matches, got {result.get('rejection_reason')!r}"
    )


# --- P0: AC-MIDE-06 ---


@pytest.mark.spec("AC-MIDE-06")
def test_ac_mide_06_scan_reject_rate_output():
    """AC-MIDE-06: scripts/dogfood/scan_mcp_reject_rate.py 輸出必填欄位。

    Uses tests/fixtures/transcripts/fake-project/session-a.jsonl:
    - 2 mcp__zenos__ calls (toolu_A rejected, toolu_B ok)
    - reject_rate == 0.5
    """
    import subprocess
    import sys

    ROOT = Path(__file__).resolve().parents[2]
    fixture = ROOT / "tests" / "fixtures" / "transcripts" / "fake-project"
    script = ROOT / "scripts" / "dogfood" / "scan_mcp_reject_rate.py"

    result = subprocess.run(
        [sys.executable, str(script), "--transcripts-dir", str(fixture), "--format", "json"],
        capture_output=True,
        text=True,
        check=True,
    )
    data = json.loads(result.stdout)

    assert data["sessions_scanned"] == 1
    assert data["total_mcp_calls"] == 2
    assert data["rejected_count"] == 1
    assert data["reject_rate"] == 0.5
    assert len(data["top_rejection_reasons"]) >= 1
    assert data["top_rejection_reasons"][0]["count"] == 1
    assert len(data["sessions"]) == 1


# --- P0: AC-MIDE-07 ---


@pytest.mark.spec("AC-MIDE-07")
def test_ac_mide_07_dogfood_workflow_mentions_gate():
    """AC-MIDE-07: skills/workflows/dogfood.md 須含 scan_mcp_reject_rate + threshold gate 說明。"""
    workflow = ROOT / "skills" / "workflows" / "dogfood.md"
    if not workflow.exists():
        pytest.fail(f"{workflow} not found")
    content = workflow.read_text(encoding="utf-8")
    # Developer 須確保實際段落存在
    assert "scan_mcp_reject_rate" in content, "dogfood workflow 未引用 scanner"
    assert "reject rate" in content.lower() or "reject-rate" in content.lower(), "dogfood workflow 未說明 gate threshold"


@pytest.mark.spec("AC-MIDE-07B")
def test_ac_mide_07b_dogfood_workflow_forbids_data_remediation_by_default():
    """Dogfood workflow must distinguish process evaluation from ontology data remediation."""
    workflow = ROOT / "skills" / "workflows" / "dogfood.md"
    if not workflow.exists():
        pytest.fail(f"{workflow} not found")
    content = workflow.read_text(encoding="utf-8")
    assert "流程評估模式" in content, "dogfood workflow 未明確標示流程評估模式"
    assert "不可以：直接 `write/confirm` 去修 ontology 資料" in content, "dogfood workflow 未禁止預設修資料"


@pytest.mark.spec("AC-MIDE-07D")
def test_ac_mide_07d_dogfood_workflow_requires_graph_first_l3_gate():
    """Dogfood workflow must validate L3 retrieval through L2 -> entity_name, not keyword coverage search."""
    workflow = ROOT / "skills" / "workflows" / "dogfood.md"
    if not workflow.exists():
        pytest.fail(f"{workflow} not found")
    content = workflow.read_text(encoding="utf-8")
    assert "L3 Graph Retrieval Gate" in content, "dogfood workflow 未加入 L3 graph retrieval gate"
    assert 'search(\n    collection="documents",' in content and 'entity_name="{最相關 L2}"' in content, (
        "dogfood workflow 未要求從 L2 用 entity_name 拉 documents"
    )
    assert "keyword search 只能做 discovery" in content, "dogfood workflow 未禁止用 keyword search 做 coverage audit"


@pytest.mark.spec("AC-MIDE-07F")
def test_ac_mide_07f_dogfood_workflow_requires_clean_room_subagents():
    """Dogfood workflow must require fresh producer/verifier sessions and a closed-loop subagent split."""
    workflow = ROOT / "skills" / "workflows" / "dogfood.md"
    if not workflow.exists():
        pytest.fail(f"{workflow} not found")
    content = workflow.read_text(encoding="utf-8")
    assert "Clean-Room Session Gate" in content, "dogfood workflow 未加入 clean-room gate"
    assert "producer subagent 必須新開" in content, "dogfood workflow 未要求 producer fresh session"
    assert "Verifier subagent" in content, "dogfood workflow 未定義 verifier subagent"
    assert "閉環驗證 Gate" in content, "dogfood workflow 未要求 fix->rerun closed loop"


@pytest.mark.spec("AC-MIDE-07G")
def test_ac_mide_07g_dogfood_workflow_defines_efficiency_and_graph_ticketing():
    """Dogfood workflow must define efficiency beyond step count and require graph-assisted ticketing."""
    workflow = ROOT / "skills" / "workflows" / "dogfood.md"
    if not workflow.exists():
        pytest.fail(f"{workflow} not found")
    content = workflow.read_text(encoding="utf-8")
    assert "token 成本" in content, "dogfood workflow 未把 token cost 納入效率目標"
    assert "full-scan ratio" in content, "dogfood workflow 未把 full-scan ratio 納入效率目標"
    assert "Graph-Assisted Ticketing Gate" in content, "dogfood workflow 未加入 graph-assisted ticketing gate"
    assert "impacts chain" in content, "dogfood workflow 未要求開票考慮 impacts chain"


@pytest.mark.spec("AC-MIDE-07H")
def test_ac_mide_07h_dogfood_workflow_mentions_iteration_artifacts():
    """Dogfood workflow must document producer/monitor artifact outputs for each iteration."""
    workflow = ROOT / "skills" / "workflows" / "dogfood.md"
    if not workflow.exists():
        pytest.fail(f"{workflow} not found")
    content = workflow.read_text(encoding="utf-8")
    assert "build_iteration_artifacts.py" in content, "dogfood workflow 未引用 iteration artifact builder"
    assert "/tmp/zenos-dogfood/{DF-ID}/producer.jsonl" in content, "dogfood workflow 未定義 producer artifact path"
    assert "/tmp/zenos-dogfood/{DF-ID}/monitor.json" in content, "dogfood workflow 未定義 monitor artifact path"


@pytest.mark.spec("AC-MIDE-07I")
def test_ac_mide_07i_dogfood_workflow_mentions_baseline_builder():
    """Dogfood workflow must document how to build the scenario baseline library."""
    workflow = ROOT / "skills" / "workflows" / "dogfood.md"
    if not workflow.exists():
        pytest.fail(f"{workflow} not found")
    content = workflow.read_text(encoding="utf-8")
    assert "build_baseline_library.py" in content, "dogfood workflow 未引用 baseline builder"
    assert "/tmp/zenos-dogfood/baseline-library.json" in content, "dogfood workflow 未定義 baseline library path"


@pytest.mark.spec("AC-MIDE-07K")
def test_ac_mide_07k_dogfood_workflow_mentions_monitor_report_builder():
    """Dogfood workflow must document how to enrich monitor.json into a per-type health diff report."""
    workflow = ROOT / "skills" / "workflows" / "dogfood.md"
    if not workflow.exists():
        pytest.fail(f"{workflow} not found")
    content = workflow.read_text(encoding="utf-8")
    assert "build_monitor_report.py" in content, "dogfood workflow 未引用 monitor report builder"
    assert "--quality-json" in content and "--staleness-json" in content, (
        "dogfood workflow 未說明 monitor report 需要哪些 governance payloads"
    )


@pytest.mark.spec("AC-MIDE-07L")
def test_ac_mide_07l_dogfood_workflow_mentions_delta_builder():
    """Dogfood workflow must document how to compare before/after iterations into delta.json."""
    workflow = ROOT / "skills" / "workflows" / "dogfood.md"
    if not workflow.exists():
        pytest.fail(f"{workflow} not found")
    content = workflow.read_text(encoding="utf-8")
    assert "build_iteration_delta.py" in content, "dogfood workflow 未引用 delta builder"
    assert "/tmp/zenos-dogfood/{DF-ID}/delta.json" in content, "dogfood workflow 未定義 delta artifact path"


@pytest.mark.spec("AC-MIDE-07M")
def test_ac_mide_07m_dogfood_workflow_mentions_replay_call_filters():
    """Dogfood workflow must document call filters for replaying broad vs targeted document retrieval from real transcripts."""
    workflow = ROOT / "skills" / "workflows" / "dogfood.md"
    if not workflow.exists():
        pytest.fail(f"{workflow} not found")
    content = workflow.read_text(encoding="utf-8")
    assert "--call-filter documents_broad" in content, "dogfood workflow 未說明 broad replay filter"
    assert "--call-filter documents_targeted" in content, "dogfood workflow 未說明 targeted replay filter"


@pytest.mark.spec("AC-MIDE-07N")
def test_ac_mide_07n_dogfood_workflow_requires_minimal_clean_room_read_set():
    """Dogfood workflow must keep producer/verifier pre-read minimal so token measurements are not dominated by governance docs."""
    workflow = ROOT / "skills" / "workflows" / "dogfood.md"
    if not workflow.exists():
        pytest.fail(f"{workflow} not found")
    content = workflow.read_text(encoding="utf-8")
    assert "最小讀取集合" in content, "dogfood workflow 未定義 minimal clean-room read set"
    assert "bootstrap-protocol.md" in content and "document-governance.md" in content, "dogfood workflow 未明示哪些長文件預設不要預載"
    assert "token 成本不能先被 pre-read 吃掉" in content, "dogfood workflow 未說明 minimal read set 的 token 理由"


@pytest.mark.spec("AC-MIDE-07O")
def test_ac_mide_07o_dogfood_workflow_caps_clean_room_search_limits():
    """Dogfood workflow must cap clean-room search limits so producer/verifier do not overfetch candidates by default."""
    workflow = ROOT / "skills" / "workflows" / "dogfood.md"
    if not workflow.exists():
        pytest.fail(f"{workflow} not found")
    content = workflow.read_text(encoding="utf-8")
    assert "預設取樣上限" in content, "dogfood workflow 未定義 clean-room search limit cap"
    assert 'limit=5' in content, "dogfood workflow 未要求 clean-room search limit<=5"
    assert 'limit<=3' in content, "dogfood workflow 未要求 document candidate sampling limit<=3"


@pytest.mark.spec("AC-MIDE-07P")
def test_ac_mide_07p_dogfood_workflow_requires_product_scope_when_known():
    """Dogfood workflow must require product-scoped search when scenario product is known."""
    workflow = ROOT / "skills" / "workflows" / "dogfood.md"
    if not workflow.exists():
        pytest.fail(f"{workflow} not found")
    content = workflow.read_text(encoding="utf-8")
    assert "產品 scope（已知時必帶）" in content, "dogfood workflow 未定義 product-scoped retrieval rule"
    assert 'product_id="{PRODUCT_ID}"' in content, "dogfood workflow 未要求 entity/document search 帶 product_id"


@pytest.mark.spec("AC-MIDE-07Q")
def test_ac_mide_07q_dogfood_workflow_separates_routing_from_delivery_failures():
    """Dogfood workflow must classify document_summary fallback after correct L3 hit as delivery degradation, not routing failure."""
    workflow = ROOT / "skills" / "workflows" / "dogfood.md"
    if not workflow.exists():
        pytest.fail(f"{workflow} not found")
    content = workflow.read_text(encoding="utf-8")
    assert "source delivery degraded" in content, "dogfood workflow 未定義 source delivery degraded 分類"
    assert "L3 routing failure" in content, "dogfood workflow 未區分 routing failure"
    assert "GitHub token / repo 權限 / delivery snapshot" in content, "dogfood workflow 未說明 delivery/auth path 判讀"


@pytest.mark.spec("AC-MIDE-07R")
def test_ac_mide_07r_dogfood_workflow_requires_github_delivery_secret_health_gate():
    """Dogfood workflow must require a post-deploy GitHub delivery secret health check for MCP runtime changes."""
    workflow = ROOT / "skills" / "workflows" / "dogfood.md"
    if not workflow.exists():
        pytest.fail(f"{workflow} not found")
    content = workflow.read_text(encoding="utf-8")
    assert "check_github_delivery_secret.py" in content, "dogfood workflow 未要求 deploy 後檢查 github delivery secret"
    assert "--secret-name github-token" in content, "dogfood workflow 未指定 github-token secret health check"
    assert "delivery/auth blocker" in content, "dogfood workflow 未定義 invalid github token 的 blocker 分類"
    assert "--github-delivery-secret-health-json" in content, "dogfood workflow 未把 github secret health 接進 monitor artifact"
    assert "health.delivery_auth" in content, "dogfood workflow 未要求 monitor 寫入 delivery_auth health"


@pytest.mark.spec("AC-MIDE-07S")
def test_ac_mide_07s_dogfood_workflow_treats_missing_formal_entry_snapshot_as_delivery_friction():
    """Dogfood workflow must use invalid_documents analyzer signal to classify missing/stale formal-entry delivery snapshot as delivery friction."""
    workflow = ROOT / "skills" / "workflows" / "dogfood.md"
    if not workflow.exists():
        pytest.fail(f"{workflow} not found")
    content = workflow.read_text(encoding="utf-8")
    assert 'analyze(check_type="invalid_documents")' in content, "dogfood workflow 未要求 monitor 檢查 invalid_documents"
    assert "--invalid-documents-json" in content, "dogfood workflow 未把 invalid_documents 接進 monitor artifact builder"
    assert "current_formal_entry_missing_delivery_snapshot" in content, "dogfood workflow 未納入 missing delivery snapshot signal"
    assert "current_formal_entry_stale_delivery_snapshot" in content, "dogfood workflow 未納入 stale delivery snapshot signal"
    assert "delivery/auth path friction" in content, "dogfood workflow 未將 formal-entry snapshot 缺口歸類為 delivery friction"
    assert "build_snapshot_repair_queue.py" in content, "dogfood workflow 未提供 snapshot repair queue builder"
    assert "apply_snapshot_repair_queue.py" in content, "dogfood workflow 未提供 snapshot repair runner"


@pytest.mark.spec("AC-MIDE-07T")
def test_ac_mide_07t_dogfood_workflow_emits_source_repair_queue_for_source_not_found():
    """Dogfood workflow must convert SOURCE_NOT_FOUND replay results into a source repair queue artifact."""
    workflow = ROOT / "skills" / "workflows" / "dogfood.md"
    if not workflow.exists():
        pytest.fail(f"{workflow} not found")
    content = workflow.read_text(encoding="utf-8")
    assert "build_source_repair_queue.py" in content, "dogfood workflow 未提供 source repair queue builder"
    assert "source-repair-queue.json" in content, "dogfood workflow 未定義 source repair queue artifact"
    assert "SOURCE_NOT_FOUND" in content, "dogfood workflow 未處理 SOURCE_NOT_FOUND replay 結果"
    assert "source governance friction" in content, "dogfood workflow 未定義 source governance friction 分類"
    assert "--source-repair-queue-json" in content, "dogfood workflow 未把 source repair queue 接進 monitor artifact"
    assert "health.source_governance" in content, "dogfood workflow 未要求 monitor 寫入 source_governance health"
    assert "health.delivery_auth" in content, "dogfood workflow 未要求 delta 比較 delivery_auth health"
    assert "build_governance_review_task_draft.py" in content, "dogfood workflow 未提供 governance review task draft builder"
    assert "governance-review-task-drafts.json" in content, "dogfood workflow 未定義 governance review task draft artifact"


@pytest.mark.spec("AC-MIDE-07H")
def test_ac_mide_07h_task_governance_forbids_full_scan_ticket_context():
    """Task governance must require graph-first context loading and forbid full-scan document search for ticket drafting."""
    workflow = ROOT / "skills" / "governance" / "task-governance.md"
    if not workflow.exists():
        pytest.fail(f"{workflow} not found")
    content = workflow.read_text(encoding="utf-8")
    assert "建票 context 載入（graph-first" in content, "task governance 未加入 graph-first ticket context"
    assert 'search(collection="documents", query="關鍵字")' in content, "task governance 未明示禁止 full-scan document query"
    assert "linked_entities" in content and "impacts chain" in content, "task governance 未要求 graph-assisted ticket quality"


@pytest.mark.spec("AC-MIDE-07C")
def test_ac_mide_07c_release_governance_skill_distinguishes_process_vs_data():
    """Release governance skill must distinguish process governance from data remediation."""
    workflow = ROOT / "skills" / "release" / "zenos-governance" / "SKILL.md"
    if not workflow.exists():
        pytest.fail(f"{workflow} not found")
    content = workflow.read_text(encoding="utf-8")
    assert "流程治理" in content, "release governance skill 未標示流程治理模式"
    assert "不是 ontology data remediation" in content, "release governance skill 未區分流程與資料修補"


@pytest.mark.spec("AC-MIDE-07E")
def test_ac_mide_07e_capture_workflow_forbids_keyword_coverage_audit():
    """Capture workflow must route document coverage audits to graph-first retrieval instead of keyword search."""
    workflow = ROOT / "skills" / "workflows" / "knowledge-capture.md"
    if not workflow.exists():
        pytest.fail(f"{workflow} not found")
    content = workflow.read_text(encoding="utf-8")
    assert "覆蓋率清查紅線" in content, "capture workflow 未加入 coverage audit red lines"
    assert 'search(collection="documents", entity_name="<L2 name>", include=["summary"])' in content, (
        "capture workflow 未要求用 entity_name 枚舉 L3 documents"
    )
    assert 'search(query="關鍵字", collection="documents")' in content, (
        "capture workflow 未明示 keyword search 不是 coverage audit 主路徑"
    )


@pytest.mark.spec("AC-MIDE-07U")
def test_ac_mide_07u_dogfood_release_skill_prefers_summary_compact_for_l3_graph_retrieval():
    """Release dogfood skill should prefer summary_compact for low-token L3 graph retrieval."""
    workflow = ROOT / "skills" / "release" / "workflows" / "dogfood" / "SKILL.md"
    if not workflow.exists():
        pytest.fail(f"{workflow} not found")
    content = workflow.read_text(encoding="utf-8")
    assert 'include=["summary_compact"]' in content, "dogfood release skill 未要求 summary_compact"
    assert 'search(collection="documents", entity_name="{L2 名稱}", include=["summary_compact"], limit=3, product_id="{PRODUCT_ID}")' in content, (
        "dogfood release skill 未提供低 token 的 L3 graph retrieval path"
    )


@pytest.mark.spec("AC-MIDE-07V")
def test_ac_mide_07v_dogfood_release_skill_tracks_payload_bytes_when_tokens_are_noisy():
    """Release dogfood skill should compare payload bytes when session-level token totals are dominated by fixed overhead."""
    workflow = ROOT / "skills" / "release" / "workflows" / "dogfood" / "SKILL.md"
    if not workflow.exists():
        pytest.fail(f"{workflow} not found")
    content = workflow.read_text(encoding="utf-8")
    assert "payload_bytes.total_result_bytes" in content, "dogfood release skill 未要求比較 total_result_bytes"
    assert "payload_bytes.search_result_bytes" in content, "dogfood release skill 未要求比較 search_result_bytes"
    assert "payload_bytes.read_source_result_bytes" in content, "dogfood release skill 未要求比較 read_source_result_bytes"


@pytest.mark.spec("AC-MIDE-07V2")
def test_ac_mide_07v2_dogfood_workflows_require_token_gate_for_pass_verdict():
    """Dogfood workflows must not allow PASS when token budget is exceeded or contaminated."""
    targets = [
        ROOT / "skills" / "workflows" / "dogfood.md",
        ROOT / "skills" / "release" / "workflows" / "dogfood" / "SKILL.md",
    ]
    for workflow in targets:
        if not workflow.exists():
            pytest.fail(f"{workflow} not found")
        content = workflow.read_text(encoding="utf-8")
        assert "token_budget" in content, f"{workflow} 未要求定義 token_budget"
        assert "token budget failure" in content, f"{workflow} 未定義 token budget failure"
        assert "token budget contaminated" in content, f"{workflow} 未定義 token budget contaminated"
        assert "cache_read_input_tokens" in content, f"{workflow} 未要求檢查 cache_read_input_tokens"
        assert "不得宣稱 dogfood 通過" in content or "不得判定 PASS" in content, (
            f"{workflow} 未禁止 token gate 未過時判定 PASS"
        )


@pytest.mark.spec("AC-MIDE-07V3")
def test_ac_mide_07v3_dogfood_workflows_require_since_text_for_artifact_slicing():
    """Dogfood workflows must slice transcript artifacts by the current DF marker to avoid session pollution."""
    targets = [
        ROOT / "skills" / "workflows" / "dogfood.md",
        ROOT / "skills" / "release" / "workflows" / "dogfood" / "SKILL.md",
    ]
    for workflow in targets:
        if not workflow.exists():
            pytest.fail(f"{workflow} not found")
        content = workflow.read_text(encoding="utf-8")
        assert "--since-text DF-{YYYYMMDD}-{N}" in content, f"{workflow} 未要求 artifact builder 使用 --since-text"
        assert "marker 找不到時 script 會 fail" in content, f"{workflow} 未說明 marker missing 必須 fail"
        assert "其他任務的 MCP calls / token usage" in content, f"{workflow} 未說明 since-text 防止 session 污染"


@pytest.mark.spec("AC-MIDE-07V4")
def test_ac_mide_07v4_dogfood_workflows_require_machine_verdict_for_l3_retrieval():
    """Dogfood workflows must produce verdict.json for L3 retrieval runs instead of relying on manual monitor inspection."""
    targets = [
        ROOT / "skills" / "workflows" / "dogfood.md",
        ROOT / "skills" / "release" / "workflows" / "dogfood" / "SKILL.md",
    ]
    for workflow in targets:
        if not workflow.exists():
            pytest.fail(f"{workflow} not found")
        content = workflow.read_text(encoding="utf-8")
        assert "build_l3_retrieval_artifacts.py" in content, f"{workflow} 未要求一鍵 artifact + verdict wrapper"
        assert "build_l3_retrieval_verdict.py" in content, f"{workflow} 未要求 L3 retrieval verdict builder"
        assert "/tmp/zenos-dogfood/{DF-ID}/verdict.json" in content, f"{workflow} 未定義 verdict artifact"
        assert "不得只靠人工讀 monitor" in content, f"{workflow} 未禁止人工 monitor 判定取代 verdict"
        assert "routing / source delivery / token gate" in content, f"{workflow} 未明確 verdict 三個 gate"
        assert "--token-budget <TOKEN_BUDGET>" in content, f"{workflow} 未要求 wrapper/verdict 帶 token budget"


@pytest.mark.spec("AC-MIDE-07W")
def test_ac_mide_07w_dogfood_release_skill_prefers_read_source_preview_before_full():
    """Release dogfood skill should default to low-cost read_source preview before full-content read."""
    workflow = ROOT / "skills" / "release" / "workflows" / "dogfood" / "SKILL.md"
    if not workflow.exists():
        pytest.fail(f"{workflow} not found")
    content = workflow.read_text(encoding="utf-8")
    assert "preview_chars=1200" in content, "dogfood release skill 未要求 read_source preview_chars"
    assert "只有 preview 不足" in content, "dogfood release skill 未規定 preview 不足才升級 full read"


@pytest.mark.spec("AC-MIDE-07X")
def test_ac_mide_07x_dogfood_workflow_requires_new_top_level_session_after_tool_schema_changes():
    """Dogfood workflow must require a fresh top-level chat session when validating MCP tool schema changes."""
    workflow = ROOT / "skills" / "workflows" / "dogfood.md"
    if not workflow.exists():
        pytest.fail(f"{workflow} not found")
    content = workflow.read_text(encoding="utf-8")
    assert "MCP tool contract / parameter schema" in content, "dogfood workflow 未標示 tool schema 變更 gate"
    assert "新的 top-level chat session" in content, "dogfood workflow 未要求 top-level session refresh"
    assert "同一個聊天內只重開 subagent 不算" in content, "dogfood workflow 未禁止用同聊天 subagent 代替 schema refresh"
    assert "schema freshness blocker" in content, "dogfood workflow 未定義 schema freshness blocker"


@pytest.mark.spec("AC-MIDE-07Y")
def test_ac_mide_07y_dogfood_release_skill_requires_new_top_level_session_after_tool_schema_changes():
    """Release dogfood skill must require a fresh top-level chat session when validating new MCP parameters."""
    workflow = ROOT / "skills" / "release" / "workflows" / "dogfood" / "SKILL.md"
    if not workflow.exists():
        pytest.fail(f"{workflow} not found")
    content = workflow.read_text(encoding="utf-8")
    assert "MCP tool contract / parameter schema" in content, "dogfood release skill 未標示 tool schema 變更 gate"
    assert "新的 top-level chat session" in content, "dogfood release skill 未要求 top-level session refresh"
    assert "同一個聊天內只重開 subagent 不算" in content, "dogfood release skill 未禁止同聊天 subagent 代替 schema refresh"
    assert "schema freshness blocker" in content, "dogfood release skill 未定義 schema freshness blocker"


@pytest.mark.spec("AC-MIDE-07Z")
def test_ac_mide_07z_dogfood_workflows_expose_schema_freshness_artifact_gate():
    """Dogfood workflows must expose machine-readable schema freshness detection for preview contract verification."""
    workflow = ROOT / "skills" / "workflows" / "dogfood.md"
    release_workflow = ROOT / "skills" / "release" / "workflows" / "dogfood" / "SKILL.md"
    for target in (workflow, release_workflow):
        if not target.exists():
            pytest.fail(f"{target} not found")
        content = target.read_text(encoding="utf-8")
        assert "--expect-read-source-preview" in content, f"{target} 未要求 artifact builder 檢查 preview schema freshness"
        assert "tool_contract.schema_freshness_blocker" in content, f"{target} 未把 schema freshness blocker 接進 monitor artifact"
        assert "findings" in content and "schema freshness blocker" in content, f"{target} 未要求 monitor findings 顯示 schema freshness blocker"


@pytest.mark.spec("AC-MIDE-07J")
def test_ac_mide_07j_release_capture_skill_requires_capture_journal_for_baseline():
    """Release capture skill must make capture journal writes explicit so dogfood baseline can be built from real sessions."""
    workflow = ROOT / "skills" / "release" / "zenos-capture" / "SKILL.md"
    if not workflow.exists():
        pytest.fail(f"{workflow} not found")
    content = workflow.read_text(encoding="utf-8")
    assert "Capture journal" in content, "release capture skill 未加入 capture journal 段落"
    assert 'journal_read(limit=5, project="{PROJECT_NAME}", flow_type="capture")' in content, (
        "release capture skill 未要求先查最近 capture journal"
    )
    assert 'journal_write(' in content and 'flow_type="capture"' in content, (
        "release capture skill 未明示寫入 flow_type=capture journal"
    )


@pytest.mark.spec("AC-MIDE-07J")
def test_ac_mide_07j_release_capture_skill_routes_binary_assets_as_controlled_assets():
    """Release capture skill must route artifacts by governance role, not by extension."""
    workflow = ROOT / "skills" / "release" / "zenos-capture" / "SKILL.md"
    if not workflow.exists():
        pytest.fail(f"{workflow} not found")
    content = workflow.read_text(encoding="utf-8")
    assert "任何 artifact 先判斷治理角色" in content
    assert "不先看副檔名" in content
    assert "controlled asset metadata" in content
    assert "operational record metadata" in content
    assert "binary、image、PDF、attachment" in content
    assert "說「無法入 ZenOS」" in content
    assert "不要建議公開圖床" in content
    assert "不要因為副檔名建 blindspot" in content


# --- P0: AC-MIDE-08 ---


@pytest.mark.spec("AC-MIDE-08")
def test_ac_mide_08_agent_skills_mention_full_id():
    """AC-MIDE-08: pm/architect/developer/qa/coach SKILL.md 各自提及 full-ID 紀律。"""
    roles = ["pm", "architect", "developer", "qa", "coach"]
    missing = []
    for role in roles:
        skill = ROOT / "skills" / "release" / role / "SKILL.md"
        if not skill.exists():
            missing.append(f"{role}: file missing")
            continue
        content = skill.read_text(encoding="utf-8")
        # Developer 須加入段落，關鍵字任一即可
        keywords = ["full id", "32-char", "32 字元", "full-id", "完整 ID"]
        if not any(kw.lower() in content.lower() for kw in keywords):
            missing.append(f"{role}: 無 full-ID 紀律段落")
    assert not missing, f"缺漏: {missing}"


# ---------------------------------------------------------------------------
# S05: deferred items
# ---------------------------------------------------------------------------


@pytest.mark.spec("S05")
def test_s05_entity_entry_protocol_exists():
    """S05: EntityEntryRepository Protocol exists in domain layer and exposes find_by_id_prefix."""
    from zenos.domain.knowledge.repositories import EntityEntryRepository

    # Protocol class must exist
    assert EntityEntryRepository is not None, "EntityEntryRepository not found in domain repositories"

    # Must declare find_by_id_prefix
    assert hasattr(EntityEntryRepository, "find_by_id_prefix"), (
        "EntityEntryRepository must define find_by_id_prefix"
    )

    # SqlEntityEntryRepository must structurally satisfy the Protocol
    from zenos.infrastructure.knowledge.sql_entity_entry_repo import SqlEntityEntryRepository

    required_methods = [
        "create",
        "get_by_id",
        "list_by_entity",
        "update_status",
        "find_by_id_prefix",
        "search_content",
        "list_saturated_entities",
        "count_active_by_entity",
    ]
    for method in required_methods:
        assert hasattr(SqlEntityEntryRepository, method), (
            f"SqlEntityEntryRepository missing method required by Protocol: {method}"
        )


@pytest.mark.spec("S05")
def test_s05_scanner_since_filter():
    """S05: --since filter excludes events older than the cutoff; window field present in output.

    Fixture s05-since-test/session-since.jsonl has:
    - 1 old rejected event (2020-01-01) — must be excluded by --since 2026-04-01
    - 1 new ok event (2026-04-20) — must be counted

    After filtering: calls=1, rejected=0, reject_rate=0.0
    """
    import subprocess
    import sys

    fixture = ROOT / "tests" / "fixtures" / "transcripts" / "s05-since-test"
    script = ROOT / "scripts" / "dogfood" / "scan_mcp_reject_rate.py"

    result = subprocess.run(
        [
            sys.executable, str(script),
            "--transcripts-dir", str(fixture),
            "--format", "json",
            "--since", "2026-04-01",
        ],
        capture_output=True,
        text=True,
        check=True,
    )
    data = json.loads(result.stdout)

    # window field must be present and match the passed value
    assert "window" in data, "Output JSON must contain 'window' field"
    assert data["window"] == "2026-04-01", f"Expected window='2026-04-01', got {data['window']!r}"

    # Old event filtered out: only 1 call remains (the new ok event)
    assert data["sessions_scanned"] == 1, (
        f"Session with new events must be counted; sessions_scanned={data['sessions_scanned']}"
    )
    assert data["total_mcp_calls"] == 1, (
        f"Only the new event should be counted; total_mcp_calls={data['total_mcp_calls']}"
    )
    assert data["rejected_count"] == 0, (
        f"New event is ok, not rejected; rejected_count={data['rejected_count']}"
    )

    # same_input_retries field must be present
    assert "same_input_retries" in data, "Output JSON must contain 'same_input_retries' field"


@pytest.mark.spec("S05")
def test_s05_scanner_same_input_retries():
    """S05: same_input_retries counts retries of identical (name, input) within 10s after a rejection.

    Fixture s05-retry-test/session-retry.jsonl has:
    - toolu_R1: mcp__zenos__write {collection:entries, id:39f160f5} @ t=0s -> rejected
    - toolu_R2: mcp__zenos__write {collection:entries, id:39f160f5} @ t=5s -> rejected
    Same input, within 10s, first was rejected -> 1 same_input_retry expected.
    """
    import subprocess
    import sys

    fixture = ROOT / "tests" / "fixtures" / "transcripts" / "s05-retry-test"
    script = ROOT / "scripts" / "dogfood" / "scan_mcp_reject_rate.py"

    result = subprocess.run(
        [
            sys.executable, str(script),
            "--transcripts-dir", str(fixture),
            "--format", "json",
        ],
        capture_output=True,
        text=True,
        check=True,
    )
    data = json.loads(result.stdout)

    assert "same_input_retries" in data, "Output JSON must contain 'same_input_retries' field"
    assert data["same_input_retries"] == 1, (
        f"Expected 1 same_input_retry (identical input, within 10s, first rejected); "
        f"got {data['same_input_retries']}"
    )
