"""AC test stubs generated from ADR-047 / PLAN-l1-level-ssot-refactor.

Auto-generated by Architect — Developer / QA fills implementation as each
subtask lands. Red = gap, Green = verified.

AC IDs cover: domain judgement, CRM-company-as-L1, legacy-alias rejection,
governance prompt hygiene, UI surface, data completeness, strict level check.
"""
from __future__ import annotations

from types import SimpleNamespace

import pytest

from zenos.domain.knowledge.collaboration_roots import is_collaboration_root_entity


# --- P0: Domain judgement ---

@pytest.mark.spec("AC-L1SSOT-01")
def test_ac_l1ssot_01_any_type_with_level_1_is_l1():
    """AC-L1SSOT-01: Given an entity with level=1 AND parent_id=None,
    When is_collaboration_root_entity is called,
    Then it returns True regardless of entity.type (product / company / person / deal)."""
    for entity_type in ("product", "company", "person", "deal"):
        entity = SimpleNamespace(type=entity_type, level=1, parent_id=None)
        assert is_collaboration_root_entity(entity) is True, (
            f"Expected L1=True for type={entity_type!r}, level=1, parent_id=None"
        )


@pytest.mark.spec("AC-L1SSOT-07")
def test_ac_l1ssot_07_strict_level_check():
    """AC-L1SSOT-07: Given an entity with level=None (legacy fallback territory),
    When is_collaboration_root_entity is called,
    Then it returns False — the level-null fallback MUST be removed after backfill."""
    # level=None must be rejected (strict mode, ADR-047 D1)
    entity_level_none = SimpleNamespace(type="product", level=None, parent_id=None)
    assert is_collaboration_root_entity(entity_level_none) is False, (
        "level=None should return False — level-null fallback has been removed"
    )
    # Confirm level=1 still works as sanity check
    entity_level_1 = SimpleNamespace(type="product", level=1, parent_id=None)
    assert is_collaboration_root_entity(entity_level_1) is True


# --- P0: CRM integration ---

@pytest.mark.spec("AC-L1SSOT-02")
def test_ac_l1ssot_02_crm_company_accepted_as_product_id():
    """AC-L1SSOT-02: Given a CRM-created entity with type=company and level=1,
    When plan(action="create", product_id=<company_id>) is called,
    Then the plan is created successfully (no INVALID_PRODUCT_ID rejection)."""
    pytest.skip("Pending S03 — Application layer refactor not yet landed")


# --- P0: Legacy alias rejection ---

@pytest.mark.spec("AC-L1SSOT-03")
@pytest.mark.asyncio
async def test_ac_l1ssot_03_project_id_param_rejected():
    """AC-L1SSOT-03: Given a caller passes project_id parameter to MCP plan/task,
    When the tool is invoked via the PUBLIC WRAPPER (the path MCP callers actually hit),
    Then server responds with structured INVALID_INPUT (not a Python TypeError).

    Two layers verified:
    1. Public wrapper (plan / task) — the FastMCP-registered entry point
    2. Internal handler (_plan_handler / _task_handler) — defense-in-depth
    """
    from zenos.interface.mcp.plan import plan as plan_tool
    from zenos.interface.mcp.task import task as task_tool
    from zenos.interface.mcp.plan import _plan_handler
    from zenos.interface.mcp.task import _task_handler

    # --- Layer 1: Public wrapper path (what MCP callers actually hit) ---

    # plan() public wrapper must return structured rejection, not raise TypeError
    result = await plan_tool(action="create", goal="x", project_id="should-reject")
    assert result.get("status") == "rejected", (
        f"plan() public wrapper: expected status=rejected when project_id passed, got: {result}"
    )
    assert result.get("data", {}).get("error") == "INVALID_INPUT", (
        f"plan() public wrapper: expected data.error=INVALID_INPUT, got: {result}"
    )

    # task() public wrapper must return structured rejection, not raise TypeError
    result = await task_tool(action="create", title="qa test", project_id="should-reject")
    assert result.get("status") == "rejected", (
        f"task() public wrapper: expected status=rejected when project_id passed, got: {result}"
    )
    assert result.get("data", {}).get("error") == "INVALID_INPUT", (
        f"task() public wrapper: expected data.error=INVALID_INPUT, got: {result}"
    )

    # --- Layer 2: Internal handler defense-in-depth (direct handler calls) ---

    # _plan_handler still guards via **kwargs (defense in depth)
    result = await _plan_handler(action="create", goal="x", project_id="y")
    assert result.get("status") == "rejected", (
        f"_plan_handler: expected status=rejected when project_id passed, got: {result}"
    )
    assert result.get("data", {}).get("error") == "INVALID_INPUT" or (
        "INVALID_INPUT" in str(result)
    ), f"_plan_handler: expected INVALID_INPUT error code, got: {result}"

    # _task_handler still guards via **kwargs (defense in depth)
    result = await _task_handler(action="create", title="x", project_id="y")
    assert result.get("status") == "rejected", (
        f"_task_handler: expected status=rejected when project_id passed, got: {result}"
    )
    assert result.get("data", {}).get("error") == "INVALID_INPUT" or (
        "INVALID_INPUT" in str(result)
    ), f"_task_handler: expected INVALID_INPUT error code, got: {result}"


# --- P0: Governance prompt hygiene ---

@pytest.mark.spec("AC-L1SSOT-04")
def test_ac_l1ssot_04_governance_prompt_clean():
    """AC-L1SSOT-04: Given governance_guide("task") and governance_guide("plan"),
    When the rendered prompt text is inspected,
    Then it contains neither 'type=product' nor 'PROJECT_STRING_IGNORED' substrings."""
    from zenos.interface.governance_rules import GOVERNANCE_RULES

    # Collect all task governance text (levels 1 and 2)
    task_rules = GOVERNANCE_RULES.get("task", {})
    all_task_text = "\n".join(str(v) for v in task_rules.values())

    # Collect all plan governance text if present
    plan_rules = GOVERNANCE_RULES.get("plan", {})
    all_plan_text = "\n".join(str(v) for v in plan_rules.values())

    combined = all_task_text + "\n" + all_plan_text

    assert "type=product" not in combined, (
        "governance_rules.py still contains 'type=product' — agent will be misled. "
        "Remove all type=product references from GOVERNANCE_RULES."
    )
    assert "type ≠ product" not in combined, (
        "governance_rules.py still contains 'type ≠ product' — agent will be misled."
    )
    assert "PROJECT_STRING_IGNORED" not in combined, (
        "governance_rules.py still contains 'PROJECT_STRING_IGNORED' — this warning code "
        "should no longer appear in agent prompts after ADR-047 D3."
    )


# --- P0: Dashboard surface ---

@pytest.mark.spec("AC-L1SSOT-05")
def test_ac_l1ssot_05_dashboard_projects_shows_all_l1():
    """AC-L1SSOT-05: Given a workspace containing L1 entities of multiple types
    (product, company, person, deal),
    When /projects page renders,
    Then all of them are displayed — UI filter is level-based, not type-based.

    (Verified via vitest on dashboard side; this Python stub asserts the API
    contract that /api/data/entities?level=1 returns all L1 regardless of type.)"""
    pytest.skip(
        "Covered by vitest: dashboard/src/__tests__/l1_level_ssot_ac.test.ts — "
        "isL1Entity, buildAvailableProjectOptions, isPortfolioRootProduct, "
        "TaskCreateDialog productOptions all verified level-based in vitest suite"
    )


# --- P0: Data completeness ---

@pytest.mark.spec("AC-L1SSOT-06")
def test_ac_l1ssot_06_production_level_no_null():
    """AC-L1SSOT-06: Given production DB post-backfill,
    When SELECT COUNT(*) FROM zenos.entities WHERE level IS NULL is executed,
    Then the count equals 0 — every entity has an explicit level assigned.

    (This AC is verified via backfill_entity_level.py apply-mode report +
    QA independent SQL spot-check during GATE A.)"""
    pytest.skip("Verified out-of-band in GATE A (production SQL check); no in-repo assertion")
