"""AC test stubs generated from ADR-047 / PLAN-l1-level-ssot-refactor.

Auto-generated by Architect — Developer / QA fills implementation as each
subtask lands. Red = gap, Green = verified.

AC IDs cover: domain judgement, CRM-company-as-L1, legacy-alias rejection,
governance prompt hygiene, UI surface, data completeness, strict level check.
"""
from __future__ import annotations

import pytest


# --- P0: Domain judgement ---

@pytest.mark.spec("AC-L1SSOT-01")
def test_ac_l1ssot_01_any_type_with_level_1_is_l1():
    """AC-L1SSOT-01: Given an entity with level=1 AND parent_id=None,
    When is_collaboration_root_entity is called,
    Then it returns True regardless of entity.type (product / company / person / deal)."""
    pytest.fail("NOT IMPLEMENTED — Developer must fill this test in S02-code")


@pytest.mark.spec("AC-L1SSOT-07")
def test_ac_l1ssot_07_strict_level_check():
    """AC-L1SSOT-07: Given an entity with level=None (legacy fallback territory),
    When is_collaboration_root_entity is called,
    Then it returns False — the level-null fallback MUST be removed after backfill."""
    pytest.fail("NOT IMPLEMENTED — Developer must fill this test in S02-code")


# --- P0: CRM integration ---

@pytest.mark.spec("AC-L1SSOT-02")
def test_ac_l1ssot_02_crm_company_accepted_as_product_id():
    """AC-L1SSOT-02: Given a CRM-created entity with type=company and level=1,
    When plan(action="create", product_id=<company_id>) is called,
    Then the plan is created successfully (no INVALID_PRODUCT_ID rejection)."""
    pytest.fail("NOT IMPLEMENTED — Developer must fill this test in S03")


# --- P0: Legacy alias rejection ---

@pytest.mark.spec("AC-L1SSOT-03")
def test_ac_l1ssot_03_project_id_param_rejected():
    """AC-L1SSOT-03: Given a caller passes project_id parameter to MCP plan/task,
    When the tool is invoked,
    Then server responds with INVALID_INPUT (no silent accept, no alias mapping)."""
    pytest.fail("NOT IMPLEMENTED — Developer must fill this test in S04")


# --- P0: Governance prompt hygiene ---

@pytest.mark.spec("AC-L1SSOT-04")
def test_ac_l1ssot_04_governance_prompt_clean():
    """AC-L1SSOT-04: Given governance_guide("task") and governance_guide("plan"),
    When the rendered prompt text is inspected,
    Then it contains neither 'type=product' nor 'project_id' substrings."""
    pytest.fail("NOT IMPLEMENTED — Developer must fill this test in S04")


# --- P0: Dashboard surface ---

@pytest.mark.spec("AC-L1SSOT-05")
def test_ac_l1ssot_05_dashboard_projects_shows_all_l1():
    """AC-L1SSOT-05: Given a workspace containing L1 entities of multiple types
    (product, company, person, deal),
    When /projects page renders,
    Then all of them are displayed — UI filter is level-based, not type-based.

    (Verified via vitest on dashboard side; this Python stub asserts the API
    contract that /api/data/entities?level=1 returns all L1 regardless of type.)"""
    pytest.fail("NOT IMPLEMENTED — Developer must fill this test in S06")


# --- P0: Data completeness ---

@pytest.mark.spec("AC-L1SSOT-06")
def test_ac_l1ssot_06_production_level_no_null():
    """AC-L1SSOT-06: Given production DB post-backfill,
    When SELECT COUNT(*) FROM zenos.entities WHERE level IS NULL is executed,
    Then the count equals 0 — every entity has an explicit level assigned.

    (This AC is verified via backfill_entity_level.py apply-mode report +
    QA independent SQL spot-check during GATE A.)"""
    pytest.fail("NOT IMPLEMENTED — Developer/QA must verify this in S02-data + S08")
