"""
AC test stubs generated from SPEC-mcp-write-auto-publish-resilience.
Auto-generated by Architect - Developer fills implementation.
Red = gap, Green = verified.
"""

from datetime import datetime, timezone
from unittest.mock import AsyncMock, MagicMock, patch

import pytest

from zenos.domain.knowledge import Entity, Tags
from zenos.infrastructure.context import current_partner_id
from zenos.interface.mcp._auth import _current_partner
from zenos.interface.mcp.write import _maybe_auto_publish_document, write

pytestmark = pytest.mark.asyncio


class _Acquire:
    def __init__(self, conn):
        self._conn = conn

    async def __aenter__(self):
        return self._conn

    async def __aexit__(self, exc_type, exc, tb):
        return False


def _document_entity(**overrides) -> Entity:
    defaults = {
        "id": "doc-wapr-1",
        "name": "MCP write auto-publish resilience",
        "type": "document",
        "summary": "Regression document",
        "tags": Tags(what=["mcp"], why="resilience", how="test", who=["developer"]),
        "status": "current",
        "parent_id": None,
        "details": {"formal_entry": True},
        "sources": [{
            "source_id": "src-1",
            "type": "github",
            "uri": "https://github.com/acme/repo/blob/main/docs/spec.md",
            "status": "valid",
            "source_status": "valid",
            "is_primary": True,
        }],
        "doc_role": "single",
        "confirmed_by_user": True,
        "created_at": datetime(2026, 1, 1, tzinfo=timezone.utc),
        "updated_at": datetime(2026, 5, 1, tzinfo=timezone.utc),
    }
    defaults.update(overrides)
    return Entity(**defaults)


def _pool_without_snapshot():
    conn = MagicMock()
    conn.fetchrow = AsyncMock(return_value={"primary_snapshot_revision_id": None, "delivery_status": None})
    pool = MagicMock()
    pool.acquire = MagicMock(return_value=_Acquire(conn))
    return pool


def _current_partner_tokens():
    partner_token = _current_partner.set({"id": "partner-wapr", "isAdmin": True})
    partner_id_token = current_partner_id.set("partner-wapr")
    return partner_token, partner_id_token


def _reset_current_partner_tokens(tokens) -> None:
    partner_token, partner_id_token = tokens
    current_partner_id.reset(partner_id_token)
    _current_partner.reset(partner_token)


@pytest.mark.spec("AC-WAPR-01")
async def test_ac_wapr_01_write_survives_auto_publish_failure():
    """AC-WAPR-01: Given write upsert succeeds for a current formal-entry GitHub document, When auto-publish fails, Then write returns ok with warning/suggestion and no MCP-layer exception."""
    tokens = _current_partner_tokens()
    doc = _document_entity()
    try:
        with (
            patch("zenos.interface.mcp._ensure_services", new=AsyncMock(return_value=None)),
            patch("zenos.interface.mcp.ontology_service") as ontology_service,
            patch("zenos.interface.mcp.write.get_pool", new=AsyncMock(return_value=_pool_without_snapshot())),
            patch("zenos.interface.mcp.write._load_document_relationships", new=AsyncMock(return_value=[])),
            patch("zenos.interface.mcp.write._build_context_bundle", new=AsyncMock(return_value={})),
            patch("zenos.interface.mcp.write._audit_log"),
            patch(
                "zenos.interface.dashboard_api._publish_document_snapshot_internal",
                new=AsyncMock(side_effect=FileNotFoundError("GitHub 404")),
            ),
        ):
            ontology_service.upsert_document = AsyncMock(return_value=doc)

            result = await write(
                collection="documents",
                data={
                    "title": "MCP write auto-publish resilience",
                    "summary": "Regression document",
                    "tags": {"what": ["mcp"], "why": "resilience", "how": "test", "who": ["developer"]},
                },
            )

        assert result["status"] == "ok"
        publish_messages = [*result["warnings"], *[str(item) for item in result["suggestions"]]]
        assert any("自動 publish 失敗" in message for message in publish_messages)
    finally:
        _reset_current_partner_tokens(tokens)


@pytest.mark.spec("AC-WAPR-02")
async def test_ac_wapr_02_auto_publish_failure_logs_doc_id():
    """AC-WAPR-02: Given auto-publish fails, When server logging runs, Then log includes doc_id and stack context."""
    tokens = _current_partner_tokens()
    serialized = {
        "id": "doc-wapr-log",
        "status": "current",
        "details": {"formal_entry": True},
        "doc_role": "single",
        "sources": [{"type": "github", "uri": "https://github.com/acme/repo/blob/main/docs/spec.md"}],
    }
    try:
        with (
            patch("zenos.interface.mcp.write.get_pool", new=AsyncMock(return_value=_pool_without_snapshot())),
            patch(
                "zenos.interface.dashboard_api._publish_document_snapshot_internal",
                new=AsyncMock(side_effect=RuntimeError("source read failed")),
            ),
            patch("zenos.interface.mcp.write.logger.warning") as warning_log,
        ):
            suggestions = await _maybe_auto_publish_document(serialized)

        assert any("自動 publish 失敗" in suggestion for suggestion in suggestions)
        warning_log.assert_called_once()
        args, kwargs = warning_log.call_args
        assert "doc-wapr-log" in args
        assert kwargs.get("exc_info") is True
    finally:
        _reset_current_partner_tokens(tokens)


@pytest.mark.spec("AC-WAPR-03")
async def test_ac_wapr_03_non_formal_document_skips_auto_publish():
    """AC-WAPR-03: Given document does not meet current formal-entry GitHub auto-publish conditions, When write succeeds, Then publish internal is not called and no auto-publish warning is added."""
    tokens = _current_partner_tokens()
    non_target_documents = [
        {
            "id": "doc-draft",
            "status": "draft",
            "details": {"formal_entry": True},
            "doc_role": "single",
            "sources": [{"type": "github", "uri": "https://github.com/acme/repo/blob/main/docs/spec.md"}],
        },
        {
            "id": "doc-non-formal",
            "status": "current",
            "details": {"formal_entry": False},
            "doc_role": "single",
            "sources": [{"type": "github", "uri": "https://github.com/acme/repo/blob/main/docs/spec.md"}],
        },
        {
            "id": "doc-non-github",
            "status": "current",
            "details": {"formal_entry": True},
            "doc_role": "single",
            "sources": [{"type": "zenos_native", "uri": "/docs/doc-non-github"}],
        },
    ]
    try:
        with patch("zenos.interface.dashboard_api._publish_document_snapshot_internal", new=AsyncMock()) as publish:
            for serialized in non_target_documents:
                suggestions = await _maybe_auto_publish_document(serialized)
                assert suggestions == []

        publish.assert_not_called()
    finally:
        _reset_current_partner_tokens(tokens)


@pytest.mark.spec("AC-WAPR-04")
async def test_ac_wapr_04_preflight_hard_invalid_still_rejects():
    """AC-WAPR-04: Given explicit preflight hard invalid current formal-entry GitHub source, When write handles payload, Then response remains rejected and resilience does not loosen preflight."""
    with (
        patch("zenos.interface.mcp._ensure_services", new=AsyncMock(return_value=None)),
        patch("zenos.interface.mcp.ontology_service") as ontology_service,
        patch(
            "zenos.interface.mcp.write._check_github_source_remote_visibility",
            new=AsyncMock(return_value=(False, "GitHub source 尚未 remote 可見：missing", True)),
        ),
    ):
        ontology_service.upsert_document = AsyncMock()

        result = await write(
            collection="documents",
            data={
                "title": "Missing remote index",
                "summary": "Remote source is missing",
                "status": "current",
                "doc_role": "index",
                "details": {"formal_entry": True},
                "sources": [{
                    "source_id": "src-1",
                    "type": "github",
                    "uri": "https://github.com/acme/repo/blob/main/docs/missing.md",
                    "is_primary": True,
                }],
                "bundle_highlights": [{
                    "source_id": "src-1",
                    "headline": "Primary",
                    "reason_to_read": "Primary source",
                    "priority": "primary",
                }],
            },
        )

    assert result["status"] == "rejected"
    assert "remote 可見" in result["rejection_reason"]
    assert any("GitHub source 尚未 remote 可見" in warning for warning in result["warnings"])
    ontology_service.upsert_document.assert_not_called()
