"""
AC test stubs generated from SPEC-task-governance §2026-04-19 Action-Layer 升級.
Auto-generated by Architect — Developer fills implementation.
Red = gap, Green = verified.

Run: .venv/bin/pytest tests/spec_compliance/test_task_action_upgrade_ac.py -x
"""
from __future__ import annotations

from pathlib import Path
from datetime import datetime, timezone
from unittest.mock import AsyncMock, MagicMock, patch

import pytest

ROOT = Path(__file__).resolve().parents[2]


def _make_uow_factory():
    uow = MagicMock()
    uow.conn = MagicMock()
    uow.__aenter__ = AsyncMock(return_value=uow)
    uow.__aexit__ = AsyncMock(return_value=False)
    return lambda: uow


# ─────────────────────────────────────────────────────────────
# P0 — Schema & DB migration
# ─────────────────────────────────────────────────────────────

@pytest.mark.spec("AC-TASK-UPG-01")
def test_ac_task_upg_01_schema_columns_with_index():
    """AC-TASK-UPG-01: tasks table 加 parent_task_id TEXT、dispatcher TEXT、
    handoff_events JSONB DEFAULT '[]'，並有 index on parent_task_id 與 dispatcher."""
    # Verify migration file exists and contains the required DDL
    migration = ROOT / "migrations" / "20260419_0001_task_action_layer_upgrade.sql"
    assert migration.exists(), "Migration file not found"
    sql = migration.read_text(encoding="utf-8")

    assert "parent_task_id TEXT" in sql, "Migration must add parent_task_id TEXT column"
    assert "dispatcher TEXT" in sql, "Migration must add dispatcher TEXT column"
    assert "handoff_events JSONB" in sql, "Migration must add handoff_events JSONB column"
    assert "DEFAULT '[]'::jsonb" in sql, "handoff_events must default to empty JSONB array"
    assert "idx_tasks_parent_task_id" in sql, "Migration must create index on parent_task_id"
    assert "idx_tasks_dispatcher" in sql, "Migration must create index on dispatcher"

    # Verify domain model carries the three new fields
    from zenos.domain.action.models import Task, HandoffEvent, DISPATCHER_PATTERN
    import dataclasses
    task_fields = {f.name for f in dataclasses.fields(Task)}
    assert "parent_task_id" in task_fields, "Task dataclass must have parent_task_id field"
    assert "dispatcher" in task_fields, "Task dataclass must have dispatcher field"
    assert "handoff_events" in task_fields, "Task dataclass must have handoff_events field"

    # Verify HandoffEvent dataclass structure
    he_fields = {f.name for f in dataclasses.fields(HandoffEvent)}
    assert he_fields == {"at", "from_dispatcher", "to_dispatcher", "reason", "output_ref", "notes"}

    # Verify DISPATCHER_PATTERN is exported from domain
    assert DISPATCHER_PATTERN is not None
    assert DISPATCHER_PATTERN.match("human")
    assert DISPATCHER_PATTERN.match("human:barry")
    assert DISPATCHER_PATTERN.match("agent:pm")
    assert not DISPATCHER_PATTERN.match("AGENT:PM")

    # Verify repo upsert SQL includes new columns
    import inspect
    from zenos.infrastructure.action.sql_task_repo import SqlTaskRepository
    upsert_source = inspect.getsource(SqlTaskRepository.upsert)
    assert "parent_task_id" in upsert_source
    assert "dispatcher" in upsert_source
    assert "handoff_events" in upsert_source


# ─────────────────────────────────────────────────────────────
# P0 — Validators
# ─────────────────────────────────────────────────────────────

@pytest.mark.spec("AC-TASK-UPG-02")
async def test_ac_task_upg_02_cross_plan_subtask_reject():
    """AC-TASK-UPG-02: Given parent task with plan_id=P1, When write(tasks)
    with parent_task_id=<parent> and plan_id=P2, Then reject with
    error_code=CROSS_PLAN_SUBTASK."""
    from zenos.application.action.task_service import TaskService, TaskValidationError
    from zenos.domain.action import Task

    # Build a parent task with plan_id=plan-P1
    parent_task = Task(
        id="parent-task-1",
        title="Parent task",
        status="in_progress",
        priority="medium",
        created_by="pm",
        plan_id="plan-P1",
    )

    task_repo = AsyncMock()
    task_repo.get_by_id = AsyncMock(return_value=parent_task)
    task_repo.upsert = AsyncMock(side_effect=lambda t: t)
    entity_repo = AsyncMock()
    entity_repo.get_by_id = AsyncMock(return_value=None)
    blindspot_repo = AsyncMock()

    svc = TaskService(task_repo, entity_repo, blindspot_repo)

    # Attempt to create a subtask with plan_id=plan-P2 (cross-plan)
    with pytest.raises(TaskValidationError) as exc_info:
        await svc.create_task({
            "title": "實作跨計畫的 subtask 驗證",
            "created_by": "dev",
            "parent_task_id": "parent-task-1",
            "plan_id": "plan-P2",  # different from parent's plan-P1
        })

    err = exc_info.value
    assert err.error_code == "CROSS_PLAN_SUBTASK", (
        f"Expected error_code=CROSS_PLAN_SUBTASK, got '{err.error_code}'"
    )
    assert "plan_id" in str(err).lower() or "cross" in str(err).lower()

    # Also verify via _task_handler at the MCP layer
    from zenos.interface.mcp.task import _task_handler

    with patch("zenos.interface.mcp._ensure_services", new=AsyncMock()), \
         patch("zenos.interface.mcp.task._current_partner") as mock_cp, \
         patch("zenos.interface.mcp.task._audit_log"), \
         patch("zenos.interface.mcp.task_service") as mock_svc:
        mock_cp.get.return_value = {"id": "partner-1", "defaultProject": "zenos"}
        mock_svc.create_task = AsyncMock(
            side_effect=TaskValidationError(
                "CROSS_PLAN_SUBTASK error",
                error_code="CROSS_PLAN_SUBTASK",
            )
        )
        result = await _task_handler(
            action="create",
            title="實作跨計畫 subtask",
            parent_task_id="parent-task-1",
            plan_id="plan-P2",
        )

    assert result["status"] in ("rejected", "error"), f"Expected rejection, got: {result['status']}"
    # error_code may appear at root or inside data.error.code depending on _error_response format
    response_text = str(result)
    assert "CROSS_PLAN_SUBTASK" in response_text, (
        f"Expected CROSS_PLAN_SUBTASK in response: {result}"
    )

    # PARENT_NOT_FOUND: parent does not exist
    task_repo2 = AsyncMock()
    task_repo2.get_by_id = AsyncMock(return_value=None)  # parent not found
    task_repo2.upsert = AsyncMock(side_effect=lambda t: t)
    entity_repo2 = AsyncMock()
    entity_repo2.get_by_id = AsyncMock(return_value=None)
    blindspot_repo2 = AsyncMock()
    svc2 = TaskService(task_repo2, entity_repo2, blindspot_repo2)

    with pytest.raises(TaskValidationError) as exc_info2:
        await svc2.create_task({
            "title": "實作不存在父 task 的驗證",
            "created_by": "dev",
            "parent_task_id": "nonexistent-parent",
            "plan_id": "plan-P1",
        })

    assert exc_info2.value.error_code == "PARENT_NOT_FOUND"


@pytest.mark.spec("AC-TASK-UPG-03")
async def test_ac_task_upg_03_invalid_dispatcher_reject():
    """AC-TASK-UPG-03: Given dispatcher value not matching
    ^(human(:[a-zA-Z0-9_-]+)?|agent:[a-z_]+)$, When write(tasks) or
    task(action="handoff"), Then reject with error_code=INVALID_DISPATCHER.
    Test: "human" OK, "human:barry" OK, "agent:pm" OK, "AGENT:PM" reject,
    "agent:pm!" reject, "random_string" reject."""
    from zenos.domain.action.models import DISPATCHER_PATTERN

    # Positive cases — must match
    valid = ["human", "human:barry", "human:barry-123", "agent:pm", "agent:architect",
             "agent:developer", "agent:qa", "agent:pm_lead"]
    for val in valid:
        assert DISPATCHER_PATTERN.match(val), f"Expected '{val}' to be VALID dispatcher"

    # Negative cases — must not match
    invalid = ["AGENT:PM", "Agent:pm", "agent:PM", "agent:pm!", "random_string",
               "human:Barry!", "agent:", ":agent:pm", "human:with space"]
    for val in invalid:
        assert not DISPATCHER_PATTERN.match(val), f"Expected '{val}' to be INVALID dispatcher"

    # Verify service raises INVALID_DISPATCHER on create
    from zenos.application.action.task_service import TaskService, TaskValidationError

    task_repo = AsyncMock()
    task_repo.upsert = AsyncMock(side_effect=lambda t: t)
    entity_repo = AsyncMock()
    entity_repo.get_by_id = AsyncMock(return_value=None)
    blindspot_repo = AsyncMock()
    svc = TaskService(task_repo, entity_repo, blindspot_repo)

    with pytest.raises(TaskValidationError) as exc_info:
        await svc.create_task({
            "title": "實作無效 dispatcher 任務",
            "created_by": "pm",
            "dispatcher": "AGENT:PM",  # invalid
        })

    assert exc_info.value.error_code == "INVALID_DISPATCHER"

    # Valid dispatcher — no error
    from zenos.domain.action import Task
    task_repo2 = AsyncMock()
    task_repo2.upsert = AsyncMock(side_effect=lambda t: t)
    entity_repo2 = AsyncMock()
    entity_repo2.get_by_id = AsyncMock(return_value=None)
    blindspot_repo2 = AsyncMock()
    svc2 = TaskService(task_repo2, entity_repo2, blindspot_repo2)
    result = await svc2.create_task({
        "title": "實作有效 dispatcher 任務",
        "created_by": "pm",
        "dispatcher": "agent:pm",
    })
    assert result.task.dispatcher == "agent:pm"

    # Verify update path also rejects invalid dispatcher
    existing = Task(id="t1", title="T", status="todo", priority="medium", created_by="pm")
    task_repo3 = AsyncMock()
    task_repo3.get_by_id = AsyncMock(return_value=existing)
    task_repo3.upsert = AsyncMock(side_effect=lambda t: t)
    entity_repo3 = AsyncMock()
    blindspot_repo3 = AsyncMock()
    svc3 = TaskService(task_repo3, entity_repo3, blindspot_repo3)

    with pytest.raises(TaskValidationError) as exc_info2:
        await svc3.update_task("t1", {"dispatcher": "agent:pm!"})

    assert exc_info2.value.error_code == "INVALID_DISPATCHER"

    # Verify MCP layer propagates INVALID_DISPATCHER error_code
    from zenos.interface.mcp.task import _task_handler

    with patch("zenos.interface.mcp._ensure_services", new=AsyncMock()), \
         patch("zenos.interface.mcp.task._current_partner") as mock_cp, \
         patch("zenos.interface.mcp.task._audit_log"), \
         patch("zenos.interface.mcp.task_service") as mock_svc:
        mock_cp.get.return_value = {"id": "partner-1", "defaultProject": "zenos"}
        mock_svc.create_task = AsyncMock(
            side_effect=TaskValidationError(
                "INVALID_DISPATCHER error",
                error_code="INVALID_DISPATCHER",
            )
        )
        result = await _task_handler(
            action="create",
            title="建立無效 dispatcher 任務",
            dispatcher="AGENT:PM",
        )

    assert result["status"] in ("rejected", "error")
    response_text = str(result)
    assert "INVALID_DISPATCHER" in response_text, (
        f"Expected INVALID_DISPATCHER in response: {result}"
    )


@pytest.mark.spec("AC-TASK-UPG-04")
async def test_ac_task_upg_04_handoff_events_readonly_on_write():
    """AC-TASK-UPG-04: Given task with handoff_events=[e1, e2],
    When write(tasks, data={handoff_events: []}), Then the field is ignored,
    response carries warning HANDOFF_EVENTS_READONLY, DB still has [e1, e2]."""
    from zenos.interface.mcp.task import _task_handler
    from zenos.application.action.task_service import TaskResult
    from zenos.domain.action import Task, HandoffEvent
    from datetime import datetime, timezone

    e1 = HandoffEvent(
        at=datetime(2026, 4, 19, 10, 0, tzinfo=timezone.utc),
        from_dispatcher=None,
        to_dispatcher="agent:pm",
        reason="initial",
    )
    e2 = HandoffEvent(
        at=datetime(2026, 4, 19, 12, 0, tzinfo=timezone.utc),
        from_dispatcher="agent:pm",
        to_dispatcher="agent:developer",
        reason="spec ready",
    )
    existing_task = Task(
        id="task-with-events",
        title="Task with handoff history",
        status="in_progress",
        priority="medium",
        created_by="pm",
        handoff_events=[e1, e2],
    )
    # update_task should NOT receive handoff_events key in updates dict
    updated_task = Task(
        id="task-with-events",
        title="Task with handoff history",
        status="in_progress",
        priority="medium",
        created_by="pm",
        handoff_events=[e1, e2],  # preserved — handoff_events not overwritten
    )
    mock_task_result = TaskResult(task=updated_task, cascade_updates=[])

    mock_task_svc = AsyncMock()
    mock_task_svc._tasks = AsyncMock()
    mock_task_svc._tasks.get_by_id = AsyncMock(return_value=existing_task)
    mock_task_svc.update_task = AsyncMock(return_value=mock_task_result)

    with patch("zenos.interface.mcp._ensure_services", new=AsyncMock()), \
         patch("zenos.interface.mcp.task._current_partner") as mock_cp, \
         patch("zenos.interface.mcp.task._audit_log"), \
         patch("zenos.interface.mcp.task_service", mock_task_svc), \
         patch("zenos.interface.mcp.task._enrich_task_result", new=AsyncMock(
             return_value={"id": "task-with-events", "title": "Task with handoff history"}
         )):
        mock_cp.get.return_value = {"id": "partner-1", "defaultProject": "zenos"}
        result = await _task_handler(
            action="update",
            id="task-with-events",
            handoff_events=[],  # caller attempts to clear handoff_events — must be ignored
        )

    # Response must be ok (not rejected)
    assert result["status"] == "ok", f"Expected status=ok, got: {result['status']}"

    # Response must carry HANDOFF_EVENTS_READONLY warning
    warnings = result.get("warnings") or []
    assert "HANDOFF_EVENTS_READONLY" in warnings, (
        f"Expected HANDOFF_EVENTS_READONLY in warnings, got: {warnings}"
    )

    # update_task must NOT have received handoff_events in updates dict
    call_kwargs = mock_task_svc.update_task.call_args
    updates_passed = call_kwargs[0][1] if call_kwargs[0] else call_kwargs[1].get("updates", {})
    assert "handoff_events" not in updates_passed, (
        f"handoff_events must not be forwarded to update_task, got: {updates_passed}"
    )

    # Confirm the task's handoff_events are unchanged (still [e1, e2])
    assert len(updated_task.handoff_events) == 2
    assert updated_task.handoff_events[0].to_dispatcher == "agent:pm"
    assert updated_task.handoff_events[1].to_dispatcher == "agent:developer"


# ─────────────────────────────────────────────────────────────
# P0 — Handoff action
# ─────────────────────────────────────────────────────────────

@pytest.mark.spec("AC-TASK-UPG-05")
async def test_ac_task_upg_05_handoff_atomic_append_and_state_changes():
    """AC-TASK-UPG-05: Given task with status=in_progress and
    dispatcher="agent:developer", When task(action="handoff", id=T, data=
    {to_dispatcher:"agent:qa", reason:"ready for review"}), Then:
    (a) handoff_events appends {at, from:"agent:developer", to:"agent:qa",
        reason, ...}
    (b) task.dispatcher == "agent:qa"
    (c) task.status == "review" (auto-bumped because qa + in_progress)
    (d) audit log event ontology.task.handoff written
    All four must be atomic (fail together or all apply)."""
    from zenos.application.action.task_service import TaskService, TaskResult
    from zenos.domain.action import Task
    from zenos.interface.mcp.task import _task_handler

    task_repo = AsyncMock()
    task_repo.get_by_id = AsyncMock(return_value=Task(
        id="task-1",
        title="Developer task",
        status="in_progress",
        priority="medium",
        created_by="partner-1",
        dispatcher="agent:developer",
    ))
    task_repo.upsert = AsyncMock(side_effect=lambda task, **_: task)
    svc = TaskService(task_repo, AsyncMock(), AsyncMock(), uow_factory=_make_uow_factory())

    result = await svc.handoff_task(
        "task-1",
        to_dispatcher="agent:qa",
        reason="ready for review",
        updated_by="partner-1",
    )

    assert result.task.dispatcher == "agent:qa"
    assert result.task.status == "review"
    assert len(result.task.handoff_events) == 1
    assert result.task.handoff_events[0].from_dispatcher == "agent:developer"
    assert result.task.handoff_events[0].to_dispatcher == "agent:qa"
    assert result.task.handoff_events[0].reason == "ready for review"
    task_repo.upsert.assert_awaited_once()

    with patch("zenos.interface.mcp._ensure_services", new=AsyncMock()), \
         patch("zenos.interface.mcp.task._current_partner") as mock_cp, \
         patch("zenos.interface.mcp.task._audit_log") as mock_audit, \
         patch("zenos.interface.mcp.task._enrich_task_result", new=AsyncMock(
             return_value={"id": "task-1", "dispatcher": "agent:qa", "status": "review"}
         )), \
         patch("zenos.interface.mcp.task_service", AsyncMock(handoff_task=AsyncMock(return_value=TaskResult(task=result.task, cascade_updates=[])))):
        mock_cp.get.return_value = {"id": "partner-1", "defaultProject": "zenos"}
        mcp_result = await _task_handler(
            action="handoff",
            id="task-1",
            to_dispatcher="agent:qa",
            reason="ready for review",
        )

    assert mcp_result["status"] == "ok"
    mock_audit.assert_called_once()
    assert mock_audit.call_args.kwargs["event_type"] == "ontology.task.handoff"


# ─────────────────────────────────────────────────────────────
# P0 — Search filters
# ─────────────────────────────────────────────────────────────

@pytest.mark.spec("AC-TASK-UPG-06")
async def test_ac_task_upg_06_search_filters_dispatcher_parent_linked_entity():
    """AC-TASK-UPG-06: search(tasks) supports three new filters:
    - dispatcher="agent:architect" → only tasks with that dispatcher
    - parent_task_id=T → only subtasks of T
    - linked_entity=E → tasks where E is any member of linked_entities
    All three can combine with existing filters via AND."""
    from zenos.interface.mcp.search import search

    mock_task_service = AsyncMock()
    mock_task_service.list_tasks = AsyncMock(return_value=[
        MagicMock(id="task-1", title="Architect task", description="", linked_entities=["entity-1"]),
    ])

    with patch("zenos.interface.mcp._ensure_services", new=AsyncMock()), \
         patch("zenos.interface.mcp.search._current_partner") as mock_cp, \
         patch("zenos.interface.mcp.search._is_task_visible", new=AsyncMock(return_value=True)), \
         patch("zenos.interface.mcp.search._enrich_task_result", new=AsyncMock(return_value={"id": "task-1"})), \
         patch("zenos.interface.mcp.task_service", mock_task_service):
        mock_cp.get.return_value = {"id": "partner-1", "defaultProject": "zenos"}
        result = await search(
            collection="tasks",
            dispatcher="agent:architect",
            parent_task_id="parent-1",
            linked_entity="entity-1",
        )

    assert result["status"] == "ok"
    assert result["data"]["tasks"] == [{"id": "task-1"}]
    mock_task_service.list_tasks.assert_awaited_once_with(
        assignee=None,
        created_by=None,
        status=None,
        dispatcher="agent:architect",
        parent_task_id="parent-1",
        linked_entity="entity-1",
        limit=200,
        offset=0,
        project="zenos",
        product_id=None,
        plan_id=None,
    )


@pytest.mark.spec("AC-TASK-UPG-07")
async def test_ac_task_upg_07_filter_composability_with_product_id():
    """AC-TASK-UPG-07: search(tasks, product_id=P, dispatcher="agent:qa",
    parent_task_id=T) applies all four filters AND; result is subset of each
    individual filter. Verifies DF-20260419-7 F12 fix preserved alongside
    new filters."""
    from zenos.interface.mcp.search import search

    keep = MagicMock(id="task-keep", title="Keep", description="", linked_entities=["module-1"])

    mock_task_service = AsyncMock()
    mock_task_service.list_tasks = AsyncMock(return_value=[keep])

    with patch("zenos.interface.mcp._ensure_services", new=AsyncMock()), \
         patch("zenos.interface.mcp.search._current_partner") as mock_cp, \
         patch("zenos.interface.mcp.search._is_task_visible", new=AsyncMock(return_value=True)), \
         patch("zenos.interface.mcp.search._enrich_task_result", new=AsyncMock(side_effect=[
             {"id": "task-keep"},
         ])), \
         patch("zenos.interface.mcp.task_service", mock_task_service):
        mock_cp.get.return_value = {"id": "partner-1", "defaultProject": "zenos"}
        result = await search(
            collection="tasks",
            product_id="product-1",
            dispatcher="agent:qa",
            parent_task_id="parent-1",
        )

    assert result["status"] == "ok"
    assert [item["id"] for item in result["data"]["tasks"]] == ["task-keep"]
    mock_task_service.list_tasks.assert_awaited_once_with(
        assignee=None,
        created_by=None,
        status=None,
        dispatcher="agent:qa",
        parent_task_id="parent-1",
        linked_entity=None,
        limit=200,
        offset=0,
        project="zenos",
        product_id="product-1",
        plan_id=None,
    )


# ─────────────────────────────────────────────────────────────
# P0 — Confirm integration
# ─────────────────────────────────────────────────────────────

@pytest.mark.spec("AC-TASK-UPG-08")
async def test_ac_task_upg_08_confirm_appends_final_handoff_event():
    """AC-TASK-UPG-08: Given task with status=review, When
    confirm(collection="tasks", id=T, accepted=true), Then handoff_events
    appends a final event {to_dispatcher:"human", reason:"accepted", ...}
    and status becomes "done"."""
    from zenos.application.action.task_service import TaskService
    from zenos.domain.action import HandoffEvent, Task

    task = Task(
        id="task-review",
        title="QA review task",
        status="review",
        priority="medium",
        created_by="partner-1",
        dispatcher="agent:qa",
        handoff_events=[
            HandoffEvent(
                at=datetime(2026, 4, 19, 10, 0, tzinfo=timezone.utc),
                from_dispatcher="agent:developer",
                to_dispatcher="agent:qa",
                reason="ready for review",
            )
        ],
    )

    task_repo = AsyncMock()
    task_repo.get_by_id = AsyncMock(return_value=task)
    task_repo.upsert = AsyncMock(side_effect=lambda current, **_: current)
    task_repo.list_blocked_by = AsyncMock(return_value=[])
    entity_repo = AsyncMock()
    entity_repo.list_by_ids = AsyncMock(return_value=[])
    blindspot_repo = AsyncMock()
    svc = TaskService(task_repo, entity_repo, blindspot_repo, uow_factory=_make_uow_factory())

    result = await svc.confirm_task(
        "task-review",
        accepted=True,
        updated_by="partner-qa",
        entity_entries=[{"entity_id": "entity-1", "type": "insight", "content": "done"}],
    )

    assert result.task.status == "done"
    assert result.task.dispatcher == "human"
    assert result.task.handoff_events[-1].to_dispatcher == "human"
    assert result.task.handoff_events[-1].reason == "accepted"
    assert result.task.handoff_events[-1].output_ref == "entity-1"


# ─────────────────────────────────────────────────────────────
# P1 — Related-spec review
# ─────────────────────────────────────────────────────────────

@pytest.mark.spec("AC-TASK-UPG-09")
def test_ac_task_upg_09_related_spec_review_passed():
    """AC-TASK-UPG-09: SPEC-task-communication-sync / SPEC-task-view-clarity /
    SPEC-task-kanban-operations have been reviewed for conflict with the new
    dispatcher / handoff / subtask semantics. Any conflicting paragraph has
    been updated. This AC is a human-reviewed checkpoint — the test asserts
    the review note exists in each spec's changelog."""
    targets = [
        ROOT / "docs/specs/SPEC-task-communication-sync.md",
        ROOT / "docs/specs/SPEC-task-view-clarity.md",
        ROOT / "docs/specs/SPEC-task-kanban-operations.md",
    ]
    required_note = "2026-04-19: reviewed against SPEC-task-governance dispatcher / handoff / subtask semantics"
    for path in targets:
        text = path.read_text(encoding="utf-8")
        assert "updated: 2026-04-19" in text, f"{path.name} must update frontmatter date"
        assert required_note in text, f"{path.name} must carry related-spec review note"
