"""
AC test stubs generated from SPEC-docs-native-edit-and-helper-ingest.
Auto-generated by Architect — Developer fills implementation.

Backend ACs covered:
- AC-DNH-05: read_source returns zenos_native content from GCS
- AC-DNH-06: archived doc hidden from default list
- AC-DNH-08: first helper push creates source with external_id
- AC-DNH-09: second push same external_id updates existing source (upsert)
- AC-DNH-10: unchanged payload returns no-op
- AC-DNH-11: duplicate external_id across bundles returns warning (not reject)
- AC-DNH-12: read_source returns snapshot_summary when present
- AC-DNH-13: read_source returns unavailable + setup_hint when no snapshot
- AC-DNH-14: invalid external_id format rejected 400
- AC-DNH-14a: oversized snapshot_summary (>10KB) rejected 413 SNAPSHOT_TOO_LARGE
- AC-DNH-17: read_source stale returns staleness_hint
- AC-DNH-18 (backend): helper resync clears stale state in storage

Frontend ACs (DNH-01, 02-frontend-trigger, 03, 04, 07, 15, 16, 18-frontend, 19, 20, 21, 22)
live in dashboard/src/__tests__/docs_native_edit_and_helper_ingest_ac.test.tsx.
"""

from __future__ import annotations

from datetime import datetime, timedelta, timezone
from unittest.mock import AsyncMock, MagicMock

import pytest

from zenos.domain.knowledge import Entity, EntityType, Tags


# ---------------------------------------------------------------------------
# Shared helpers
# ---------------------------------------------------------------------------

def _now_utc() -> datetime:
    return datetime.now(timezone.utc)


def _make_entity(
    *,
    entity_id: str = "doc-test-1",
    name: str = "Test Doc",
    sources: list[dict] | None = None,
    status: str = "current",
    doc_role: str = "index",
    partner_id: str = "partner-test",
) -> Entity:
    if sources is None:
        sources = [{
            "source_id": "src-1",
            "uri": "/docs/doc-test-1",
            "type": "zenos_native",
            "status": "valid",
            "source_status": "valid",
            "is_primary": True,
        }]
    return Entity(
        id=entity_id,
        name=name,
        type=EntityType.DOCUMENT,
        summary="Test document",
        tags=Tags(what=["test"], why="testing", how="unit", who=["dev"]),
        status=status,
        sources=sources,
        doc_role=doc_role,
        visibility="public",
        created_at=_now_utc(),
        updated_at=_now_utc(),
    )


class _StubEntityRepo:
    """In-memory stub for EntityRepository."""

    def __init__(self, entities: list[Entity]) -> None:
        self._by_id = {e.id: e for e in entities if e.id}
        self._all = list(entities)

    async def get_by_id(self, entity_id: str) -> Entity | None:
        return self._by_id.get(entity_id)

    async def get_by_name(self, name: str) -> Entity | None:
        return next((e for e in self._all if e.name == name), None)

    async def list_all(self, type_filter: str | None = None) -> list[Entity]:
        if type_filter is None:
            return list(self._all)
        return [e for e in self._all if e.type == type_filter]

    async def upsert(self, entity: Entity) -> Entity:
        self._by_id[entity.id] = entity
        self._all = [e if e.id != entity.id else entity for e in self._all]
        if entity.id not in {e.id for e in self._all}:
            self._all.append(entity)
        return entity

    async def list_unconfirmed(self) -> list[Entity]:
        return []

    async def list_by_parent(self, parent_id: str) -> list[Entity]:
        return []

    async def list_by_ids(self, ids: list[str]) -> list[Entity]:
        return [self._by_id[i] for i in ids if i in self._by_id]

    async def update_source_status(self, entity_id: str, status: str, source_id: str | None = None) -> None:
        entity = self._by_id.get(entity_id)
        if entity:
            for src in (entity.sources or []):
                if source_id is None or src.get("source_id") == source_id:
                    src["status"] = status
                    src["source_status"] = status

    async def archive_entity(self, entity_id: str) -> None:
        entity = self._by_id.get(entity_id)
        if entity:
            entity.status = "archived"

    async def find_by_id_prefix(self, prefix: str, partner_id: str, limit: int = 11) -> list[Entity]:
        return []


class _StubAdapter:
    """Returns fixed content for any URI."""

    def __init__(self, content: str = "# Native Content\n\nHello from GCS.") -> None:
        self._content = content

    async def read_content(self, uri: str) -> str:
        return self._content

    async def search_alternatives_for_uri(self, uri: str) -> list[str]:
        return []


PARENT_ENTITY = Entity(
    id="parent-entity-1",
    name="Test L2 Module",
    type="module",
    summary="Parent module for tests",
    tags=Tags(what=["module"], why="test", how="test", who=["dev"]),
    status="active",
    level=2,
)


def _make_ontology_service(entities: list[Entity] | None = None):
    """Create a real OntologyService with in-memory stubs.

    Always seeds PARENT_ENTITY so that linked_entity_ids=["parent-entity-1"]
    passes validation without requiring full DB connectivity.
    """
    from zenos.application.knowledge.ontology_service import OntologyService

    all_entities = list(entities or [])
    # Ensure parent entity is always present for validation
    if not any(e.id == PARENT_ENTITY.id for e in all_entities):
        all_entities.append(PARENT_ENTITY)

    entity_repo = _StubEntityRepo(all_entities)
    doc_repo = AsyncMock()
    doc_repo.list_all = AsyncMock(return_value=[])
    doc_repo.get_by_id = AsyncMock(return_value=None)
    rel_repo = AsyncMock()
    rel_repo.list_by_entity = AsyncMock(return_value=[])
    rel_repo.add = AsyncMock()
    rel_repo.find_duplicate = AsyncMock(return_value=None)
    rel_repo.remove_by_id = AsyncMock(return_value=1)
    # Support delete_by_source_and_type (used in linkage sync)
    rel_repo.delete_by_source_and_type = AsyncMock(return_value=0)
    protocol_repo = AsyncMock()
    protocol_repo.get_by_entity = AsyncMock(return_value=None)
    blindspot_repo = AsyncMock()

    svc = OntologyService(
        entity_repo=entity_repo,
        document_repo=doc_repo,
        relationship_repo=rel_repo,
        protocol_repo=protocol_repo,
        blindspot_repo=blindspot_repo,
    )
    return svc, entity_repo


# Shorthand for linked_entity_ids arg in upsert_document calls
_LINKED = ["parent-entity-1"]


# ---------------------------------------------------------------------------
# P0-1: Dashboard 原生文件編輯器（backend slice）
# ---------------------------------------------------------------------------


@pytest.mark.spec("AC-DNH-05")
async def test_ac_dnh_05_read_source_returns_zenos_native_content_from_gcs():
    """AC-DNH-05: Given zenos_native source 的文件, When agent 呼叫 read_source(doc_id),
    Then 讀到最新 revision 的 markdown content."""
    from zenos.application.knowledge.source_service import SourceService

    native_content = "# Hello from ZenOS\n\nNative document content."
    entity = _make_entity(
        entity_id="doc-native-1",
        sources=[{
            "source_id": "src-native-1",
            "uri": "/docs/doc-native-1",
            "type": "zenos_native",
            "status": "valid",
            "source_status": "valid",
            "is_primary": True,
        }],
    )
    repo = _StubEntityRepo([entity])
    adapter = _StubAdapter(content=native_content)
    svc = SourceService(entity_repo=repo, source_adapter=adapter)

    # read_source should delegate to adapter for zenos_native URIs
    content = await svc.read_source("doc-native-1")

    assert content == native_content


@pytest.mark.spec("AC-DNH-06")
async def test_ac_dnh_06_archived_doc_hidden_from_default_list():
    """AC-DNH-06: Given 文件被標 archived, When 用戶在列表檢視,
    Then 預設不顯示；需切「已封存」才看得到（backend: list filter respects status=archived）."""
    svc, repo = _make_ontology_service()

    active_entity = _make_entity(entity_id="doc-active", name="Active Doc", status="current")
    archived_entity = _make_entity(entity_id="doc-archived", name="Archived Doc", status="archived")
    for e in (active_entity, archived_entity):
        repo._by_id[e.id] = e
        repo._all.append(e)

    # The search/list in ontology_service excludes archived docs by default
    results = await svc.search("Doc")

    result_ids = [r.entity.id if hasattr(r, "entity") else r.id for r in results]
    assert "doc-active" in result_ids
    assert "doc-archived" not in result_ids


# ---------------------------------------------------------------------------
# P0-2: Helper Ingest Contract（external_id + upsert）
# ---------------------------------------------------------------------------


@pytest.mark.spec("AC-DNH-08")
async def test_ac_dnh_08_first_helper_push_creates_source_with_external_id():
    """AC-DNH-08: Given helper 首次推入 Notion 頁 external_id='notion:abc',
    When write 執行, Then 建立新 source, server 設 last_synced_at."""
    doc_entity = _make_entity(
        entity_id="doc-001",
        sources=[{
            "source_id": "src-existing",
            "uri": "https://www.notion.so/some-page-abc123def456abc123def456abc123de",
            "type": "notion",
            "status": "valid",
            "source_status": "valid",
        }],
    )
    svc, repo = _make_ontology_service([doc_entity])

    before_call = _now_utc()

    result = await svc.upsert_document({
        "id": "doc-001",
        "linked_entity_ids": _LINKED,
        "add_source": {
            "type": "notion",
            "uri": "https://www.notion.so/new-page-abc123def456abc123def456abc123de",
            "label": "Notion Page",
            "external_id": "notion:abc",
            "external_updated_at": "2026-04-10T00:00:00+00:00",
            "snapshot_summary": "Summary of the page.",
        },
    })

    # Find the newly added source
    new_src = next(
        (s for s in result.sources if s.get("external_id") == "notion:abc"),
        None,
    )
    assert new_src is not None, "Source with external_id='notion:abc' should have been created"
    assert new_src.get("source_id"), "source_id should be set"

    # Verify last_synced_at was set by server
    last_synced = new_src.get("last_synced_at")
    assert last_synced is not None, "last_synced_at should be set by server"
    # Parse and check it's recent
    from zenos.application.knowledge.source_service import _parse_iso
    parsed = _parse_iso(last_synced)
    assert parsed >= before_call.replace(microsecond=0), "last_synced_at should be >= before the call"


@pytest.mark.spec("AC-DNH-09")
async def test_ac_dnh_09_second_push_same_external_id_updates_existing_source():
    """AC-DNH-09: Given helper 第二次推入同一 external_id='notion:abc'（同 doc_id）且 uri/content 有變,
    When write 執行, Then **更新既有 source**（保留 source_id），不建新 source."""
    original_source_id = "src-notion-original"
    doc_entity = _make_entity(
        entity_id="doc-002",
        sources=[{
            "source_id": original_source_id,
            "uri": "https://www.notion.so/original-page-abc123def456abc123def456abc123de",
            "type": "notion",
            "external_id": "notion:abc",
            "external_updated_at": "2026-04-01T00:00:00+00:00",
            "snapshot_summary": "Original summary.",
            "last_synced_at": "2026-04-01T00:00:00+00:00",
            "status": "valid",
            "source_status": "valid",
        }],
    )
    svc, repo = _make_ontology_service([doc_entity])

    result = await svc.upsert_document({
        "id": "doc-002",
        "linked_entity_ids": _LINKED,
        "add_source": {
            "type": "notion",
            "uri": "https://www.notion.so/updated-page-abc123def456abc123def456abc123de",
            "label": "Updated Notion Page",
            "external_id": "notion:abc",
            "external_updated_at": "2026-04-20T00:00:00+00:00",
            "snapshot_summary": "Updated summary with new content.",
        },
    })

    # Should still have only 1 source with external_id=notion:abc
    notion_sources = [s for s in result.sources if s.get("external_id") == "notion:abc"]
    assert len(notion_sources) == 1, "Should have exactly one source with external_id='notion:abc' (upsert, not duplicate)"

    updated_src = notion_sources[0]
    assert updated_src.get("source_id") == original_source_id, "source_id must be preserved on upsert"
    assert "Updated Notion Page" in updated_src.get("label", ""), "label should be updated"
    assert updated_src.get("snapshot_summary") == "Updated summary with new content."
    assert updated_src.get("external_updated_at") == "2026-04-20T00:00:00+00:00"


@pytest.mark.spec("AC-DNH-10")
async def test_ac_dnh_10_unchanged_payload_returns_noop():
    """AC-DNH-10: Given helper 第二次推入時 external_updated_at 不變且 snapshot_summary 不變,
    When write 執行, Then 仍接受但 response 註記 noop=true."""
    existing_external_updated = "2026-04-01T00:00:00+00:00"
    existing_snapshot = "Unchanged summary text."

    doc_entity = _make_entity(
        entity_id="doc-003",
        sources=[{
            "source_id": "src-noop-1",
            "uri": "https://www.notion.so/noop-page-abc123def456abc123def456abc123def",
            "type": "notion",
            "external_id": "notion:noop",
            "external_updated_at": existing_external_updated,
            "snapshot_summary": existing_snapshot,
            "last_synced_at": "2026-04-01T00:00:00+00:00",
            "status": "valid",
            "source_status": "valid",
        }],
    )
    svc, repo = _make_ontology_service([doc_entity])

    data: dict = {
        "id": "doc-003",
        "linked_entity_ids": _LINKED,
        "add_source": {
            "type": "notion",
            "uri": "https://www.notion.so/noop-page-abc123def456abc123def456abc123def",
            "external_id": "notion:noop",
            "external_updated_at": existing_external_updated,  # unchanged
            "snapshot_summary": existing_snapshot,              # unchanged
        },
    }
    result = await svc.upsert_document(data)

    # The _helper_upsert_meta should report noop=True
    helper_meta = getattr(result, "_helper_upsert_meta", {})
    assert helper_meta.get("noop") is True, (
        "When external_updated_at and snapshot_summary are unchanged, "
        "upsert should be marked as noop=True"
    )


@pytest.mark.spec("AC-DNH-11")
async def test_ac_dnh_11_duplicate_external_id_across_bundles_returns_warning():
    """AC-DNH-11: Given source A 帶 external_id='notion:abc' 已在 doc_id=X,
    When helper 把同 external_id 寫入 doc_id=Y,
    Then write 成功但 response 含 warning DUPLICATE_EXTERNAL_ID_ACROSS_BUNDLES."""
    # doc X already has the external_id
    doc_x = _make_entity(
        entity_id="doc-x",
        name="Doc X",
        sources=[{
            "source_id": "src-x-1",
            "uri": "https://www.notion.so/notion-page-abc123def456abc123def456abc123de",
            "type": "notion",
            "external_id": "notion:cross-doc",
            "status": "valid",
            "source_status": "valid",
        }],
    )
    # doc Y will receive the same external_id
    doc_y = _make_entity(
        entity_id="doc-y",
        name="Doc Y",
        sources=[{
            "source_id": "src-y-existing",
            "uri": "/docs/doc-y",
            "type": "zenos_native",
            "status": "valid",
            "source_status": "valid",
        }],
    )
    svc, repo = _make_ontology_service([doc_x, doc_y])

    result = await svc.upsert_document({
        "id": "doc-y",
        "linked_entity_ids": _LINKED,
        "add_source": {
            "type": "notion",
            "uri": "https://www.notion.so/another-page-abc123def456abc123def456abc12345",
            "external_id": "notion:cross-doc",
            "snapshot_summary": "Cross-doc summary.",
        },
    })

    # Should succeed (not raise) — write returns the entity
    assert result is not None

    # The _helper_warnings should contain the DUPLICATE_EXTERNAL_ID_ACROSS_BUNDLES message
    helper_warnings = getattr(result, "_helper_warnings", [])
    assert any(
        "DUPLICATE_EXTERNAL_ID_ACROSS_BUNDLES" in w for w in helper_warnings
    ), f"Expected DUPLICATE_EXTERNAL_ID_ACROSS_BUNDLES warning, got: {helper_warnings}"


@pytest.mark.spec("AC-DNH-12")
async def test_ac_dnh_12_read_source_returns_snapshot_summary_when_present():
    """AC-DNH-12: Given source 有 snapshot_summary,
    When agent 呼叫 read_source(doc_id, source_id),
    Then 回傳 snapshot_summary（原始真相仍為 source.uri 指向的外部文件）."""
    from zenos.interface.mcp.source import read_source
    from zenos.interface.mcp._auth import _current_partner

    summary_text = "This is a semantic summary of the Notion page."
    entity = _make_entity(
        entity_id="doc-snap-1",
        sources=[{
            "source_id": "src-snap-1",
            "uri": "https://www.notion.so/snap-page-abc123def456abc123def456abc123def",
            "type": "notion",
            "external_id": "notion:snap",
            "snapshot_summary": summary_text,
            "last_synced_at": _now_utc().isoformat(),
            "status": "valid",
            "source_status": "valid",
        }],
    )

    mock_ontology_svc = MagicMock()
    mock_ontology_svc.get_document = AsyncMock(return_value=entity)

    mock_source_svc = MagicMock()

    import zenos.interface.mcp as _mcp
    with (
        MagicMock() as _,
    ):
        original_ontology = getattr(_mcp, "ontology_service", None)
        original_source = getattr(_mcp, "source_service", None)
        original_ensure = getattr(_mcp, "_ensure_services", None)
        _mcp.ontology_service = mock_ontology_svc
        _mcp.source_service = mock_source_svc
        _mcp._ensure_services = AsyncMock()
        _current_partner.set({"id": "p1", "isAdmin": False, "sharedPartnerId": None})
        try:
            resp = await read_source("doc-snap-1", source_id="src-snap-1")
        finally:
            _mcp.ontology_service = original_ontology
            _mcp.source_service = original_source
            _mcp._ensure_services = original_ensure

    assert resp.get("status") == "ok"
    data = resp.get("data", {})
    assert data.get("content") == summary_text
    assert data.get("content_type") == "snapshot_summary"
    assert data.get("source_id") == "src-snap-1"


@pytest.mark.spec("AC-DNH-13")
async def test_ac_dnh_13_read_source_returns_unavailable_with_setup_hint():
    """AC-DNH-13: Given source 無 snapshot_summary,
    When agent 呼叫 read_source,
    Then 回傳 unavailable 結構 + setup_hint 提示用戶用 Notion MCP 同步或 Dashboard 重新同步."""
    from zenos.interface.mcp.source import read_source
    from zenos.interface.mcp._auth import _current_partner

    entity = _make_entity(
        entity_id="doc-no-snap-1",
        sources=[{
            "source_id": "src-no-snap-1",
            "uri": "https://www.notion.so/no-snap-page-abc123def456abc123def456abc123",
            "type": "notion",
            "external_id": "notion:nosnap",
            # No snapshot_summary
            "status": "valid",
            "source_status": "valid",
        }],
    )

    mock_ontology_svc = MagicMock()
    mock_ontology_svc.get_document = AsyncMock(return_value=entity)
    mock_source_svc = MagicMock()

    import zenos.interface.mcp as _mcp
    original_ontology = getattr(_mcp, "ontology_service", None)
    original_source = getattr(_mcp, "source_service", None)
    original_ensure = getattr(_mcp, "_ensure_services", None)
    _mcp.ontology_service = mock_ontology_svc
    _mcp.source_service = mock_source_svc
    _mcp._ensure_services = AsyncMock()
    _current_partner.set({"id": "p1", "isAdmin": False, "sharedPartnerId": None})
    try:
        resp = await read_source("doc-no-snap-1", source_id="src-no-snap-1")
    finally:
        _mcp.ontology_service = original_ontology
        _mcp.source_service = original_source
        _mcp._ensure_services = original_ensure

    # Should return an error (unavailable)
    assert resp.get("status") in ("error", "rejected")
    data = resp.get("data", {})
    error_code = data.get("error", {}).get("code", "") if isinstance(data.get("error"), dict) else data.get("error", "")
    # Also check top-level error structure
    assert "SNAPSHOT_UNAVAILABLE" in str(resp) or "SNAPSHOT_UNAVAILABLE" in str(data)
    # setup_hint should be present
    assert "Notion MCP" in str(resp) or "Dashboard" in str(resp) or "setup_hint" in str(data)


@pytest.mark.spec("AC-DNH-14")
async def test_ac_dnh_14_invalid_external_id_format_rejected_400():
    """AC-DNH-14: Given 傳入 external_id 但格式不合法（例：空字串、未含 ':' 分隔）,
    When write 執行, Then 回傳 400."""
    from zenos.application.knowledge.ontology_service import OntologyService

    doc_entity = _make_entity(
        entity_id="doc-fmt-1",
        sources=[{
            "source_id": "src-fmt-1",
            "uri": "/docs/doc-fmt-1",
            "type": "zenos_native",
            "status": "valid",
            "source_status": "valid",
        }],
    )
    svc, repo = _make_ontology_service([doc_entity])

    # Empty string external_id
    with pytest.raises(ValueError, match="external_id"):
        await svc.upsert_document({
            "id": "doc-fmt-1",
            "linked_entity_ids": _LINKED,
            "add_source": {
                "type": "notion",
                "uri": "https://www.notion.so/some-page-abc123def456abc123def456abc123de",
                "external_id": "",  # empty — invalid
            },
        })

    # No colon separator
    with pytest.raises(ValueError, match="external_id"):
        await svc.upsert_document({
            "id": "doc-fmt-1",
            "linked_entity_ids": _LINKED,
            "add_source": {
                "type": "notion",
                "uri": "https://www.notion.so/some-page-abc123def456abc123def456abc123de",
                "external_id": "notionpage123",  # no colon — invalid
            },
        })

    # Invalid prefix (uppercase)
    with pytest.raises(ValueError, match="external_id"):
        await svc.upsert_document({
            "id": "doc-fmt-1",
            "linked_entity_ids": _LINKED,
            "add_source": {
                "type": "notion",
                "uri": "https://www.notion.so/some-page-abc123def456abc123def456abc123de",
                "external_id": "Notion:abc",  # uppercase prefix — invalid
            },
        })


@pytest.mark.spec("AC-DNH-14a")
async def test_ac_dnh_14a_oversized_snapshot_summary_rejected_413():
    """AC-DNH-14a: Given 傳入的 snapshot_summary 超過 10KB（10240 bytes）,
    When write 執行, Then 回傳 413 with code SNAPSHOT_TOO_LARGE，且 message 提示
    'snapshot_summary 是摘要不是 mirror，請先在 helper 端 distill'."""
    from zenos.application.knowledge.ontology_service import SnapshotTooLargeError

    doc_entity = _make_entity(
        entity_id="doc-size-1",
        sources=[{
            "source_id": "src-size-1",
            "uri": "/docs/doc-size-1",
            "type": "zenos_native",
            "status": "valid",
            "source_status": "valid",
        }],
    )
    svc, repo = _make_ontology_service([doc_entity])

    # 10241 bytes exceeds the 10240-byte limit
    oversized_summary = "x" * 10_241

    with pytest.raises(SnapshotTooLargeError) as exc_info:
        await svc.upsert_document({
            "id": "doc-size-1",
            "linked_entity_ids": _LINKED,
            "add_source": {
                "type": "notion",
                "uri": "https://www.notion.so/snap-page-abc123def456abc123def456abc1234",
                "external_id": "notion:toobig",
                "snapshot_summary": oversized_summary,
            },
        })

    # Error message must mention "distill"
    error_msg = str(exc_info.value)
    assert "distill" in error_msg, f"Error message should mention 'distill', got: {error_msg}"
    assert "摘要不是 mirror" in error_msg or "snapshot_summary" in error_msg


# ---------------------------------------------------------------------------
# P0-3: 手動 / Agent 觸發 Re-sync UX（backend slice）
# ---------------------------------------------------------------------------


@pytest.mark.spec("AC-DNH-17")
async def test_ac_dnh_17_read_source_stale_returns_staleness_hint():
    """AC-DNH-17: Given agent 呼叫 read_source 讀到 stale source,
    When 回傳, Then response 含 staleness_hint（含 last_synced_at、建議動作）."""
    from zenos.interface.mcp.source import read_source
    from zenos.interface.mcp._auth import _current_partner

    # source with last_synced_at older than 14 days
    stale_date = (_now_utc() - timedelta(days=20)).isoformat()
    snapshot_text = "Stale snapshot summary."

    entity = _make_entity(
        entity_id="doc-stale-1",
        sources=[{
            "source_id": "src-stale-1",
            "uri": "https://www.notion.so/stale-page-abc123def456abc123def456abc123def",
            "type": "notion",
            "external_id": "notion:stale",
            "snapshot_summary": snapshot_text,
            "last_synced_at": stale_date,
            "status": "valid",
            "source_status": "valid",
        }],
    )

    mock_ontology_svc = MagicMock()
    mock_ontology_svc.get_document = AsyncMock(return_value=entity)
    mock_source_svc = MagicMock()

    import zenos.interface.mcp as _mcp
    original_ontology = getattr(_mcp, "ontology_service", None)
    original_source = getattr(_mcp, "source_service", None)
    original_ensure = getattr(_mcp, "_ensure_services", None)
    _mcp.ontology_service = mock_ontology_svc
    _mcp.source_service = mock_source_svc
    _mcp._ensure_services = AsyncMock()
    _current_partner.set({"id": "p1", "isAdmin": False, "sharedPartnerId": None})
    try:
        resp = await read_source("doc-stale-1", source_id="src-stale-1")
    finally:
        _mcp.ontology_service = original_ontology
        _mcp.source_service = original_source
        _mcp._ensure_services = original_ensure

    assert resp.get("status") == "ok"
    data = resp.get("data", {})
    assert "staleness_hint" in data, (
        f"Expected staleness_hint in response data, got: {list(data.keys())}"
    )
    hint = data["staleness_hint"]
    assert hint.get("reason") == "outdated"
    assert "last_synced_at" in hint
    assert hint.get("suggested_helper_prompt")


@pytest.mark.spec("AC-DNH-18-backend")
async def test_ac_dnh_18_helper_resync_clears_stale_in_storage():
    """AC-DNH-18 (backend slice): Given helper 完成 re-sync（走 update_source with external_id）,
    When write 返回, Then last_synced_at 已更新到 now（前端 stale 標記消失由 frontend AC 驗證）."""
    old_synced = (_now_utc() - timedelta(days=20)).isoformat()

    doc_entity = _make_entity(
        entity_id="doc-resync-1",
        sources=[{
            "source_id": "src-resync-1",
            "uri": "https://www.notion.so/resync-page-abc123def456abc123def456abc1234",
            "type": "notion",
            "external_id": "notion:resync",
            "snapshot_summary": "Old summary.",
            "last_synced_at": old_synced,
            "status": "valid",
            "source_status": "valid",
        }],
    )
    svc, repo = _make_ontology_service([doc_entity])

    before_resync = _now_utc()

    # Re-sync via add_source with same external_id (upsert path)
    result = await svc.upsert_document({
        "id": "doc-resync-1",
        "linked_entity_ids": _LINKED,
        "add_source": {
            "type": "notion",
            "uri": "https://www.notion.so/resync-page-abc123def456abc123def456abc1234",
            "external_id": "notion:resync",
            "external_updated_at": _now_utc().isoformat(),
            "snapshot_summary": "Updated summary after resync.",
        },
    })

    updated_src = next(
        (s for s in result.sources if s.get("external_id") == "notion:resync"),
        None,
    )
    assert updated_src is not None, "Source with external_id='notion:resync' should exist"

    last_synced_raw = updated_src.get("last_synced_at")
    assert last_synced_raw is not None, "last_synced_at must be set after resync"

    from zenos.application.knowledge.source_service import _parse_iso
    new_last_synced = _parse_iso(last_synced_raw)
    assert new_last_synced >= before_resync.replace(microsecond=0), (
        f"last_synced_at ({new_last_synced}) should be updated to now, "
        f"was previously stale ({old_synced})"
    )
