"""
AC test stubs generated from SPEC-semantic-retrieval (ADR-041 Phase 1).
Auto-generated by Architect — Developer fills implementation.
Red = gap, Green = verified.

Run: .venv/bin/pytest tests/spec_compliance/test_semantic_retrieval_ac.py -x

Integration note (AC-01..05):
  These tests require a real PostgreSQL instance with the migration applied.
  They are marked @pytest.mark.integration and will be skipped unless the
  DATABASE_URL environment variable is set and points to a test database
  with the migration already run.
"""
from __future__ import annotations

import hashlib
import os
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any
from unittest.mock import AsyncMock, MagicMock, patch

import pytest

from zenos.application.knowledge.embedding_service import (
    EMPTY_HASH,
    FAILED_HASH,
    GEMINI_EMBED_MODEL,
    EmbeddingService,
)
from zenos.domain.knowledge.models import Entity, Tags
from zenos.infrastructure.llm_client import EmbeddingAPIError


# ---------------------------------------------------------------------------
# Shared test fixtures / helpers
# ---------------------------------------------------------------------------

def _make_entity(
    *,
    summary: str = "This is a summary",
    embedded_summary_hash: str | None = None,
    embedding_model: str | None = None,
    embedded_at: datetime | None = None,
) -> Entity:
    return Entity(
        id="entity-001",
        name="Test Entity",
        type="module",
        summary=summary,
        tags=Tags(what=["test"], why="testing", how="unit test", who=["dev"]),
        embedded_summary_hash=embedded_summary_hash,
        embedding_model=embedding_model,
        embedded_at=embedded_at,
    )


def _fake_vec(dim: int = 768) -> list[float]:
    return [0.1] * dim


def _sha256(text: str) -> str:
    return hashlib.sha256(text.encode()).hexdigest()


# ============================================================
# Helpers for R1 integration tests
# ============================================================

def _get_db_url() -> str | None:
    return os.environ.get("DATABASE_URL")


def _integration_skip_reason() -> str:
    return (
        "Integration test: requires DATABASE_URL env var pointing to a "
        "PostgreSQL instance with migration 20260418_0001_pgvector_entity_embedding applied."
    )


# ============================================================
# R1: Migration & Schema (AC-SEMRET-01..05)
# ============================================================

@pytest.mark.spec("AC-SEMRET-01")
@pytest.mark.integration
@pytest.mark.asyncio
async def test_ac_semret_01_migration_adds_columns():
    """AC-SEMRET-01: migration adds summary_embedding vector(768) / embedding_model / embedded_at / embedded_summary_hash to zenos.entities."""
    db_url = _get_db_url()
    if not db_url:
        pytest.skip(_integration_skip_reason())

    import asyncpg  # type: ignore[import-untyped]

    conn = await asyncpg.connect(db_url)
    try:
        rows = await conn.fetch(
            """
            SELECT column_name, data_type, udt_name
            FROM information_schema.columns
            WHERE table_schema = 'zenos'
              AND table_name   = 'entities'
              AND column_name  IN (
                  'summary_embedding',
                  'embedding_model',
                  'embedded_at',
                  'embedded_summary_hash'
              )
            ORDER BY column_name
            """
        )
        found = {r["column_name"] for r in rows}
        assert "summary_embedding" in found, "summary_embedding column missing"
        assert "embedding_model" in found, "embedding_model column missing"
        assert "embedded_at" in found, "embedded_at column missing"
        assert "embedded_summary_hash" in found, "embedded_summary_hash column missing"

        # Verify summary_embedding is a vector type (udt_name = 'vector')
        embedding_col = next(r for r in rows if r["column_name"] == "summary_embedding")
        assert embedding_col["udt_name"] == "vector", (
            f"summary_embedding should be type vector, got udt_name={embedding_col['udt_name']!r}"
        )
    finally:
        await conn.close()


@pytest.mark.spec("AC-SEMRET-02")
@pytest.mark.integration
@pytest.mark.asyncio
async def test_ac_semret_02_pgvector_enabled():
    """AC-SEMRET-02: pgvector extension enabled."""
    db_url = _get_db_url()
    if not db_url:
        pytest.skip(_integration_skip_reason())

    import asyncpg  # type: ignore[import-untyped]

    conn = await asyncpg.connect(db_url)
    try:
        row = await conn.fetchrow(
            "SELECT extname FROM pg_extension WHERE extname = 'vector'"
        )
        assert row is not None, "pgvector extension 'vector' is not installed"
        assert row["extname"] == "vector"
    finally:
        await conn.close()


@pytest.mark.spec("AC-SEMRET-03")
@pytest.mark.integration
@pytest.mark.asyncio
async def test_ac_semret_03_hnsw_index_exists():
    """AC-SEMRET-03: HNSW index on summary_embedding with vector_cosine_ops exists."""
    db_url = _get_db_url()
    if not db_url:
        pytest.skip(_integration_skip_reason())

    import asyncpg  # type: ignore[import-untyped]

    conn = await asyncpg.connect(db_url)
    try:
        row = await conn.fetchrow(
            """
            SELECT indexname, indexdef
            FROM pg_indexes
            WHERE schemaname = 'zenos'
              AND tablename  = 'entities'
              AND indexname  = 'idx_entities_summary_embedding_hnsw'
            """
        )
        assert row is not None, "HNSW index idx_entities_summary_embedding_hnsw not found"
        index_def: str = row["indexdef"].lower()
        assert "hnsw" in index_def, f"Expected HNSW in index definition, got: {row['indexdef']!r}"
        assert "vector_cosine_ops" in index_def, (
            f"Expected vector_cosine_ops in index definition, got: {row['indexdef']!r}"
        )
    finally:
        await conn.close()


@pytest.mark.spec("AC-SEMRET-04")
@pytest.mark.integration
@pytest.mark.asyncio
async def test_ac_semret_04_existing_rows_null():
    """AC-SEMRET-04: existing entity rows have all 4 new columns = null after migration."""
    db_url = _get_db_url()
    if not db_url:
        pytest.skip(_integration_skip_reason())

    import asyncpg  # type: ignore[import-untyped]

    conn = await asyncpg.connect(db_url)
    try:
        # Check that every row that existed before the migration (i.e., was not
        # inserted by a post-migration embed pipeline) has null embedding columns.
        # We verify this by checking: any row with embedded_at IS NOT NULL must
        # also have a non-null summary_embedding (consistency invariant).
        # More directly: rows where embedding was never set must have all 4 cols null.
        rows = await conn.fetch(
            """
            SELECT id, summary_embedding, embedding_model, embedded_at, embedded_summary_hash
            FROM zenos.entities
            WHERE embedded_at IS NULL
            LIMIT 10
            """
        )
        # All rows with no embedded_at must have all four embedding cols null.
        for row in rows:
            assert row["summary_embedding"] is None, (
                f"Row {row['id']}: summary_embedding should be null when embedded_at is null"
            )
            assert row["embedding_model"] is None, (
                f"Row {row['id']}: embedding_model should be null when embedded_at is null"
            )
            assert row["embedded_summary_hash"] is None, (
                f"Row {row['id']}: embedded_summary_hash should be null when embedded_at is null"
            )

        # Additionally verify the columns exist and accept NULL via information_schema
        col_rows = await conn.fetch(
            """
            SELECT column_name, is_nullable
            FROM information_schema.columns
            WHERE table_schema = 'zenos'
              AND table_name   = 'entities'
              AND column_name  IN (
                  'summary_embedding', 'embedding_model',
                  'embedded_at', 'embedded_summary_hash'
              )
            """
        )
        for col_row in col_rows:
            assert col_row["is_nullable"] == "YES", (
                f"Column {col_row['column_name']} must be nullable (existing rows stay null after migration)"
            )
    finally:
        await conn.close()


@pytest.mark.spec("AC-SEMRET-05")
@pytest.mark.integration
@pytest.mark.asyncio
async def test_ac_semret_05_documents_untouched():
    """AC-SEMRET-05: zenos.documents schema has no embedding columns (P0 not included)."""
    db_url = _get_db_url()
    if not db_url:
        pytest.skip(_integration_skip_reason())

    import asyncpg  # type: ignore[import-untyped]

    conn = await asyncpg.connect(db_url)
    try:
        rows = await conn.fetch(
            """
            SELECT column_name
            FROM information_schema.columns
            WHERE table_schema = 'zenos'
              AND table_name   = 'documents'
              AND column_name  IN (
                  'summary_embedding',
                  'embedding_model',
                  'embedded_at',
                  'embedded_summary_hash'
              )
            """
        )
        forbidden = [r["column_name"] for r in rows]
        assert forbidden == [], (
            f"zenos.documents must NOT have embedding columns (ADR-042 scope), "
            f"but found: {forbidden}"
        )
    finally:
        await conn.close()


# ============================================================
# R2: Embedding Pipeline (AC-SEMRET-06..12)
# ============================================================

@pytest.mark.spec("AC-SEMRET-06")
@pytest.mark.asyncio
async def test_ac_semret_06_compute_and_store():
    """AC-SEMRET-06: compute_and_store triggers Gemini embed, writes summary_embedding (768 dim), embedding_model, embedded_at, embedded_summary_hash=sha256(summary)."""
    summary = "This is a summary"
    vec = _fake_vec(768)
    entity = _make_entity(summary=summary)

    repo = MagicMock()
    repo.get_by_id = AsyncMock(return_value=entity)
    repo.update_embedding = AsyncMock()

    llm = MagicMock()
    llm.embed = AsyncMock(return_value=[vec])

    service = EmbeddingService(repo, llm)
    result = await service.compute_and_store("entity-001")

    assert result is True

    # Verify embed was called with the summary text
    llm.embed.assert_called_once_with([summary])

    # Verify update_embedding was called with the correct arguments
    repo.update_embedding.assert_called_once()
    call_args = repo.update_embedding.call_args
    entity_id_arg, vec_arg, model_arg, hash_arg = call_args.args

    assert entity_id_arg == "entity-001"
    assert len(vec_arg) == 768
    assert model_arg == GEMINI_EMBED_MODEL
    assert hash_arg == _sha256(summary)


@pytest.mark.spec("AC-SEMRET-07")
@pytest.mark.asyncio
async def test_ac_semret_07_needs_reembed_on_summary_change():
    """AC-SEMRET-07: after summary changes, needs_reembed returns True (hash mismatch)."""
    original_summary = "Original summary text"
    original_hash = _sha256(original_summary)

    # Entity was embedded with original summary, now has a different summary
    entity = _make_entity(
        summary="Updated summary text",
        embedded_summary_hash=original_hash,
        embedding_model=GEMINI_EMBED_MODEL,
        embedded_at=datetime.utcnow(),
    )

    service = EmbeddingService(MagicMock(), MagicMock())
    assert service.needs_reembed(entity) is True


@pytest.mark.spec("AC-SEMRET-08")
@pytest.mark.asyncio
async def test_ac_semret_08_no_reembed_on_other_fields():
    """AC-SEMRET-08: changing tags/owner does NOT trigger needs_reembed=True."""
    summary = "Stable summary text"
    correct_hash = _sha256(summary)

    entity = _make_entity(
        summary=summary,
        embedded_summary_hash=correct_hash,
        embedding_model=GEMINI_EMBED_MODEL,
        embedded_at=datetime.utcnow(),
    )
    # Simulate tags / owner change — only non-summary fields changed
    entity.owner = "NewOwner"
    entity.tags = Tags(what=["changed"], why="changed", how="changed", who=["changed"])

    service = EmbeddingService(MagicMock(), MagicMock())
    assert service.needs_reembed(entity) is False


@pytest.mark.spec("AC-SEMRET-09")
@pytest.mark.asyncio
async def test_ac_semret_09_async_embed_on_write():
    """AC-SEMRET-09: write/confirm triggers async embed; caller latency p95 < +50ms; background job runs compute_and_store.

    Test strategy (mock):
    - Verify _schedule_embed is called after a successful entity upsert (write path).
    - Verify _schedule_embed is called after a successful entity confirm (confirm path).
    - Verify caller returns immediately without awaiting compute_and_store (async proxy: mock
      compute_and_store delays 200ms; write/confirm must return well under that threshold).
    - Verify compute_and_store is eventually called by the scheduled background task.

    Note: This test uses mock for ontology_service / embedding_service.
    It validates the call-path and non-blocking semantics.
    ⚠️ mock test only — actual end-to-end latency measured by Architect (AC-SEMRET-36).
    """
    import asyncio
    import time
    from unittest.mock import AsyncMock, MagicMock, patch

    import zenos.interface.mcp as _mcp_module

    # ---------------------------------------------------------------
    # Part 1: write path — _schedule_embed called after upsert_entity
    # ---------------------------------------------------------------

    # Build a minimal upsert result that write.py will accept.
    fake_entity_id = "entity-test-001"
    fake_result = MagicMock()
    fake_result.warnings = []
    fake_result.similar_items = []
    # _serialize(result) must return {"entity": {"id": ...}} for entity write.
    # write.py calls _serialize which delegates to result.entity.
    # Easiest way: return a real-looking dict via patching _serialize.
    fake_serialized = {"entity": {"id": fake_entity_id}}

    # Track _schedule_embed calls.
    schedule_embed_calls: list[str] = []

    orig_schedule_embed = _mcp_module._schedule_embed

    def _spy_schedule_embed(eid: str) -> None:
        schedule_embed_calls.append(eid)
        # Do NOT actually schedule a task — just record the call.

    # Patch: ontology_service.upsert_entity, _serialize, _schedule_embed,
    # _build_context_bundle, _build_governance_hints, _audit_log, _current_partner,
    # _ensure_services, and write-path visibility checks.
    with (
        patch.object(_mcp_module, "ontology_service", MagicMock()) as mock_ont_svc,
        patch("zenos.interface.mcp.write._serialize", return_value=fake_serialized),
        patch("zenos.interface.mcp.write._build_context_bundle", new=AsyncMock(return_value={})),
        patch("zenos.interface.mcp.write._build_governance_hints", return_value={}),
        patch("zenos.interface.mcp.write._audit_log"),
        patch("zenos.interface.mcp.write._current_partner") as mock_partner_ctx,
        patch("zenos.interface.mcp.write._guest_write_rejection", return_value=None),
        patch("zenos.interface.mcp._ensure_services", new=AsyncMock()),
        patch.object(_mcp_module, "_schedule_embed", side_effect=_spy_schedule_embed),
        patch.object(_mcp_module, "entity_repo", MagicMock()),
    ):
        mock_partner_ctx.get.return_value = {"id": "partner-001"}
        mock_ont_svc.upsert_entity = AsyncMock(return_value=fake_result)
        # entity_repo.get_by_id — no existing entity (new write, no visibility check triggered).
        _mcp_module.entity_repo.get_by_id = AsyncMock(return_value=None)
        _mcp_module.entity_repo.get_by_name = AsyncMock(return_value=None)

        from zenos.interface.mcp.write import write as _write_tool

        t0 = time.monotonic()
        resp = await _write_tool(collection="entities", data={"name": "X", "type": "module", "summary": "s"})
        elapsed_ms = (time.monotonic() - t0) * 1000

    # _schedule_embed must be called with the entity id.
    assert fake_entity_id in schedule_embed_calls, (
        f"_schedule_embed not called for entity_id={fake_entity_id!r}; calls={schedule_embed_calls}"
    )
    # Caller must return quickly — well under 50ms (mock path, no real I/O).
    assert elapsed_ms < 50, f"write returned in {elapsed_ms:.1f}ms — expected < 50ms (mock path)"

    # ---------------------------------------------------------------
    # Part 2: confirm path — _schedule_embed called after ontology confirm
    # ---------------------------------------------------------------
    confirm_embed_calls: list[str] = []

    def _spy_confirm_embed(eid: str) -> None:
        confirm_embed_calls.append(eid)

    confirm_entity_id = "entity-confirm-001"

    with (
        patch.object(_mcp_module, "ontology_service", MagicMock()) as mock_ont_svc2,
        patch("zenos.interface.mcp.confirm._build_context_bundle", new=AsyncMock(return_value={})),
        patch("zenos.interface.mcp.confirm._build_governance_hints", return_value={}),
        patch("zenos.interface.mcp.confirm._audit_log"),
        patch("zenos.interface.mcp.confirm._current_partner") as mock_partner_ctx2,
        patch("zenos.interface.mcp._ensure_services", new=AsyncMock()),
        patch.object(_mcp_module, "_schedule_embed", side_effect=_spy_confirm_embed),
    ):
        mock_partner_ctx2.get.return_value = {"id": "partner-001"}
        mock_ont_svc2.confirm = AsyncMock(return_value={"id": confirm_entity_id, "status": "confirmed"})

        from zenos.interface.mcp.confirm import confirm as _confirm_tool

        resp2 = await _confirm_tool(collection="entities", id=confirm_entity_id)

    assert confirm_entity_id in confirm_embed_calls, (
        f"_schedule_embed not called for entity_id={confirm_entity_id!r}; calls={confirm_embed_calls}"
    )

    # ---------------------------------------------------------------
    # Part 3: non-blocking proof — compute_and_store with 200ms delay
    # must NOT block write caller.
    # ---------------------------------------------------------------
    EMBED_DELAY_S = 0.2  # 200ms simulated embed latency

    compute_calls: list[str] = []

    async def _slow_compute(eid: str) -> bool:
        await asyncio.sleep(EMBED_DELAY_S)
        compute_calls.append(eid)
        return True

    slow_embed_svc = MagicMock(spec=["compute_and_store"])
    slow_embed_svc.compute_and_store = _slow_compute

    orig_embedding_service = _mcp_module.embedding_service
    _mcp_module.embedding_service = slow_embed_svc

    try:
        # Call _schedule_embed directly (simulates what write.py does after upsert).
        t1 = time.monotonic()
        _mcp_module._schedule_embed("entity-nonblocking-001")
        dispatch_ms = (time.monotonic() - t1) * 1000

        # _schedule_embed must return immediately (before compute completes).
        assert dispatch_ms < 50, (
            f"_schedule_embed blocked for {dispatch_ms:.1f}ms — must return immediately"
        )

        # Give the background task time to complete.
        await asyncio.sleep(EMBED_DELAY_S + 0.05)

        assert "entity-nonblocking-001" in compute_calls, (
            "compute_and_store was never called in background task"
        )
    finally:
        _mcp_module.embedding_service = orig_embedding_service


@pytest.mark.spec("AC-SEMRET-10")
@pytest.mark.asyncio
async def test_ac_semret_10_failed_marker():
    """AC-SEMRET-10: after 3 Gemini failures, entity.embedded_summary_hash='FAILED', embedded_at=null, summary_embedding=null, WARNING logged; write flow NOT interrupted."""
    entity = _make_entity(summary="Some valid summary")

    repo = MagicMock()
    repo.get_by_id = AsyncMock(return_value=entity)
    repo.update_embedding = AsyncMock()

    llm = MagicMock()
    # All 3 attempts raise EmbeddingAPIError
    llm.embed = AsyncMock(side_effect=EmbeddingAPIError("quota exceeded"))

    service = EmbeddingService(repo, llm, max_retries=3)

    import logging
    with patch.object(logging.getLogger("zenos.application.knowledge.embedding_service"), "warning") as mock_warn:
        result = await service.compute_and_store("entity-001")

    # Must return False (not raise)
    assert result is False

    # update_embedding must be called with FAILED sentinel and None vector
    repo.update_embedding.assert_called_once()
    call_args = repo.update_embedding.call_args.args
    entity_id_arg, vec_arg, model_arg, hash_arg = call_args
    assert entity_id_arg == "entity-001"
    assert vec_arg is None
    assert hash_arg == FAILED_HASH

    # Must have logged at WARNING level (at least once)
    assert mock_warn.called

    # embed must have been called max_retries times
    assert llm.embed.call_count == 3


@pytest.mark.spec("AC-SEMRET-11")
@pytest.mark.asyncio
async def test_ac_semret_11_api_unavailable_null():
    """AC-SEMRET-11: Gemini API unavailable during write/confirm → entity still written with embedding=null + WARNING log."""
    # This tests embed_query's graceful degradation when the API is unavailable.
    # For the write/confirm path (S03), the async task uses compute_and_store which
    # writes FAILED marker; the entity write itself is unaffected.
    # Here we verify embed_query returns None and logs WARNING when API raises.
    llm = MagicMock()
    llm.embed = AsyncMock(side_effect=EmbeddingAPIError("connection refused"))

    service = EmbeddingService(MagicMock(), llm)

    import logging
    with patch.object(logging.getLogger("zenos.application.knowledge.embedding_service"), "warning") as mock_warn:
        result = await service.embed_query("some query text")

    assert result is None
    assert mock_warn.called


@pytest.mark.spec("AC-SEMRET-12")
@pytest.mark.asyncio
async def test_ac_semret_12_embed_query():
    """AC-SEMRET-12: embed_query(text) returns 768-dim vector, does not write DB."""
    vec = _fake_vec(768)

    repo = MagicMock()
    repo.update_embedding = AsyncMock()

    llm = MagicMock()
    llm.embed = AsyncMock(return_value=[vec])

    service = EmbeddingService(repo, llm)
    result = await service.embed_query("query about governance")

    assert result is not None
    assert len(result) == 768

    # Must NOT write to DB
    repo.update_embedding.assert_not_called()


# ============================================================
# R3: Neighbor Ranking (AC-SEMRET-13..18)
# ============================================================

# ---------------------------------------------------------------------------
# Helpers for R3 tests
# ---------------------------------------------------------------------------

def _make_relationship(source_id: str, target_id: str, rel_type: str = "impacts") -> Any:
    """Build a minimal Relationship domain object."""
    from zenos.domain.knowledge.models import Relationship
    return Relationship(
        source_entity_id=source_id,
        target_id=target_id,
        type=rel_type,
        description="test",
    )


def _make_graph_entity(eid: str, name: str, summary: str = "summary") -> Any:
    """Build a minimal Entity with an id and name for graph traversal."""
    from zenos.domain.knowledge.models import Entity, Tags
    return Entity(
        id=eid,
        name=name,
        type="module",
        summary=summary,
        tags=Tags(what=[], why="", how="", who=[]),
    )


def _build_ontology_service(
    entities: dict,         # id -> Entity
    relationships: list,    # list[Relationship]
    embedding_service: Any | None = None,
    embeddings: dict | None = None,  # id -> list[float] | None
) -> Any:
    """Construct an OntologyService with in-memory repo mocks."""
    from zenos.application.knowledge.ontology_service import OntologyService

    entity_repo = MagicMock()
    relationship_repo = MagicMock()

    async def _get_by_id(eid: str):
        return entities.get(eid)

    async def _list_by_entity(eid: str):
        return [r for r in relationships if r.source_entity_id == eid or r.target_id == eid]

    async def _get_embeddings_by_ids(ids: list[str]):
        if embeddings is None:
            return {}
        return {eid: embeddings.get(eid) for eid in ids if eid in embeddings}

    entity_repo.get_by_id = AsyncMock(side_effect=_get_by_id)
    entity_repo.get_embeddings_by_ids = AsyncMock(side_effect=_get_embeddings_by_ids)
    relationship_repo.list_by_entity = AsyncMock(side_effect=_list_by_entity)

    return OntologyService(
        entity_repo=entity_repo,
        relationship_repo=relationship_repo,
        document_repo=MagicMock(),
        protocol_repo=MagicMock(),
        blindspot_repo=MagicMock(),
        embedding_service=embedding_service,
    )


def _vec(base: float, dim: int = 768) -> list[float]:
    """Return a unit-ish vector where all components equal base."""
    return [base] * dim


def _sparse_vec(score_approx: float, dim: int = 768) -> list[float]:
    """Return a vector whose cosine sim with [1.0]*dim roughly equals score_approx.

    Strategy: first component = score_approx, rest = small positive value.
    Cosine with [1.0, 1.0, ...] = sum(v) / (sqrt(sum(v^2)) * sqrt(dim)).
    We approximate by making v[0] = score_approx and v[1:] near-zero.
    This gives a clearly distinguishable ordering without exact math.
    We achieve an ordering by simply placing score_approx in v[0] and 0 elsewhere.
    cosine([q, 0...0], [1,1...1]) = q / (|q| * sqrt(dim)) * sqrt(1) -- not useful.

    Simpler: make query = e0 (unit vector on dimension 0).
    Neighbor vector = [score_approx, 0, 0, ...].
    cosine(neighbor, e0) = score_approx / |neighbor| = sign(score_approx).
    That is also not distinguishable.

    Best approach: query = [1,0,...,0] and neighbor = [s, sqrt(1-s^2), 0,...,0].
    cosine = s (since both are unit vectors and dot = s).
    """
    # Build unit vector: first component = score_approx, second = complement
    import math
    second = math.sqrt(max(0.0, 1.0 - score_approx ** 2))
    v = [0.0] * dim
    v[0] = score_approx
    if dim > 1:
        v[1] = second
    return v


@pytest.mark.spec("AC-SEMRET-13")
@pytest.mark.asyncio
async def test_ac_semret_13_intent_ranking():
    """AC-SEMRET-13: intent → embed query → each hop cosine-rank neighbors → top_k_per_hop=3 retained → each neighbor has relevance_score float."""
    # Graph: root -> A, B, C, D, E (5 forward neighbors at depth=1)
    root_id = "root"
    entities = {
        root_id: _make_graph_entity(root_id, "Root"),
        "A": _make_graph_entity("A", "Alpha"),
        "B": _make_graph_entity("B", "Beta"),
        "C": _make_graph_entity("C", "Gamma"),
        "D": _make_graph_entity("D", "Delta"),
        "E": _make_graph_entity("E", "Epsilon"),
    }
    rels = [
        _make_relationship(root_id, "A"),
        _make_relationship(root_id, "B"),
        _make_relationship(root_id, "C"),
        _make_relationship(root_id, "D"),
        _make_relationship(root_id, "E"),
    ]

    # Use unit-vector design: query = e0 = [1,0,...,0].
    # Neighbor vec cosine to e0 = neighbor[0] (first component).
    # _sparse_vec(s) produces a unit vector with first component = s.
    # Expected order: A(0.9) > D(0.8) > B(0.5) > E(0.3) > C(0.1)
    query_vec = _sparse_vec(1.0)  # e0-like unit vector
    embeddings = {
        "A": _sparse_vec(0.9),
        "B": _sparse_vec(0.5),
        "C": _sparse_vec(0.1),
        "D": _sparse_vec(0.8),
        "E": _sparse_vec(0.3),
    }

    embed_svc = MagicMock()
    embed_svc.embed_query = AsyncMock(return_value=query_vec)

    svc = _build_ontology_service(entities, rels, embedding_service=embed_svc, embeddings=embeddings)

    chain = await svc.compute_impact_chain(
        root_id, direction="forward", max_depth=3, intent="治理 audit", top_k_per_hop=3,
    )

    # embed_query must have been called with the intent
    embed_svc.embed_query.assert_called_once_with("治理 audit")

    # Only 3 results (top_k_per_hop=3 out of 5 candidates)
    assert len(chain) == 3, f"Expected 3 results, got {len(chain)}: {chain}"

    # Each result must have a float relevance_score
    for hop in chain:
        assert "relevance_score" in hop, f"Missing relevance_score in hop: {hop}"
        assert isinstance(hop["relevance_score"], float), (
            f"relevance_score should be float, got {type(hop['relevance_score'])}"
        )

    # Top-3 should be A (0.9), D (0.8), B (0.5) — sorted descending by cosine
    result_ids = [hop["to_id"] for hop in chain]
    assert result_ids[0] == "A", f"Expected A first (highest score), got {result_ids[0]}"
    assert result_ids[1] == "D", f"Expected D second, got {result_ids[1]}"
    assert result_ids[2] == "B", f"Expected B third, got {result_ids[2]}"

    # Scores should be descending
    scores = [hop["relevance_score"] for hop in chain]
    assert scores[0] > scores[1] > scores[2], f"Scores not descending: {scores}"


@pytest.mark.spec("AC-SEMRET-14")
@pytest.mark.asyncio
async def test_ac_semret_14_root_self_ranking():
    """AC-SEMRET-14: intent=None + root has embedding → use root.summary_embedding as query_vec → same ranking behavior as AC-13."""
    root_id = "root"
    entities = {
        root_id: _make_graph_entity(root_id, "Root"),
        "A": _make_graph_entity("A", "Alpha"),
        "B": _make_graph_entity("B", "Beta"),
        "C": _make_graph_entity("C", "Gamma"),
    }
    rels = [
        _make_relationship(root_id, "A"),
        _make_relationship(root_id, "B"),
        _make_relationship(root_id, "C"),
    ]

    # Use sparse unit vectors: cosine(neighbor, root_vec) = neighbor[0]
    root_vec = _sparse_vec(1.0)
    embeddings = {
        root_id: root_vec,
        "A": _sparse_vec(0.9),   # highest sim
        "B": _sparse_vec(0.2),
        "C": _sparse_vec(0.6),
    }

    # EmbeddingService is present but embed_query must NOT be called (intent=None)
    embed_svc = MagicMock()
    embed_svc.embed_query = AsyncMock(return_value=None)

    svc = _build_ontology_service(entities, rels, embedding_service=embed_svc, embeddings=embeddings)

    chain = await svc.compute_impact_chain(
        root_id, direction="forward", max_depth=3, intent=None, top_k_per_hop=3,
    )

    # embed_query must NOT be called (intent is None)
    embed_svc.embed_query.assert_not_called()

    # All 3 neighbors fit within top_k=3
    assert len(chain) == 3

    # Scores must be floats
    for hop in chain:
        assert "relevance_score" in hop
        assert isinstance(hop["relevance_score"], float)

    # A (0.9) should rank first
    result_ids = [hop["to_id"] for hop in chain]
    assert result_ids[0] == "A", f"Expected A first, got {result_ids[0]}"


@pytest.mark.spec("AC-SEMRET-15")
@pytest.mark.asyncio
async def test_ac_semret_15_fallback_alphabetical():
    """AC-SEMRET-15: neighbor with no embedding → relevance_score=null + sorted alphabetically by name, placed at tail of the hop."""
    root_id = "root"
    entities = {
        root_id: _make_graph_entity(root_id, "Root"),
        "scored1": _make_graph_entity("scored1", "Zebra"),    # has embedding, high score
        "scored2": _make_graph_entity("scored2", "Mango"),    # has embedding, low score
        "noscore_a": _make_graph_entity("noscore_a", "Apple"),  # no embedding
        "noscore_b": _make_graph_entity("noscore_b", "Banana"), # no embedding
    }
    rels = [
        _make_relationship(root_id, "scored1"),
        _make_relationship(root_id, "scored2"),
        _make_relationship(root_id, "noscore_a"),
        _make_relationship(root_id, "noscore_b"),
    ]

    query_vec = _sparse_vec(1.0)
    embeddings = {
        root_id: query_vec,
        "scored1": _sparse_vec(0.9),
        "scored2": _sparse_vec(0.3),
        # noscore_a and noscore_b intentionally absent
    }

    embed_svc = MagicMock()
    embed_svc.embed_query = AsyncMock(return_value=query_vec)

    svc = _build_ontology_service(entities, rels, embedding_service=embed_svc, embeddings=embeddings)

    chain = await svc.compute_impact_chain(
        root_id, direction="forward", max_depth=2, intent="test", top_k_per_hop=None,
    )

    assert len(chain) == 4, f"Expected all 4 neighbors, got {len(chain)}"

    # All hops must have relevance_score key
    for hop in chain:
        assert "relevance_score" in hop

    # Scored items must come before null items
    scored_hops = [h for h in chain if h["relevance_score"] is not None]
    null_hops = [h for h in chain if h["relevance_score"] is None]

    assert len(scored_hops) == 2
    assert len(null_hops) == 2

    # scored items appear first
    scored_positions = [chain.index(h) for h in scored_hops]
    null_positions = [chain.index(h) for h in null_hops]
    assert max(scored_positions) < min(null_positions), (
        "Scored hops must appear before null hops"
    )

    # scored items are ordered by score descending (Zebra > Mango)
    assert scored_hops[0]["to_id"] == "scored1"
    assert scored_hops[1]["to_id"] == "scored2"

    # null items are alphabetical by name: Apple < Banana
    assert null_hops[0]["to_name"] == "Apple"
    assert null_hops[1]["to_name"] == "Banana"


@pytest.mark.spec("AC-SEMRET-16")
@pytest.mark.asyncio
async def test_ac_semret_16_no_pruning():
    """AC-SEMRET-16: top_k_per_hop=None → no pruning, all neighbors preserved, each with relevance_score (or null if no embed)."""
    root_id = "root"
    entities = {
        root_id: _make_graph_entity(root_id, "Root"),
        **{f"n{i}": _make_graph_entity(f"n{i}", f"Node{i:02d}") for i in range(6)},
    }
    rels = [_make_relationship(root_id, f"n{i}") for i in range(6)]

    query_vec = _sparse_vec(1.0)
    # Only n0..n2 have embeddings; n3..n5 do not
    embeddings = {
        root_id: query_vec,
        "n0": _sparse_vec(0.8),
        "n1": _sparse_vec(0.5),
        "n2": _sparse_vec(0.2),
    }

    embed_svc = MagicMock()
    embed_svc.embed_query = AsyncMock(return_value=query_vec)

    svc = _build_ontology_service(entities, rels, embedding_service=embed_svc, embeddings=embeddings)

    chain = await svc.compute_impact_chain(
        root_id, direction="forward", max_depth=2, intent="test", top_k_per_hop=None,
    )

    # All 6 neighbors must be preserved
    assert len(chain) == 6, f"Expected 6 results (no pruning), got {len(chain)}: {chain}"

    # All hops must have relevance_score key
    for hop in chain:
        assert "relevance_score" in hop

    # n0..n2 have float scores; n3..n5 have null
    scored = [h for h in chain if h["relevance_score"] is not None]
    unscored = [h for h in chain if h["relevance_score"] is None]
    assert len(scored) == 3
    assert len(unscored) == 3


@pytest.mark.spec("AC-SEMRET-17")
@pytest.mark.asyncio
async def test_ac_semret_17_all_fallback():
    """AC-SEMRET-17: root has no embedding AND intent=None → entire chain fallback alphabetical, all relevance_score=null, top_k applied as alphabetical top-K, NO embedding API call."""
    root_id = "root"
    entities = {
        root_id: _make_graph_entity(root_id, "Root"),
        "id_z": _make_graph_entity("id_z", "Zebra"),
        "id_a": _make_graph_entity("id_a", "Apple"),
        "id_m": _make_graph_entity("id_m", "Mango"),
        "id_b": _make_graph_entity("id_b", "Banana"),
        "id_c": _make_graph_entity("id_c", "Cherry"),
    }
    rels = [
        _make_relationship(root_id, "id_z"),
        _make_relationship(root_id, "id_a"),
        _make_relationship(root_id, "id_m"),
        _make_relationship(root_id, "id_b"),
        _make_relationship(root_id, "id_c"),
    ]

    # No embeddings at all (root has no embedding either)
    embeddings: dict = {}

    embed_svc = MagicMock()
    embed_svc.embed_query = AsyncMock(return_value=_vec(0.5))  # should never be called

    svc = _build_ontology_service(entities, rels, embedding_service=embed_svc, embeddings=embeddings)

    chain = await svc.compute_impact_chain(
        root_id, direction="forward", max_depth=2, intent=None, top_k_per_hop=3,
    )

    # embed_query must NOT be called (no intent, no root embedding → full alphabetical fallback)
    embed_svc.embed_query.assert_not_called()

    # top_k_per_hop=3 → only top 3 alphabetical
    assert len(chain) == 3, f"Expected 3 (top-3 alphabetical), got {len(chain)}"

    # All relevance_score must be null
    for hop in chain:
        assert "relevance_score" in hop
        assert hop["relevance_score"] is None, (
            f"relevance_score must be null in full fallback mode, got {hop['relevance_score']}"
        )

    # Must be alphabetical: Apple, Banana, Cherry (not Mango or Zebra)
    names = [hop["to_name"] for hop in chain]
    assert names == ["Apple", "Banana", "Cherry"], f"Expected alphabetical top-3, got {names}"


@pytest.mark.spec("AC-SEMRET-18")
@pytest.mark.asyncio
async def test_ac_semret_18_relevance_score_field():
    """AC-SEMRET-18: each hop dict includes `relevance_score: float | null` as new field; ADR-040 existing fields preserved."""
    root_id = "root"
    entities = {
        root_id: _make_graph_entity(root_id, "Root"),
        "child": _make_graph_entity("child", "Child"),
    }
    rels = [_make_relationship(root_id, "child")]

    # No embedding service — full alphabetical fallback
    svc = _build_ontology_service(entities, rels, embedding_service=None, embeddings={})

    chain = await svc.compute_impact_chain(root_id, direction="forward", max_depth=2)

    assert len(chain) == 1
    hop = chain[0]

    # ADR-040 existing fields must be present
    assert "from_id" in hop, "from_id missing"
    assert "from_name" in hop, "from_name missing"
    assert "type" in hop, "type missing"
    assert "to_id" in hop, "to_id missing"
    assert "to_name" in hop, "to_name missing"

    # New field added by S04
    assert "relevance_score" in hop, "relevance_score missing (new S04 field)"

    # Values must be correct
    assert hop["from_id"] == root_id
    assert hop["to_id"] == "child"
    assert hop["to_name"] == "Child"
    assert hop["relevance_score"] is None  # no embedding service → null


# ============================================================
# R4: Search Hybrid Mode (AC-SEMRET-19..24)
# ============================================================

# ---------------------------------------------------------------------------
# Helpers for R4 tests
# ---------------------------------------------------------------------------

def _make_search_entity(
    eid: str,
    name: str,
    summary: str = "summary text",
    tags: "Tags | None" = None,
) -> "Entity":
    from zenos.domain.knowledge.models import Entity, Tags
    return Entity(
        id=eid,
        name=name,
        type="module",
        summary=summary,
        tags=tags or Tags(what=[], why="", how="", who=[]),
    )


def _build_search_service(
    entities: list,
    *,
    embed_query_return: list[float] | None = None,
    vector_pairs: list | None = None,
) -> "Any":
    """Build SearchService with mocked repo and embedding_service."""
    from zenos.application.knowledge.search_service import SearchService

    repo = MagicMock()
    repo.list_all = AsyncMock(return_value=entities)
    # search_by_vector returns (Entity, score) pairs
    repo.search_by_vector = AsyncMock(return_value=vector_pairs or [])

    embed_svc = MagicMock()
    embed_svc.embed_query = AsyncMock(return_value=embed_query_return)

    return SearchService(repo, embed_svc), repo, embed_svc


@pytest.mark.spec("AC-SEMRET-19")
@pytest.mark.asyncio
async def test_ac_semret_19_search_semantic():
    """AC-SEMRET-19: mode=semantic → query embedded → pgvector cosine sort → top N results, each with score=cosine."""
    from zenos.domain.knowledge.models import Tags

    entities = [
        _make_search_entity("e1", "Governance Module", "治理 is a governance process"),
        _make_search_entity("e2", "Auth Module", "authentication"),
    ]

    query_vec = _fake_vec(768)
    # search_by_vector returns (entity, cosine_score) pairs, already sorted by score
    vector_pairs = [
        (entities[0], 0.92),
        (entities[1], 0.55),
    ]

    svc, repo, embed_svc = _build_search_service(
        entities,
        embed_query_return=query_vec,
        vector_pairs=vector_pairs,
    )

    results = await svc.search_entities("治理", mode="semantic", limit=10)

    # embed_query must be called with the query
    embed_svc.embed_query.assert_called_once_with("治理")

    # search_by_vector must be called with the query vector
    repo.search_by_vector.assert_called_once()
    call_args = repo.search_by_vector.call_args
    assert call_args.args[0] == query_vec

    # Results must contain correct scores
    assert len(results) == 2

    # Each result must have score = cosine
    assert results[0]["score"] == pytest.approx(0.92, abs=1e-5)
    assert results[1]["score"] == pytest.approx(0.55, abs=1e-5)

    # Each result must have score_breakdown with semantic score
    assert results[0]["score_breakdown"]["semantic"] == pytest.approx(0.92, abs=1e-5)
    assert results[1]["score_breakdown"]["semantic"] == pytest.approx(0.55, abs=1e-5)

    # Entity objects must be accessible
    assert results[0]["_entity"].id == "e1"
    assert results[1]["_entity"].id == "e2"


@pytest.mark.spec("AC-SEMRET-20")
@pytest.mark.asyncio
async def test_ac_semret_20_search_hybrid():
    """AC-SEMRET-20: mode=hybrid (default) → final = 0.7*semantic + 0.3*keyword_boolean where keyword_boolean = any(query_lower in val_lower for val in [name, summary, tags flattened]); each result has score + score_breakdown {semantic, keyword}."""
    from zenos.application.knowledge.search_service import HYBRID_KEYWORD_WEIGHT, HYBRID_SEMANTIC_WEIGHT

    # Entity A: high semantic score + keyword match → highest hybrid score
    entity_a = _make_search_entity("eA", "治理 Module", "governance audit process", tags=None)
    # Entity B: high semantic score only, no keyword match
    entity_b = _make_search_entity("eB", "Auth Module", "authentication module", tags=None)
    # Entity C: low semantic score but keyword match in name
    entity_c = _make_search_entity("eC", "治理 Index", "some unrelated text", tags=None)

    entities = [entity_a, entity_b, entity_c]

    query_vec = _fake_vec(768)
    vector_pairs = [
        (entity_a, 0.9),
        (entity_b, 0.8),
        (entity_c, 0.2),
    ]

    svc, repo, embed_svc = _build_search_service(
        entities,
        embed_query_return=query_vec,
        vector_pairs=vector_pairs,
    )

    results = await svc.search_entities("治理", mode="hybrid", limit=10)

    # embed_query must be called
    embed_svc.embed_query.assert_called_once_with("治理")

    assert len(results) >= 2

    # Find result for entity_a
    result_a = next(r for r in results if r["_entity"].id == "eA")
    # entity_a has keyword match (治理 in name) → keyword = 1.0
    expected_score_a = HYBRID_SEMANTIC_WEIGHT * 0.9 + HYBRID_KEYWORD_WEIGHT * 1.0
    assert result_a["score"] == pytest.approx(expected_score_a, abs=1e-5)
    assert result_a["score_breakdown"]["semantic"] == pytest.approx(0.9, abs=1e-5)
    assert result_a["score_breakdown"]["keyword"] == pytest.approx(1.0, abs=1e-5)

    # Find result for entity_b
    result_b = next(r for r in results if r["_entity"].id == "eB")
    # entity_b has no keyword match → keyword = 0.0
    expected_score_b = HYBRID_SEMANTIC_WEIGHT * 0.8 + HYBRID_KEYWORD_WEIGHT * 0.0
    assert result_b["score"] == pytest.approx(expected_score_b, abs=1e-5)
    assert result_b["score_breakdown"]["keyword"] == pytest.approx(0.0, abs=1e-5)

    # All results must have score_breakdown with both keys
    for r in results:
        assert "score_breakdown" in r
        assert "semantic" in r["score_breakdown"]
        assert "keyword" in r["score_breakdown"]


@pytest.mark.spec("AC-SEMRET-21")
@pytest.mark.asyncio
async def test_ac_semret_21_keyword_compat():
    """AC-SEMRET-21: mode=keyword → current behavior preserved (backward compat), no embedding API call."""
    from zenos.domain.knowledge.models import Tags

    entity_match = _make_search_entity("e1", "治理 Module", "governance audit")
    entity_no_match = _make_search_entity("e2", "Auth Module", "authentication")

    svc, repo, embed_svc = _build_search_service([entity_match, entity_no_match])

    results = await svc.search_entities("治理", mode="keyword", limit=10)

    # embed_query must NOT be called (keyword mode = no embedding API)
    embed_svc.embed_query.assert_not_called()

    # Only entity with keyword match returned
    assert len(results) == 1
    assert results[0]["_entity"].id == "e1"

    # score_breakdown.semantic must be None for keyword mode
    assert results[0]["score_breakdown"]["semantic"] is None


@pytest.mark.spec("AC-SEMRET-22")
@pytest.mark.asyncio
async def test_ac_semret_22_empty_query_fallback():
    """AC-SEMRET-22: mode=hybrid + query='' → degrades to mode=keyword (list all, no embed API); each result has score_breakdown.semantic=null."""
    entities = [
        _make_search_entity("e1", "Module A"),
        _make_search_entity("e2", "Module B"),
    ]

    svc, repo, embed_svc = _build_search_service(entities)

    results = await svc.search_entities("", mode="hybrid", limit=10)

    # embed_query must NOT be called (empty query → keyword degrade)
    embed_svc.embed_query.assert_not_called()

    # search_by_vector must NOT be called
    repo.search_by_vector.assert_not_called()

    # list_all is called (keyword list-all)
    repo.list_all.assert_called()

    # All entities returned (list-all behavior)
    assert len(results) == 2

    # score_breakdown.semantic must be null for each result
    for r in results:
        assert r["score_breakdown"]["semantic"] is None, (
            f"Expected semantic=null for empty query fallback, got {r['score_breakdown']['semantic']}"
        )

    # Also verify mode="semantic" + empty query also degrades
    embed_svc.embed_query.reset_mock()
    repo.search_by_vector.reset_mock()
    repo.list_all.reset_mock()
    repo.list_all = AsyncMock(return_value=entities)

    results_sem = await svc.search_entities("", mode="semantic", limit=10)
    embed_svc.embed_query.assert_not_called()
    for r in results_sem:
        assert r["score_breakdown"]["semantic"] is None


@pytest.mark.spec("AC-SEMRET-23")
@pytest.mark.asyncio
async def test_ac_semret_23_default_hybrid():
    """AC-SEMRET-23: search(collection=entities, query=X) without mode → uses hybrid as default."""
    from zenos.application.knowledge.search_service import SearchService

    entities = [_make_search_entity("e1", "治理 Module", "governance")]
    query_vec = _fake_vec(768)

    repo = MagicMock()
    repo.list_all = AsyncMock(return_value=entities)
    repo.search_by_vector = AsyncMock(return_value=[(entities[0], 0.9)])

    embed_svc = MagicMock()
    embed_svc.embed_query = AsyncMock(return_value=query_vec)

    svc = SearchService(repo, embed_svc)

    # Call WITHOUT explicit mode → must default to hybrid
    results = await svc.search_entities("治理", limit=10)

    # embed_query should be called (hybrid calls embedding)
    embed_svc.embed_query.assert_called_once_with("治理")

    # Results should have score_breakdown with both semantic and keyword fields
    assert len(results) >= 1
    for r in results:
        assert "score_breakdown" in r
        assert "semantic" in r["score_breakdown"]
        assert "keyword" in r["score_breakdown"]


@pytest.mark.spec("AC-SEMRET-24")
@pytest.mark.asyncio
async def test_ac_semret_24_api_fail_fallback():
    """AC-SEMRET-24: mode=semantic|hybrid + non-empty query + Gemini API failure → fallback to mode=keyword + WARNING log; response returned (no exception to caller)."""
    import logging

    entities = [
        _make_search_entity("e1", "治理 Module", "governance audit"),
        _make_search_entity("e2", "Auth Module", "authentication"),
    ]

    # Test semantic mode fallback
    repo_sem = MagicMock()
    repo_sem.list_all = AsyncMock(return_value=entities)
    repo_sem.search_by_vector = AsyncMock(return_value=[])

    embed_svc_sem = MagicMock()
    embed_svc_sem.embed_query = AsyncMock(return_value=None)  # API fail → None

    from zenos.application.knowledge.search_service import SearchService

    svc_sem = SearchService(repo_sem, embed_svc_sem)

    warning_logged = []
    with patch.object(
        logging.getLogger("zenos.application.knowledge.search_service"),
        "warning",
        side_effect=lambda *a, **kw: warning_logged.append(a),
    ):
        results_sem = await svc_sem.search_entities("治理", mode="semantic", limit=10)

    # Must NOT raise — response returned
    assert isinstance(results_sem, list)

    # WARNING must have been logged
    assert len(warning_logged) >= 1, "Expected WARNING log when embed_query returns None"

    # Fallback to keyword: only e1 matches "治理"
    assert len(results_sem) == 1
    assert results_sem[0]["_entity"].id == "e1"

    # search_by_vector must NOT be called (fallback path skips vector search)
    repo_sem.search_by_vector.assert_not_called()

    # Test hybrid mode fallback
    repo_hyb = MagicMock()
    repo_hyb.list_all = AsyncMock(return_value=entities)
    repo_hyb.search_by_vector = AsyncMock(return_value=[])

    embed_svc_hyb = MagicMock()
    embed_svc_hyb.embed_query = AsyncMock(return_value=None)  # API fail → None

    svc_hyb = SearchService(repo_hyb, embed_svc_hyb)

    warning_logged_hyb = []
    with patch.object(
        logging.getLogger("zenos.application.knowledge.search_service"),
        "warning",
        side_effect=lambda *a, **kw: warning_logged_hyb.append(a),
    ):
        results_hyb = await svc_hyb.search_entities("治理", mode="hybrid", limit=10)

    assert isinstance(results_hyb, list)
    assert len(warning_logged_hyb) >= 1
    assert len(results_hyb) == 1
    assert results_hyb[0]["_entity"].id == "e1"
    repo_hyb.search_by_vector.assert_not_called()


# ============================================================
# R5: MCP Interface (AC-SEMRET-25..28)
# ============================================================

@pytest.mark.spec("AC-SEMRET-25")
@pytest.mark.asyncio
async def test_ac_semret_25_get_kwargs():
    """AC-SEMRET-25: get(collection=entities, include=[impact_chain], intent=X, top_k_per_hop=3) passes intent/top_k_per_hop to compute_impact_chain."""
    from unittest.mock import AsyncMock, MagicMock, patch
    from zenos.domain.knowledge.models import Entity, Tags
    from zenos.application.knowledge.ontology_service import EntityWithRelationships
    import zenos.interface.mcp as _mcp_module

    fake_entity_id = "entity-test-001"
    fake_entity = Entity(
        id=fake_entity_id,
        name="Test Entity",
        type="module",
        summary="A test entity",
        tags=Tags(what=[], why="", how="", who=[]),
        status="active",
        confirmed_by_user=True,
        sources=[],
    )
    fake_ewr = EntityWithRelationships(entity=fake_entity, relationships=[])

    # Track compute_impact_chain calls
    impact_chain_calls: list[dict] = []

    async def _spy_compute_impact_chain(eid: str, *, direction: str = "forward", **kwargs):
        impact_chain_calls.append({"eid": eid, "direction": direction, **kwargs})
        return []

    with (
        patch.object(_mcp_module, "ontology_service", MagicMock()) as mock_ont_svc,
        patch.object(_mcp_module, "entity_repo", MagicMock()),
        patch.object(_mcp_module, "relationship_repo", MagicMock()),
        patch("zenos.interface.mcp._ensure_services", new=AsyncMock()),
        patch("zenos.interface.mcp.get._current_partner") as mock_partner,
        patch("zenos.interface.mcp.get._is_entity_visible", return_value=True),
        patch("zenos.interface.mcp.get._schedule_tool_event"),
    ):
        mock_partner.get.return_value = {}
        mock_ont_svc.get_entity = AsyncMock(return_value=fake_ewr)
        mock_ont_svc.compute_impact_chain = _spy_compute_impact_chain
        _mcp_module.entity_repo.get_by_id = AsyncMock(return_value=None)

        from zenos.interface.mcp.get import get as _get_tool

        resp = await _get_tool(
            collection="entities",
            name="Test Entity",
            include=["impact_chain"],
            intent="治理 audit",
            top_k_per_hop=3,
        )

    # compute_impact_chain must have been called at least once
    assert len(impact_chain_calls) >= 1, "compute_impact_chain was not called"

    # All calls must carry intent and top_k_per_hop
    for call in impact_chain_calls:
        assert call.get("intent") == "治理 audit", (
            f"Expected intent='治理 audit' in compute_impact_chain call, got: {call}"
        )
        assert call.get("top_k_per_hop") == 3, (
            f"Expected top_k_per_hop=3 in compute_impact_chain call, got: {call}"
        )


@pytest.mark.spec("AC-SEMRET-26")
@pytest.mark.asyncio
async def test_ac_semret_26_kwargs_ignored_without_chain():
    """AC-SEMRET-26: get without include=[impact_chain] + intent/top_k_per_hop → params silently ignored, non-impact_chain path unaffected."""
    import zenos.interface.mcp as _mcp_module
    from unittest.mock import AsyncMock, MagicMock, patch
    from zenos.domain.knowledge.models import Entity, Tags
    from zenos.application.knowledge.ontology_service import EntityWithRelationships

    fake_entity = Entity(
        id="entity-026",
        name="Entity 026",
        type="module",
        summary="A test entity for AC-26",
        tags=Tags(what=[], why="", how="", who=[]),
        status="active",
        confirmed_by_user=True,
        sources=[],
    )
    fake_ewr = EntityWithRelationships(entity=fake_entity, relationships=[])

    compute_chain_called = []

    async def _spy_compute(eid: str, *, direction: str = "forward", **kwargs):
        compute_chain_called.append({"eid": eid, "direction": direction, **kwargs})
        return []

    with (
        patch.object(_mcp_module, "ontology_service", MagicMock()) as mock_ont_svc,
        patch.object(_mcp_module, "entity_repo", MagicMock()),
        patch.object(_mcp_module, "relationship_repo", MagicMock()),
        patch("zenos.interface.mcp._ensure_services", new=AsyncMock()),
        patch("zenos.interface.mcp.get._current_partner") as mock_partner,
        patch("zenos.interface.mcp.get._is_entity_visible", return_value=True),
        patch("zenos.interface.mcp.get._schedule_tool_event"),
    ):
        mock_partner.get.return_value = {}
        mock_ont_svc.get_entity = AsyncMock(return_value=fake_ewr)
        mock_ont_svc.compute_impact_chain = _spy_compute
        _mcp_module.entity_repo.list_by_entity = AsyncMock(return_value=[])

        from zenos.interface.mcp.get import get as _get_tool

        # include=["summary"] — no impact_chain, but intent/top_k_per_hop passed
        resp = await _get_tool(
            collection="entities",
            name="Entity 026",
            include=["summary"],
            intent="should be ignored",
            top_k_per_hop=5,
        )

    # compute_impact_chain must NOT be called when include does not contain impact_chain
    assert len(compute_chain_called) == 0, (
        f"compute_impact_chain should not be called for include=['summary'], "
        f"but was called: {compute_chain_called}"
    )

    # Response must be successful (not an error)
    assert resp.get("status") != "rejected", f"Expected success response, got: {resp}"


@pytest.mark.spec("AC-SEMRET-27")
@pytest.mark.asyncio
async def test_ac_semret_27_search_mode_signature():
    """AC-SEMRET-27: search MCP signature has mode: str = 'hybrid' parameter."""
    import inspect
    from zenos.interface.mcp.search import search

    sig = inspect.signature(search)
    params = sig.parameters

    # mode parameter must exist
    assert "mode" in params, f"'mode' parameter missing from search() signature. Params: {list(params.keys())}"

    mode_param = params["mode"]

    # mode must have a default value of "hybrid"
    assert mode_param.default == "hybrid", (
        f"Expected mode default='hybrid', got default={mode_param.default!r}"
    )

    # mode must be annotated as str (handle both str and 'str' due to from __future__ import annotations)
    annotation = mode_param.annotation
    assert annotation in (str, "str"), (
        f"Expected mode annotation=str or 'str', got {annotation!r}"
    )


@pytest.mark.spec("AC-SEMRET-28")
@pytest.mark.asyncio
async def test_ac_semret_28_docstrings():
    """AC-SEMRET-28: search docstring lists mode values (keyword|semantic|hybrid) with semantics; get docstring documents intent/top_k_per_hop under include=[impact_chain]."""
    from zenos.interface.mcp.search import search
    from zenos.interface.mcp.get import get

    # ── search docstring checks ──────────────────────────────────────────────
    search_doc = search.__doc__ or ""

    assert "keyword" in search_doc, "search docstring missing 'keyword' mode description"
    assert "semantic" in search_doc, "search docstring missing 'semantic' mode description"
    assert "hybrid" in search_doc, "search docstring missing 'hybrid' mode description"

    # mode descriptions must include distinct semantic explanations
    assert "mode=" in search_doc or "mode 參數" in search_doc, (
        "search docstring should document mode parameter values"
    )

    # ── get docstring checks ─────────────────────────────────────────────────
    get_doc = get.__doc__ or ""

    assert "intent" in get_doc, "get docstring missing 'intent' parameter description"
    assert "top_k_per_hop" in get_doc, "get docstring missing 'top_k_per_hop' parameter description"
    assert "impact_chain" in get_doc, "get docstring missing 'impact_chain' context for kwargs"


# ============================================================
# R6: Batch Backfill (AC-SEMRET-29..33)
# ============================================================

# ---------------------------------------------------------------------------
# Helpers for R6 tests
# ---------------------------------------------------------------------------

def _make_backfill_entity(
    eid: str,
    *,
    summary: str = "A valid summary",
    embedded_summary_hash: str | None = None,
    embedding_model: str | None = None,
    embedded_at: "datetime | None" = None,
) -> "Any":
    return Entity(
        id=eid,
        name=f"Entity {eid}",
        type="module",
        summary=summary,
        tags=Tags(what=[], why="", how="", who=[]),
        embedded_summary_hash=embedded_summary_hash,
        embedding_model=embedding_model,
        embedded_at=embedded_at,
    )


def _make_backfill_args(*, dry_run: bool = False, only_reembed: bool = False) -> "Any":
    import argparse
    args = argparse.Namespace()
    args.dry_run = dry_run
    args.only_reembed = only_reembed
    return args


async def _run_main_async_with_mocks(
    args: "Any",
    entities: list,
    embed_return: "list[float] | None" = None,
) -> tuple["Any", list[str]]:
    """Run main_async with fully mocked repo, llm, and partner lookup.

    Returns:
        (stats_from_service, captured_print_lines)
    """
    import io
    from unittest.mock import AsyncMock, MagicMock, patch

    from zenos.application.knowledge.embedding_service import EmbeddingService, BackfillStats

    embed_return = embed_return or _fake_vec(768)

    # Build a mock entity_repo that returns our entities list.
    mock_repo = MagicMock()
    mock_repo.list_all = AsyncMock(return_value=entities)
    mock_repo.get_by_id = AsyncMock(side_effect=lambda eid: next(
        (e for e in entities if e.id == eid), None
    ))
    mock_repo.update_embedding = AsyncMock()

    # Build a mock llm_client.
    mock_llm = MagicMock()
    mock_llm.embed = AsyncMock(return_value=[embed_return])

    import asyncpg  # type: ignore[import-untyped]

    captured_lines: list[str] = []

    async def _mock_resolve_admin(pool) -> str:
        return "admin-partner-test"

    with (
        patch("scripts.backfill_embeddings._resolve_admin_partner_id", new=_mock_resolve_admin),
        patch("scripts.backfill_embeddings.get_pool", new=AsyncMock(return_value=MagicMock())),
        patch("scripts.backfill_embeddings.SqlEntityRepository", return_value=mock_repo),
        patch("scripts.backfill_embeddings.create_llm_client", return_value=mock_llm),
        patch("scripts.backfill_embeddings.current_partner_id") as mock_ctx,
        patch("builtins.print", side_effect=lambda *a, **kw: captured_lines.append(" ".join(str(x) for x in a))),
    ):
        mock_ctx.set = MagicMock()
        from scripts.backfill_embeddings import main_async
        exit_code = await main_async(args)

    return exit_code, captured_lines, mock_repo, mock_llm


@pytest.mark.spec("AC-SEMRET-29")
@pytest.mark.asyncio
async def test_ac_semret_29_backfill_dry_run():
    """AC-SEMRET-29: backfill_embeddings.py --dry-run prints 'will process N entities' WITHOUT calling embedding API or writing DB."""
    entities = [
        _make_backfill_entity("e1"),                              # null hash → needs embed
        _make_backfill_entity("e2"),                              # null hash → needs embed
        _make_backfill_entity("e3", embedded_summary_hash="FAILED"),  # failed → needs embed
    ]
    args = _make_backfill_args(dry_run=True)

    exit_code, lines, mock_repo, mock_llm = await _run_main_async_with_mocks(args, entities)

    # Must have printed the "will process N" message
    printed = "\n".join(lines)
    assert "will process" in printed, (
        f"Expected 'will process N entities' in dry-run output, got:\n{printed}"
    )
    assert "3" in printed, (
        f"Expected count=3 in dry-run output, got:\n{printed}"
    )

    # Must NOT have called embedding API
    mock_llm.embed.assert_not_called()

    # Must NOT have written to DB
    mock_repo.update_embedding.assert_not_called()


@pytest.mark.spec("AC-SEMRET-30")
@pytest.mark.asyncio
async def test_ac_semret_30_backfill_full():
    """AC-SEMRET-30: backfill_embeddings.py (no flag) embeds all entities with summary_embedding=null OR needs_reembed=true."""
    correct_hash = _sha256("A valid summary")
    entities = [
        # e1: never embedded (hash=None) → should be processed
        _make_backfill_entity("e1"),
        # e2: already fresh (hash matches) → should be skipped
        _make_backfill_entity("e2", embedded_summary_hash=correct_hash),
        # e3: needs reembed (hash mismatch — was embedded with different summary)
        _make_backfill_entity("e3", embedded_summary_hash="old-stale-hash"),
    ]
    args = _make_backfill_args(dry_run=False, only_reembed=False)

    exit_code, lines, mock_repo, mock_llm = await _run_main_async_with_mocks(args, entities)

    # e1 and e3 need processing; e2 is already fresh and should be skipped.
    # embed must have been called (at least once, for the non-empty-summary entities)
    assert mock_llm.embed.call_count >= 2, (
        f"Expected embed called >= 2 times for 2 unembedded entities, "
        f"got {mock_llm.embed.call_count}"
    )

    # update_embedding must have been called for e1 and e3
    updated_ids = {call.args[0] for call in mock_repo.update_embedding.call_args_list}
    assert "e1" in updated_ids, "e1 (never embedded) must be processed"
    assert "e3" in updated_ids, "e3 (stale hash) must be reprocessed"
    assert "e2" not in updated_ids, "e2 (already fresh) must NOT be reprocessed"


@pytest.mark.spec("AC-SEMRET-31")
@pytest.mark.asyncio
async def test_ac_semret_31_only_reembed():
    """AC-SEMRET-31: backfill_embeddings.py --only-reembed processes only needs_reembed=true entities (skips never-embedded nulls)."""
    correct_hash = _sha256("A valid summary")
    entities = [
        # e1: never embedded (hash=None) → SKIP with --only-reembed
        _make_backfill_entity("e1"),
        # e2: stale hash (was embedded with different summary) → PROCESS
        _make_backfill_entity("e2", embedded_summary_hash="old-stale-hash"),
        # e3: failed previously (FAILED sentinel) → PROCESS (needs_reembed=True)
        _make_backfill_entity("e3", embedded_summary_hash="FAILED"),
        # e4: already fresh → SKIP
        _make_backfill_entity("e4", embedded_summary_hash=correct_hash),
    ]
    args = _make_backfill_args(dry_run=False, only_reembed=True)

    exit_code, lines, mock_repo, mock_llm = await _run_main_async_with_mocks(args, entities)

    updated_ids = {call.args[0] for call in mock_repo.update_embedding.call_args_list}

    # e1 (never embedded, hash=None) must be SKIPPED under --only-reembed
    assert "e1" not in updated_ids, (
        "e1 (never embedded, hash=None) must be skipped when --only-reembed is set"
    )

    # e2 (stale hash) and e3 (FAILED) must be processed
    assert "e2" in updated_ids, "e2 (stale hash) must be processed with --only-reembed"
    assert "e3" in updated_ids, "e3 (FAILED sentinel) must be processed with --only-reembed"

    # e4 (already fresh) must also be skipped
    assert "e4" not in updated_ids, "e4 (already fresh) must be skipped"


@pytest.mark.spec("AC-SEMRET-32")
@pytest.mark.asyncio
async def test_ac_semret_32_rate_limit():
    """AC-SEMRET-32: batch execution respects Gemini AI Studio rate limit (<=1500 req/min) via async semaphore.

    Strategy: verify that batch_embed_missing is called with rate_limit_per_min=1500.
    The implementation in EmbeddingService (S02) enforces the semaphore + sleep logic;
    here we verify the script passes the correct rate_limit value through.

    Note: Testing the actual semaphore/sleep behavior is done at the EmbeddingService
    level. This test verifies the script-layer wiring is correct.
    ⚠️ mock test only — verifies parameter pass-through, not actual timing behavior.
    """
    from unittest.mock import AsyncMock, MagicMock, patch
    from zenos.application.knowledge.embedding_service import BackfillStats

    args = _make_backfill_args(dry_run=False, only_reembed=False)

    captured_calls: list[dict] = []

    async def _spy_batch_embed_missing(*, dry_run, only_reembed, rate_limit_per_min) -> BackfillStats:
        captured_calls.append({
            "dry_run": dry_run,
            "only_reembed": only_reembed,
            "rate_limit_per_min": rate_limit_per_min,
        })
        stats = BackfillStats()
        stats.total = 0
        stats.embedded = 0
        stats.skipped = 0
        stats.failed = 0
        stats.duration_seconds = 0.1
        return stats

    mock_service = MagicMock()
    mock_service.batch_embed_missing = _spy_batch_embed_missing

    async def _mock_resolve_admin(pool) -> str:
        return "admin-partner-test"

    with (
        patch("scripts.backfill_embeddings._resolve_admin_partner_id", new=_mock_resolve_admin),
        patch("scripts.backfill_embeddings.get_pool", new=AsyncMock(return_value=MagicMock())),
        patch("scripts.backfill_embeddings.SqlEntityRepository", return_value=MagicMock()),
        patch("scripts.backfill_embeddings.create_llm_client", return_value=MagicMock()),
        patch("scripts.backfill_embeddings.current_partner_id") as mock_ctx,
        patch("scripts.backfill_embeddings.EmbeddingService", return_value=mock_service),
        patch("builtins.print"),
    ):
        mock_ctx.set = MagicMock()
        from scripts.backfill_embeddings import main_async
        await main_async(args)

    assert len(captured_calls) == 1, "batch_embed_missing must be called exactly once"
    call = captured_calls[0]
    assert call["rate_limit_per_min"] == 1500, (
        f"Expected rate_limit_per_min=1500, got {call['rate_limit_per_min']}"
    )
    assert call["dry_run"] is False
    assert call["only_reembed"] is False


@pytest.mark.spec("AC-SEMRET-33")
@pytest.mark.asyncio
async def test_ac_semret_33_stats_output():
    """AC-SEMRET-33: script end prints stats block: total/embedded/skipped/failed/duration."""
    from unittest.mock import AsyncMock, MagicMock, patch
    from zenos.application.knowledge.embedding_service import BackfillStats

    args = _make_backfill_args(dry_run=False, only_reembed=False)

    mock_stats = BackfillStats()
    mock_stats.total = 298
    mock_stats.embedded = 295
    mock_stats.skipped = 0
    mock_stats.failed = 3
    mock_stats.duration_seconds = 45.2

    async def _mock_batch(**kwargs) -> BackfillStats:
        return mock_stats

    mock_service = MagicMock()
    mock_service.batch_embed_missing = _mock_batch

    printed_lines: list[str] = []

    async def _mock_resolve_admin(pool) -> str:
        return "admin-partner-test"

    with (
        patch("scripts.backfill_embeddings._resolve_admin_partner_id", new=_mock_resolve_admin),
        patch("scripts.backfill_embeddings.get_pool", new=AsyncMock(return_value=MagicMock())),
        patch("scripts.backfill_embeddings.SqlEntityRepository", return_value=MagicMock()),
        patch("scripts.backfill_embeddings.create_llm_client", return_value=MagicMock()),
        patch("scripts.backfill_embeddings.current_partner_id") as mock_ctx,
        patch("scripts.backfill_embeddings.EmbeddingService", return_value=mock_service),
        patch("builtins.print", side_effect=lambda *a, **kw: printed_lines.append(" ".join(str(x) for x in a))),
    ):
        mock_ctx.set = MagicMock()
        from scripts.backfill_embeddings import main_async
        await main_async(args)

    output = "\n".join(printed_lines)

    # All five stat lines must be present (substring match per AC-33)
    assert "total:" in output, f"Missing 'total:' in stats output:\n{output}"
    assert "embedded:" in output, f"Missing 'embedded:' in stats output:\n{output}"
    assert "skipped:" in output, f"Missing 'skipped:' in stats output:\n{output}"
    assert "failed:" in output, f"Missing 'failed:' in stats output:\n{output}"
    assert "duration:" in output, f"Missing 'duration:' in stats output:\n{output}"

    # Values must match the mock stats
    assert "298" in output, f"Expected total=298 in output:\n{output}"
    assert "295" in output, f"Expected embedded=295 in output:\n{output}"
    assert "45.2s" in output, f"Expected duration=45.2s in output:\n{output}"
    assert "3" in output, f"Expected failed=3 in output:\n{output}"


# ============================================================
# Non-functional (AC-SEMRET-34..37) — Phase 3 Architect verification
# ============================================================

@pytest.mark.spec("AC-SEMRET-34")
@pytest.mark.skip(reason="Architect Phase 3 dogfood verification (payload size p50 < 5KB)")
@pytest.mark.asyncio
async def test_ac_semret_34_payload_size():
    """AC-SEMRET-34: impact_chain top_k=3/max_depth=3 payload p50 < 5KB (vs ADR-040's ~27KB)."""
    pytest.fail("Architect-verified in Phase 3")


@pytest.mark.spec("AC-SEMRET-35")
@pytest.mark.skip(reason="Architect Phase 3 backfill cold-start timing")
@pytest.mark.asyncio
async def test_ac_semret_35_backfill_duration():
    """AC-SEMRET-35: 298 entity cold-start backfill < 2 minutes."""
    pytest.fail("Architect-verified in Phase 3")


@pytest.mark.spec("AC-SEMRET-36")
@pytest.mark.skip(reason="Architect Phase 3 write latency measurement")
@pytest.mark.asyncio
async def test_ac_semret_36_write_latency():
    """AC-SEMRET-36: write/confirm p95 latency increase ≤ 50ms."""
    pytest.fail("Architect-verified in Phase 3")


@pytest.mark.spec("AC-SEMRET-37")
@pytest.mark.skip(reason="Architect Phase 3 coverage metric")
@pytest.mark.asyncio
async def test_ac_semret_37_coverage():
    """AC-SEMRET-37: post-backfill, entities with summary_embedding IS NOT NULL ≥ 95%."""
    pytest.fail("Architect-verified in Phase 3")


# ============================================================
# QA Edge Cases — added by QA S08
# ============================================================


@pytest.mark.asyncio
async def test_qa_edge_empty_string_summary_needs_reembed():
    """QA: empty string summary (not null) → needs_reembed returns False (same as null per OQ-3)."""
    # Architect ruling: summary="" is treated as empty; no embed needed.
    service = EmbeddingService(MagicMock(), MagicMock())
    entity = _make_entity(summary="")
    assert service.needs_reembed(entity) is False


@pytest.mark.asyncio
async def test_qa_edge_empty_string_compute_and_store_writes_empty_sentinel():
    """QA: compute_and_store on entity with empty string summary writes EMPTY sentinel, returns True."""
    entity = _make_entity(summary="")

    repo = MagicMock()
    repo.get_by_id = AsyncMock(return_value=entity)
    repo.update_embedding = AsyncMock()

    llm = MagicMock()
    llm.embed = AsyncMock()  # must NOT be called

    service = EmbeddingService(repo, llm)
    result = await service.compute_and_store("entity-001")

    assert result is True
    llm.embed.assert_not_called()

    # Must write EMPTY sentinel
    repo.update_embedding.assert_called_once()
    call_args = repo.update_embedding.call_args.args
    entity_id_arg, vec_arg, model_arg, hash_arg = call_args
    assert hash_arg == EMPTY_HASH
    assert vec_arg is None


@pytest.mark.asyncio
async def test_qa_edge_compute_impact_chain_empty_intent():
    """QA: compute_impact_chain(intent='') treats empty string as no-intent (falls through to root-self or alphabetical)."""
    root_id = "root"
    entities = {
        root_id: _make_graph_entity(root_id, "Root"),
        "A": _make_graph_entity("A", "Alpha"),
        "B": _make_graph_entity("B", "Beta"),
    }
    rels = [
        _make_relationship(root_id, "A"),
        _make_relationship(root_id, "B"),
    ]

    # Root has no embedding; embeddings dict is empty
    embed_svc = MagicMock()
    embed_svc.embed_query = AsyncMock(return_value=_vec(0.5))

    svc = _build_ontology_service(entities, rels, embedding_service=embed_svc, embeddings={})

    # intent="" — empty string; EmbeddingService.embed_query would return None for empty strings
    # but we want to verify the intent="" path doesn't crash and uses alphabetical fallback
    embed_svc.embed_query = AsyncMock(return_value=None)  # empty string would return None from embed_query

    chain = await svc.compute_impact_chain(root_id, direction="forward", max_depth=2, intent="")

    # Should not raise
    assert isinstance(chain, list)
    # All hops should be present
    assert len(chain) == 2
    # With no usable query_vec, all fallback to null
    for hop in chain:
        assert "relevance_score" in hop


@pytest.mark.asyncio
async def test_qa_edge_search_all_unembedded_hybrid_no_crash():
    """QA: search hybrid mode when ALL entities have no embedding → must not crash, returns keyword-ranked results."""
    from zenos.application.knowledge.search_service import SearchService

    entities = [
        _make_search_entity("e1", "治理 Module", "governance audit"),
        _make_search_entity("e2", "Auth Module", "authentication module"),
        _make_search_entity("e3", "治理 Index", "index content"),
    ]

    repo = MagicMock()
    # search_by_vector returns empty (no embeddings in DB)
    repo.search_by_vector = AsyncMock(return_value=[])
    repo.list_all = AsyncMock(return_value=entities)

    embed_svc = MagicMock()
    query_vec = _fake_vec(768)
    embed_svc.embed_query = AsyncMock(return_value=query_vec)

    svc = SearchService(repo, embed_svc)

    results = await svc.search_entities("治理", mode="hybrid", limit=10)

    # Must not crash
    assert isinstance(results, list)

    # Keyword-matching entities (治理 in name) should rank above others due to keyword_boolean
    matched_ids = [r["_entity"].id for r in results]
    # e1 and e3 match "治理" keyword; e2 does not
    # Both e1 and e3 should appear, e2 should also appear with score=0
    assert "e1" in matched_ids
    assert "e3" in matched_ids

    # Entities with keyword match should appear; entities with no embedding AND no keyword match
    # may be absent (hybrid supplement path only adds kw>0 entities from list_all).
    # This is the documented S05 coverage gap: unembedded, non-keyword entities get score=0
    # and are dropped from the supplement path. Acceptable behavior — Architect aware.
    assert "e1" in matched_ids, "e1 (keyword match) must appear in hybrid results"
    assert "e3" in matched_ids, "e3 (keyword match) must appear in hybrid results"
    # e2 has no keyword match and no embedding → score=0, may be absent (known coverage gap)
    # Document: unembedded entities with no keyword match are invisible in hybrid mode
    # unless they are returned by search_by_vector.
    # Verify e1 and e3 rank before e2 IF e2 is present
    if "e2" in matched_ids:
        rank_e1 = matched_ids.index("e1")
        rank_e2 = matched_ids.index("e2")
        rank_e3 = matched_ids.index("e3")
        assert rank_e1 < rank_e2 or rank_e3 < rank_e2, (
            "Keyword-matching entities should rank above non-matching entity in hybrid mode"
        )

    # Score breakdown must be present on all results
    for r in results:
        assert "score_breakdown" in r
        assert "semantic" in r["score_breakdown"]
        assert "keyword" in r["score_breakdown"]


@pytest.mark.asyncio
async def test_qa_edge_get_include_all_passes_intent():
    """QA (S06 concern): get(include=['all'], intent='X', top_k_per_hop=3) must also pass intent+top_k through to compute_impact_chain."""
    import zenos.interface.mcp as _mcp_module
    from unittest.mock import AsyncMock, MagicMock, patch
    from zenos.domain.knowledge.models import Entity, Tags
    from zenos.application.knowledge.ontology_service import EntityWithRelationships

    fake_entity = Entity(
        id="entity-all-001",
        name="Entity All",
        type="module",
        summary="A test entity",
        tags=Tags(what=[], why="", how="", who=[]),
        status="active",
        confirmed_by_user=True,
        sources=[],
    )
    fake_ewr = EntityWithRelationships(entity=fake_entity, relationships=[])

    impact_chain_calls: list[dict] = []

    async def _spy_compute_impact_chain(eid: str, *, direction: str = "forward", **kwargs):
        impact_chain_calls.append({"eid": eid, "direction": direction, **kwargs})
        return []

    with (
        patch.object(_mcp_module, "ontology_service", MagicMock()) as mock_ont_svc,
        patch.object(_mcp_module, "entity_repo", MagicMock()),
        patch.object(_mcp_module, "relationship_repo", MagicMock()),
        patch.object(_mcp_module, "entry_repo", MagicMock()),
        patch("zenos.interface.mcp._ensure_services", new=AsyncMock()),
        patch("zenos.interface.mcp.get._current_partner") as mock_partner,
        patch("zenos.interface.mcp.get._is_entity_visible", return_value=True),
        patch("zenos.interface.mcp.get._schedule_tool_event"),
    ):
        mock_partner.get.return_value = {}
        mock_ont_svc.get_entity = AsyncMock(return_value=fake_ewr)
        mock_ont_svc.compute_impact_chain = _spy_compute_impact_chain
        _mcp_module.entity_repo.get_by_id = AsyncMock(return_value=None)
        _mcp_module.entry_repo.list_by_entity = AsyncMock(return_value=[])

        from zenos.interface.mcp.get import get as _get_tool

        resp = await _get_tool(
            collection="entities",
            name="Entity All",
            include=["all"],
            intent="治理",
            top_k_per_hop=5,
        )

    # compute_impact_chain must have been called with intent and top_k_per_hop
    assert len(impact_chain_calls) >= 1, "compute_impact_chain was not called for include=['all']"
    for call in impact_chain_calls:
        assert call.get("intent") == "治理", (
            f"include=['all'] path must pass intent to compute_impact_chain, got: {call}"
        )
        assert call.get("top_k_per_hop") == 5, (
            f"include=['all'] path must pass top_k_per_hop to compute_impact_chain, got: {call}"
        )


@pytest.mark.asyncio
async def test_qa_edge_direction_both_passes_intent():
    """QA (S04 concern): direction='both' must transparently pass intent/top_k_per_hop to both forward and reverse traversals."""
    root_id = "root"
    entities = {
        root_id: _make_graph_entity(root_id, "Root"),
        "fwd": _make_graph_entity("fwd", "Forward"),
        "rev": _make_graph_entity("rev", "Reverse"),
    }
    rels = [
        _make_relationship(root_id, "fwd"),   # forward
        _make_relationship("rev", root_id),    # reverse (rev → root)
    ]

    query_vec = _sparse_vec(1.0)
    embeddings = {
        root_id: query_vec,
        "fwd": _sparse_vec(0.8),
        "rev": _sparse_vec(0.6),
    }

    embed_svc = MagicMock()
    embed_svc.embed_query = AsyncMock(return_value=query_vec)

    svc = _build_ontology_service(entities, rels, embedding_service=embed_svc, embeddings=embeddings)

    chain = await svc.compute_impact_chain(
        root_id, direction="both", max_depth=2, intent="test intent", top_k_per_hop=3,
    )

    # Must not crash; must return results
    assert isinstance(chain, list)
    # Forward: fwd entity; Reverse: rev entity
    to_ids = {hop["to_id"] for hop in chain}
    assert "fwd" in to_ids, "forward direction should include 'fwd' entity"

    # Verify embed_query was called (intent path triggered)
    embed_svc.embed_query.assert_called()

    # All hops must have relevance_score field
    for hop in chain:
        assert "relevance_score" in hop
