"""
AC test stubs generated from SPEC-governance-task-link-resilience.
Auto-generated by Architect - Developer fills implementation.
Red = gap, Green = verified.
"""

import pytest

from zenos.application.knowledge import governance_ai
from zenos.application.knowledge.governance_ai import GovernanceAI, TaskLinkInference


def _entities(count: int) -> list[dict]:
    return [
        {
            "id": f"entity-{i}",
            "name": f"Entity {i}",
            "type": "module",
            "summary": f"Summary for entity {i}",
            "tags": {"what": [f"topic-{i}"]},
        }
        for i in range(count)
    ]


def _entity_line_count(messages: list[dict]) -> int:
    user_prompt = messages[1]["content"]
    entity_block = user_prompt.split("實體：\n", 1)[1]
    return len([line for line in entity_block.splitlines() if line.strip()])


class _RecordingLLM:
    model = "test-model"

    def __init__(self, responses):
        self._responses = list(responses)
        self.calls = []

    def chat_structured(self, **kwargs):
        self.calls.append(kwargs)
        response = self._responses.pop(0)
        if isinstance(response, Exception):
            raise response
        return response


@pytest.mark.spec("AC-GTLR-01")
def test_ac_gtlr_01_infer_task_links_chunks_large_candidate_sets():
    """AC-GTLR-01: Given existing_entities exceeds chunk limit, When inference runs, Then chat_structured is called per bounded chunk."""
    chunk_size = GovernanceAI.TASK_LINK_ENTITY_CHUNK_SIZE
    entities = _entities(chunk_size * 2 + 3)
    llm = _RecordingLLM(
        [
            TaskLinkInference(entity_ids=[]),
            TaskLinkInference(entity_ids=[]),
            TaskLinkInference(entity_ids=[]),
        ]
    )

    result = GovernanceAI(llm).infer_task_links(
        title="Task",
        description="Description",
        existing_entities=entities,
    )

    assert result == []
    assert len(llm.calls) == 3
    assert [_entity_line_count(call["messages"]) for call in llm.calls] == [
        chunk_size,
        chunk_size,
        3,
    ]


@pytest.mark.spec("AC-GTLR-02")
def test_ac_gtlr_02_partial_chunk_failure_keeps_successful_links():
    """AC-GTLR-02: Given one chunk fails and another succeeds, When inference completes, Then successful entity IDs are returned."""
    chunk_size = GovernanceAI.TASK_LINK_ENTITY_CHUNK_SIZE
    entities = _entities(chunk_size + 2)
    llm = _RecordingLLM(
        [
            RuntimeError("first chunk failed"),
            TaskLinkInference(entity_ids=["entity-26"]),
        ]
    )

    result = GovernanceAI(llm).infer_task_links(
        title="Task",
        description="Description",
        existing_entities=entities,
    )

    assert result == ["entity-26"]
    assert len(llm.calls) == 2


@pytest.mark.spec("AC-GTLR-03")
def test_ac_gtlr_03_all_chunks_fail_uses_keyword_fallback():
    """AC-GTLR-03: Given all LLM chunks fail but task text overlaps candidate entity text, When fallback runs, Then up to 3 deterministic candidate IDs are returned."""
    entities = [
        {"id": "e1", "name": "Billing Pipeline", "type": "module", "summary": ""},
        {"id": "e2", "name": "Billing Audit", "type": "module", "summary": ""},
        {"id": "e3", "name": "Billing Retry", "type": "module", "summary": ""},
        {"id": "e4", "name": "Billing Export", "type": "module", "summary": ""},
        {"id": "e5", "name": "Search Console", "type": "module", "summary": ""},
    ]
    llm = _RecordingLLM([RuntimeError("all chunks failed")])

    result = GovernanceAI(llm).infer_task_links(
        title="Fix billing retry audit",
        description="Billing pipeline retry behavior fails audit checks",
        existing_entities=entities,
    )

    assert result == ["e1", "e3", "e2"]
    assert len(result) <= 3
    assert set(result) <= {entity["id"] for entity in entities}


@pytest.mark.spec("AC-GTLR-03")
def test_ac_gtlr_03_all_chunks_fail_uses_cjk_keyword_fallback():
    """AC-GTLR-03: fallback handles conservative CJK overlap without relying on ASCII tokens."""
    entities = [
        {
            "id": "payment-flow",
            "name": "支付流程",
            "type": "module",
            "summary": "處理金流扣款、扣款重試與扣款失敗恢復",
            "tags": {"what": ["金流", "扣款", "重試"]},
        },
        {
            "id": "search",
            "name": "搜尋體驗",
            "type": "module",
            "summary": "處理全文檢索與排序",
            "tags": {"what": ["搜尋", "排序"]},
        },
        {
            "id": "profile",
            "name": "個人設定",
            "type": "module",
            "summary": "處理使用者偏好設定",
            "tags": {"what": ["使用者", "設定"]},
        },
    ]
    llm = _RecordingLLM([RuntimeError("all chunks failed")])

    result = GovernanceAI(llm).infer_task_links(
        title="修復金流扣款失敗問題",
        description="扣款重試邏輯異常，需要修正",
        existing_entities=entities,
    )

    assert result == ["payment-flow"]
    assert len(result) <= 3
    assert set(result) <= {entity["id"] for entity in entities}


@pytest.mark.spec("AC-GTLR-03")
def test_ac_gtlr_03_cjk_fallback_ignores_single_character_fields():
    """AC-GTLR-03: single-character CJK fields do not match solely by substring."""
    entities = [
        {
            "id": "single-gold",
            "name": "金",
            "type": "module",
            "summary": "金",
            "tags": {"what": ["金"]},
        },
        {
            "id": "finance",
            "name": "金融",
            "type": "module",
            "summary": "金融交易",
            "tags": {"what": ["金融"]},
        },
        {
            "id": "cashflow",
            "name": "金流",
            "type": "module",
            "summary": "金流處理",
            "tags": {"what": ["金流"]},
        },
    ]
    llm = _RecordingLLM([RuntimeError("all chunks failed")])

    result = GovernanceAI(llm).infer_task_links(
        title="修復金流問題",
        description="金流流程需要修正",
        existing_entities=entities,
    )

    assert "single-gold" not in result
    assert result == ["cashflow"]
    assert len(result) <= 3
    assert set(result) <= {entity["id"] for entity in entities}


@pytest.mark.spec("AC-GTLR-04")
def test_ac_gtlr_04_filters_unknown_and_duplicate_entity_ids():
    """AC-GTLR-04: Given LLM returns duplicate or unknown IDs, When results are merged, Then output is unique, ordered, and only known IDs."""
    entities = _entities(3)
    llm = _RecordingLLM(
        [
            TaskLinkInference(
                entity_ids=["entity-1", "missing", "entity-1", "entity-2"]
            )
        ]
    )

    result = GovernanceAI(llm).infer_task_links(
        title="Task",
        description="Description",
        existing_entities=entities,
    )

    assert result == ["entity-1", "entity-2"]


@pytest.mark.spec("AC-GTLR-05")
def test_ac_gtlr_05_audit_includes_chunk_failure_and_fallback_summary(monkeypatch):
    """AC-GTLR-05: Given chunk failure or fallback occurs, When audit emits, Then payload includes model, task_title, candidate count, chunk count, failed chunk count, and fallback_used."""
    captured = []
    monkeypatch.setattr(
        governance_ai,
        "_audit_governance",
        lambda event_type, payload: captured.append((event_type, payload)),
    )
    entities = [
        {"id": "billing", "name": "Billing Pipeline", "type": "module"},
    ]
    llm = _RecordingLLM([RuntimeError("all chunks failed")])

    result = GovernanceAI(llm).infer_task_links(
        title="Fix Billing Pipeline",
        description="Billing work",
        existing_entities=entities,
    )

    assert result == ["billing"]
    assert captured
    payload = captured[-1][1]
    assert payload["model"] == "test-model"
    assert payload["task_title"] == "Fix Billing Pipeline"
    assert payload["candidate_entities_count"] == 1
    assert payload["chunk_count"] == 1
    assert payload["failed_chunk_count"] == 1
    assert payload["fallback_used"] is True
