"""AC test stubs generated from SPEC-task-governance §2026-04-22 Task Ownership SSOT 收斂.

Auto-generated by Architect (ADR-044) — Developer fills implementation.
Red = gap, Green = verified.

Coverage matrix:
  - AC-TOSC-01..04: Schema / Migration
  - AC-TOSC-05..11: Server Validation
  - AC-TOSC-12..15: Write Path
  - AC-TOSC-16..18: Read Path
  - AC-TOSC-19..20: Frontend (covered in test_task_ownership_ssot_ac.test.tsx)
  - AC-TOSC-21..22: Deprecation
  - AC-TOSC-23..25: Documentation / Governance SSOT sync
"""
import pytest

pytestmark = pytest.mark.skip(
    reason="Draft AC stubs for task_ownership_ssot; enable when implementation starts."
)


# ─────────────────────────────────────────────────────────
# P0 Schema / Migration
# ─────────────────────────────────────────────────────────


@pytest.mark.spec("AC-TOSC-01")
async def test_ac_tosc_01_tasks_product_id_column_exists():
    """AC-TOSC-01: migration 完成後，tasks.product_id 欄位存在（取代 project_id），
    有 idx_tasks_partner_product_id index 與 FK to entities(partner_id, id)."""
    pytest.fail("NOT IMPLEMENTED — Developer must fill this test")


@pytest.mark.spec("AC-TOSC-02")
async def test_ac_tosc_02_plans_product_id_column_exists():
    """AC-TOSC-02: plans.product_id 同 AC-TOSC-01 完成改名，FK 與 index 對齊."""
    pytest.fail("NOT IMPLEMENTED — Developer must fill this test")


@pytest.mark.spec("AC-TOSC-03")
async def test_ac_tosc_03_zero_null_after_backfill():
    """AC-TOSC-03: migration 完成後，SELECT COUNT(*) FROM tasks WHERE product_id IS NULL = 0,
    且所有兜底 task 有 governance:review_product_assignment tag."""
    pytest.fail("NOT IMPLEMENTED — Developer must fill this test")


@pytest.mark.spec("AC-TOSC-04")
async def test_ac_tosc_04_not_null_constraint_enforced():
    """AC-TOSC-04: tasks.product_id 與 plans.product_id 加上 NOT NULL constraint,
    違反時 DB 直接 reject."""
    pytest.fail("NOT IMPLEMENTED — Developer must fill this test")


# ─────────────────────────────────────────────────────────
# P0 Server Validation
# ─────────────────────────────────────────────────────────


@pytest.mark.spec("AC-TOSC-05")
async def test_ac_tosc_05_missing_product_id_rejected():
    """AC-TOSC-05: task(action="create") / write(collection="tasks") 沒傳 product_id,
    且 partner.defaultProject 解析無結果時, reject MISSING_PRODUCT_ID."""
    pytest.fail("NOT IMPLEMENTED — Developer must fill this test")


@pytest.mark.spec("AC-TOSC-06")
async def test_ac_tosc_06_invalid_product_id_rejected():
    """AC-TOSC-06: product_id 指向不存在 entity 或 type ≠ product 的 entity 時,
    reject INVALID_PRODUCT_ID."""
    pytest.fail("NOT IMPLEMENTED — Developer must fill this test")


@pytest.mark.spec("AC-TOSC-07")
async def test_ac_tosc_07_linked_entities_product_stripped():
    """AC-TOSC-07: linked_entities 含 type=product entity 時, server strip 並回傳
    warning LINKED_ENTITIES_PRODUCT_STRIPPED, DB 不會寫入該關聯."""
    pytest.fail("NOT IMPLEMENTED — Developer must fill this test")


@pytest.mark.spec("AC-TOSC-08")
async def test_ac_tosc_08_project_string_ignored_with_warning():
    """AC-TOSC-08: 同時傳 project 字串與 product_id 且 product entity.name ≠ project 字串時,
    以 product_id 為準並回傳 warning PROJECT_STRING_IGNORED."""
    pytest.fail("NOT IMPLEMENTED — Developer must fill this test")


@pytest.mark.spec("AC-TOSC-09")
async def test_ac_tosc_09_cross_product_subtask_rejected():
    """AC-TOSC-09: subtask 的 product_id ≠ parent task product_id 時,
    reject CROSS_PRODUCT_SUBTASK."""
    pytest.fail("NOT IMPLEMENTED — Developer must fill this test")


@pytest.mark.spec("AC-TOSC-10")
async def test_ac_tosc_10_cross_product_plan_task_rejected():
    """AC-TOSC-10: task 有 plan_id 且 task.product_id ≠ plan.product_id 時,
    reject CROSS_PRODUCT_PLAN_TASK."""
    pytest.fail("NOT IMPLEMENTED — Developer must fill this test")


@pytest.mark.spec("AC-TOSC-11")
async def test_ac_tosc_11_default_project_fallback_resolves():
    """AC-TOSC-11: caller 沒傳 product_id 但 partner.defaultProject 解析成功時,
    server 自動填入並回傳 task; audit log 記錄 auto_resolved_product_id."""
    pytest.fail("NOT IMPLEMENTED — Developer must fill this test")


# ─────────────────────────────────────────────────────────
# P0 Write Path
# ─────────────────────────────────────────────────────────


@pytest.mark.spec("AC-TOSC-12")
async def test_ac_tosc_12_mcp_task_create_update_accepts_product_id():
    """AC-TOSC-12: MCP task(action="create", product_id=...) 接受參數並寫入 DB;
    task(action="update", id=..., product_id=...) 同樣可用."""
    pytest.fail("NOT IMPLEMENTED — Developer must fill this test")


@pytest.mark.spec("AC-TOSC-13")
async def test_ac_tosc_13_mcp_plan_create_accepts_product_id():
    """AC-TOSC-13: MCP plan(action="create", product_id=...) 已存在,
    verify 改名後仍可用, 且加上 type validation."""
    pytest.fail("NOT IMPLEMENTED — Developer must fill this test")


@pytest.mark.spec("AC-TOSC-14")
async def test_ac_tosc_14_dashboard_api_accepts_product_id():
    """AC-TOSC-14: Dashboard POST /api/data/tasks 接受 body 內 product_id 並寫入;
    PATCH /api/data/tasks/{id} 同樣可用."""
    pytest.fail("NOT IMPLEMENTED — Developer must fill this test")


@pytest.mark.spec("AC-TOSC-15")
async def test_ac_tosc_15_ext_ingestion_accepts_product_id():
    """AC-TOSC-15: ext_ingestion_api 的 task 寫入路徑接受並驗證 product_id."""
    pytest.fail("NOT IMPLEMENTED — Developer must fill this test")


# ─────────────────────────────────────────────────────────
# P0 Read Path
# ─────────────────────────────────────────────────────────


@pytest.mark.spec("AC-TOSC-16")
async def test_ac_tosc_16_list_tasks_by_entity_uses_product_id_for_product():
    """AC-TOSC-16: GET /api/data/tasks/by-entity/{entityId} 當 entity.type=product 時走
    WHERE product_id = $entityId; 當 entity.type 為其他 (goal / module) 時走
    task_entities join."""
    pytest.fail("NOT IMPLEMENTED — Developer must fill this test")


@pytest.mark.spec("AC-TOSC-17")
async def test_ac_tosc_17_search_uses_product_id_only():
    """AC-TOSC-17: MCP search(tasks, product_id=X) 純走 product_id 欄位,
    不再 fallback project 字串 match."""
    pytest.fail("NOT IMPLEMENTED — Developer must fill this test")


# AC-TOSC-18 covered in frontend test (test_task_ownership_ssot_ac.test.tsx)


# ─────────────────────────────────────────────────────────
# P1 Deprecation / Governance SSOT sync
# ─────────────────────────────────────────────────────────


@pytest.mark.spec("AC-TOSC-21")
async def test_ac_tosc_21_project_string_write_ignored():
    """AC-TOSC-21: caller 寫入 project 字串欄位被 server ignore 並回傳 warning
    PROJECT_STRING_IGNORED; DB 內 project 字串由 server 從 product entity.name 自動派生."""
    pytest.fail("NOT IMPLEMENTED — Developer must fill this test")


@pytest.mark.spec("AC-TOSC-22")
async def test_ac_tosc_22_governance_rules_runtime_ssot_synced():
    """AC-TOSC-22: src/zenos/interface/governance_rules.py["task"] runtime SSOT 同步加上
    三條繩子原則 + 七條 server validation 規則 (AC-TOSC-05..11) 的 level 2 內容."""
    pytest.fail("NOT IMPLEMENTED — Developer must fill this test")


# ─────────────────────────────────────────────────────────
# P0 Documentation / Governance Guide
# ─────────────────────────────────────────────────────────


@pytest.mark.spec("AC-TOSC-23")
async def test_ac_tosc_23_governance_guide_returns_ssot_rules():
    """AC-TOSC-23: governance_guide(topic="task", level=2) 回傳內容包含三條繩子原則
    與七條 validation 規則."""
    pytest.fail("NOT IMPLEMENTED — Developer must fill this test")


# AC-TOSC-24 / AC-TOSC-25 are documentation-only (verified by Architect review,
# not automated — included here for matrix completeness).
