"""
AC test stubs generated from SPEC-mcp-opt-in-include (ADR-040 Phase A).
Auto-generated by Architect — Developer fills implementation.
Red = gap, Green = verified.

Run: .venv/bin/pytest tests/spec_compliance/test_mcp_opt_in_include_ac.py -x
"""
from __future__ import annotations

import json
import logging
from datetime import datetime, timezone
from unittest.mock import AsyncMock, patch

import pytest

from zenos.application.knowledge.ontology_service import EntityWithRelationships
from zenos.domain.knowledge import Entity, EntityEntry, Relationship, Tags


# ---------------------------------------------------------------------------
# Helpers: shared mock setup
# ---------------------------------------------------------------------------


def _make_entity(
    eid: str = "ent-1",
    name: str = "Paceriz",
    summary: str = "A running coach app for athletes",
    sources: list | None = None,
    tags: Tags | None = None,
    **overrides,
) -> Entity:
    return Entity(
        id=eid,
        name=name,
        type="product",
        level=1,
        status="active",
        summary=summary,
        tags=tags or Tags(what=["app"], why="coaching", how="AI", who=["runners"]),
        confirmed_by_user=True,
        owner="Barry",
        parent_id=None,
        sources=sources if sources is not None else [],
        visibility="public",
        created_at=datetime(2026, 1, 1, tzinfo=timezone.utc),
        updated_at=datetime(2026, 3, 1, tzinfo=timezone.utc),
        **overrides,
    )


def _make_relationship(
    source_id: str = "ent-1",
    target_id: str = "ent-2",
    rel_type: str = "impacts",
    description: str = "Paceriz impacts users",
) -> Relationship:
    return Relationship(
        id="rel-1",
        source_entity_id=source_id,
        target_id=target_id,
        type=rel_type,
        description=description,
    )


def _make_entry(entity_id: str = "ent-1", content: str = "We decided X") -> EntityEntry:
    return EntityEntry(
        id="entry-1",
        partner_id="p1",
        entity_id=entity_id,
        type="decision",
        content=content,
        status="active",
        created_at=datetime(2026, 3, 1, tzinfo=timezone.utc),
    )


def _ok_data(result: dict) -> dict:
    assert result["status"] == "ok", f"Expected status=ok, got: {result}"
    return result["data"]


def _mock_get_bootstrap(ontology_service=None, entity_repo=None, entry_repo=None,
                         relationship_repo=None):
    """Return a context-manager stack for get tool mocking."""
    patches = [
        patch("zenos.interface.mcp._ensure_services", new=AsyncMock(return_value=None)),
    ]
    if ontology_service is not None:
        patches.append(patch("zenos.interface.mcp.ontology_service", new=ontology_service))
    if entity_repo is not None:
        patches.append(patch("zenos.interface.mcp.entity_repo", new=entity_repo))
    if entry_repo is not None:
        patches.append(patch("zenos.interface.mcp.entry_repo", new=entry_repo))
    if relationship_repo is not None:
        patches.append(patch("zenos.interface.mcp.relationship_repo", new=relationship_repo))
    return patches


# ---------------------------------------------------------------------------
# Shared context manager helper to avoid deep nesting
# ---------------------------------------------------------------------------

from contextlib import ExitStack


async def _call_get(patches: list, **kwargs) -> dict:
    from zenos.interface.mcp.get import get
    with ExitStack() as stack:
        for p in patches:
            stack.enter_context(p)
        return await get(**kwargs)


async def _call_search(patches: list, **kwargs) -> dict:
    from zenos.interface.mcp.search import search
    with ExitStack() as stack:
        for p in patches:
            stack.enter_context(p)
        return await search(**kwargs)


# --- R1: get(collection="entities") include 参数 ---

@pytest.mark.spec("AC-MCPINC-01")
@pytest.mark.asyncio
async def test_ac_mcpinc_01_get_no_include_eager_dump_with_warning():
    """AC-MCPINC-01: get(no include) → eager dump payload + deprecation warning."""
    entity = _make_entity(sources=[{"uri": "https://example.com"}])
    rel = _make_relationship()
    ewr = EntityWithRelationships(entity=entity, relationships=[rel])
    entry = _make_entry()

    mock_os = AsyncMock()
    mock_os.get_entity = AsyncMock(return_value=ewr)
    mock_os.compute_impact_chain = AsyncMock(return_value=[])
    mock_er = AsyncMock()
    mock_er.get_by_id = AsyncMock(return_value=_make_entity(eid="ent-2"))
    mock_entry = AsyncMock()
    mock_entry.list_by_entity = AsyncMock(return_value=[entry])

    patches = _mock_get_bootstrap(
        ontology_service=mock_os,
        entity_repo=mock_er,
        entry_repo=mock_entry,
    )

    with patch("zenos.interface.mcp._include.logger") as mock_logger:
        result = await _call_get(patches, collection="entities", name="Paceriz")

    data = _ok_data(result)

    # Must have entity nested under "entity" key (legacy structure)
    assert "entity" in data
    assert data["entity"]["name"] == "Paceriz"

    # Must have all eager-dump fields
    assert "outgoing_relationships" in data
    assert "incoming_relationships" in data
    assert "active_entries" in data
    assert "impact_chain" in data
    assert "reverse_impact_chain" in data

    # Must have emitted deprecation warning
    mock_logger.warning.assert_called_once()
    warning_body = json.loads(mock_logger.warning.call_args[0][0])
    assert "caller not using include, defaulting to full payload" in warning_body["message"]
    assert "Phase B" in warning_body["message"]
    assert warning_body["tool"] == "get"


@pytest.mark.spec("AC-MCPINC-02")
@pytest.mark.asyncio
async def test_ac_mcpinc_02_get_summary_only():
    """AC-MCPINC-02: get(include=["summary"]) → entity body + source_count only, no warning."""
    entity = _make_entity(sources=[{"uri": "https://a.com"}, {"uri": "https://b.com"}])
    ewr = EntityWithRelationships(entity=entity, relationships=[])

    mock_os = AsyncMock()
    mock_os.get_entity = AsyncMock(return_value=ewr)
    mock_entry = AsyncMock()
    mock_entry.list_by_entity = AsyncMock(return_value=[])

    patches = _mock_get_bootstrap(ontology_service=mock_os, entry_repo=mock_entry)

    with patch("zenos.interface.mcp._include.logger") as mock_logger:
        result = await _call_get(patches, collection="entities", name="Paceriz", include=["summary"])

    data = _ok_data(result)

    # Must have entity core fields
    assert data["id"] == "ent-1"
    assert data["name"] == "Paceriz"
    assert data["type"] == "product"
    assert data["level"] == 1
    assert data["status"] == "active"
    assert data["summary"] == entity.summary
    assert "tags" in data
    assert data["owner"] == "Barry"
    assert data["confirmed_by_user"] is True
    assert data["parent_id"] is None
    # Must have source_count (integer), not sources array
    assert data["source_count"] == 2
    # Must NOT have heavy fields
    assert "sources" not in data
    assert "outgoing_relationships" not in data
    assert "incoming_relationships" not in data
    assert "active_entries" not in data
    assert "impact_chain" not in data
    assert "reverse_impact_chain" not in data
    # Must NOT log deprecation warning
    mock_logger.warning.assert_not_called()


@pytest.mark.spec("AC-MCPINC-03")
@pytest.mark.asyncio
async def test_ac_mcpinc_03_get_summary_plus_relationships():
    """AC-MCPINC-03: get(include=["summary","relationships"]) → +outgoing/incoming."""
    entity = _make_entity()
    entity2 = _make_entity(eid="ent-2", name="ZenOS")
    rel_out = _make_relationship(source_id="ent-1", target_id="ent-2")
    rel_in = _make_relationship(source_id="ent-2", target_id="ent-1", description="reverse")
    ewr = EntityWithRelationships(entity=entity, relationships=[rel_out, rel_in])

    mock_os = AsyncMock()
    mock_os.get_entity = AsyncMock(return_value=ewr)
    mock_er = AsyncMock()
    mock_er.get_by_id = AsyncMock(return_value=entity2)
    mock_entry = AsyncMock()
    mock_entry.list_by_entity = AsyncMock(return_value=[])

    patches = _mock_get_bootstrap(ontology_service=mock_os, entity_repo=mock_er, entry_repo=mock_entry)
    result = await _call_get(patches, collection="entities", name="Paceriz", include=["summary", "relationships"])

    data = _ok_data(result)
    assert "outgoing_relationships" in data
    assert "incoming_relationships" in data
    assert len(data["outgoing_relationships"]) == 1
    assert len(data["incoming_relationships"]) == 1
    # Relationships contain complete description
    assert data["outgoing_relationships"][0]["description"] == "Paceriz impacts users"
    # source_count still present (summary baseline)
    assert "source_count" in data


@pytest.mark.spec("AC-MCPINC-04")
@pytest.mark.asyncio
async def test_ac_mcpinc_04_get_summary_plus_entries_limit_5():
    """AC-MCPINC-04: get(include=["summary","entries"]) → active_entries, limit=5, updated_at DESC."""
    entity = _make_entity()
    ewr = EntityWithRelationships(entity=entity, relationships=[])

    # Make 8 entries with varying updated_at; newest should be first after sort
    entries = []
    for i in range(8):
        e = EntityEntry(
            id=f"entry-{i}",
            partner_id="p1",
            entity_id="ent-1",
            type="decision",
            content=f"Decision {i}",
            status="active",
            created_at=datetime(2026, 1, i + 1, tzinfo=timezone.utc),
        )
        entries.append(e)
    # Shuffle to ensure sorting is tested
    entries_shuffled = [entries[3], entries[7], entries[0], entries[5], entries[2], entries[6], entries[1], entries[4]]

    mock_os = AsyncMock()
    mock_os.get_entity = AsyncMock(return_value=ewr)
    mock_entry = AsyncMock()
    mock_entry.list_by_entity = AsyncMock(return_value=entries_shuffled)

    patches = _mock_get_bootstrap(ontology_service=mock_os, entry_repo=mock_entry)
    result = await _call_get(patches, collection="entities", name="Paceriz", include=["summary", "entries"])

    data = _ok_data(result)
    assert "active_entries" in data
    assert len(data["active_entries"]) == 5  # limit enforced


@pytest.mark.spec("AC-MCPINC-05")
@pytest.mark.asyncio
async def test_ac_mcpinc_05_get_summary_plus_impact_chain():
    """AC-MCPINC-05: get(include=["summary","impact_chain"]) → +impact_chain + reverse_impact_chain."""
    entity = _make_entity()
    ewr = EntityWithRelationships(entity=entity, relationships=[])
    fwd_chain = [{"entity_id": "ent-x", "entity_name": "Module X", "depth": 1}]
    rev_chain = [{"entity_id": "ent-y", "entity_name": "Module Y", "depth": 1}]

    mock_os = AsyncMock()
    mock_os.get_entity = AsyncMock(return_value=ewr)
    mock_os.compute_impact_chain = AsyncMock(side_effect=lambda eid, direction: (
        fwd_chain if direction == "forward" else rev_chain
    ))
    mock_entry = AsyncMock()
    mock_entry.list_by_entity = AsyncMock(return_value=[])

    patches = _mock_get_bootstrap(ontology_service=mock_os, entry_repo=mock_entry)
    result = await _call_get(patches, collection="entities", name="Paceriz", include=["summary", "impact_chain"])

    data = _ok_data(result)
    assert data["impact_chain"] == fwd_chain
    assert data["reverse_impact_chain"] == rev_chain
    assert "source_count" in data


@pytest.mark.spec("AC-MCPINC-06")
@pytest.mark.asyncio
async def test_ac_mcpinc_06_get_summary_plus_sources_array():
    """AC-MCPINC-06: get(include=["summary","sources"]) → full sources array, no source_count."""
    sources_data = [{"uri": "https://a.com", "label": "doc A"}, {"uri": "https://b.com", "label": "doc B"}]
    entity = _make_entity(sources=sources_data)
    ewr = EntityWithRelationships(entity=entity, relationships=[])

    mock_os = AsyncMock()
    mock_os.get_entity = AsyncMock(return_value=ewr)
    mock_entry = AsyncMock()
    mock_entry.list_by_entity = AsyncMock(return_value=[])

    patches = _mock_get_bootstrap(ontology_service=mock_os, entry_repo=mock_entry)
    result = await _call_get(patches, collection="entities", name="Paceriz", include=["summary", "sources"])

    data = _ok_data(result)
    assert "sources" in data
    assert len(data["sources"]) == 2
    assert data["sources"][0]["uri"] == "https://a.com"
    # source_count must be absent when sources array is present
    assert "source_count" not in data


@pytest.mark.spec("AC-MCPINC-07")
@pytest.mark.asyncio
async def test_ac_mcpinc_07_get_include_all_eager_no_warning():
    """AC-MCPINC-07: get(include=["all"]) → eager dump, no deprecation warning."""
    entity = _make_entity(sources=[{"uri": "https://example.com"}])
    rel = _make_relationship()
    ewr = EntityWithRelationships(entity=entity, relationships=[rel])
    entry = _make_entry()

    mock_os = AsyncMock()
    mock_os.get_entity = AsyncMock(return_value=ewr)
    mock_os.compute_impact_chain = AsyncMock(return_value=[])
    mock_er = AsyncMock()
    mock_er.get_by_id = AsyncMock(return_value=_make_entity(eid="ent-2"))
    mock_entry = AsyncMock()
    mock_entry.list_by_entity = AsyncMock(return_value=[entry])

    patches = _mock_get_bootstrap(ontology_service=mock_os, entity_repo=mock_er, entry_repo=mock_entry)

    with patch("zenos.interface.mcp._include.logger") as mock_logger:
        result = await _call_get(patches, collection="entities", name="Paceriz", include=["all"])

    data = _ok_data(result)

    # Must have all eager-dump fields (same structure as AC-01)
    assert "entity" in data
    assert "outgoing_relationships" in data
    assert "incoming_relationships" in data
    assert "active_entries" in data
    assert "impact_chain" in data
    assert "reverse_impact_chain" in data

    # Must NOT log deprecation warning
    mock_logger.warning.assert_not_called()


@pytest.mark.spec("AC-MCPINC-08")
@pytest.mark.asyncio
async def test_ac_mcpinc_08_get_unknown_include_rejected():
    """AC-MCPINC-08: get(include=["xyz"]) → structured error with supported values."""
    patches = [
        patch("zenos.interface.mcp._ensure_services", new=AsyncMock(return_value=None)),
        patch("zenos.interface.mcp.ontology_service", new=AsyncMock()),
    ]
    result = await _call_get(patches, collection="entities", name="Paceriz", include=["xyz"])

    assert result["status"] == "rejected"
    assert result["data"]["error"] == "INVALID_INCLUDE"
    # Error message must list supported values
    message = result["data"]["message"]
    for v in ["summary", "relationships", "entries", "impact_chain", "sources", "all"]:
        assert v in message


@pytest.mark.spec("AC-MCPINC-09")
@pytest.mark.asyncio
async def test_ac_mcpinc_09_get_non_entity_collection_include_ignored():
    """AC-MCPINC-09: get(collection≠entities, include=[...]) → include ignored, no warning."""
    from zenos.domain.action import Task

    task = Task(
        id="task-1",
        title="Fix login",
        status="todo",
        priority="high",
        created_by="architect",
        description="desc",
        assignee="developer",
        created_at=datetime(2026, 1, 1, tzinfo=timezone.utc),
        updated_at=datetime(2026, 1, 2, tzinfo=timezone.utc),
    )

    mock_ts = AsyncMock()
    mock_ts.get_task_enriched = AsyncMock(return_value=(task, {}))
    mock_ts.enrich_task = AsyncMock(return_value={"expanded_entities": []})

    patches = [
        patch("zenos.interface.mcp._ensure_services", new=AsyncMock(return_value=None)),
        patch("zenos.interface.mcp.task_service", new=mock_ts),
    ]

    with patch("zenos.interface.mcp._include.logger") as mock_logger:
        result = await _call_get(patches, collection="tasks", id="task-1", include=["summary", "relationships"])

    # include is ignored — should return normal task payload
    assert result["status"] == "ok"
    assert result["data"]["title"] == "Fix login"
    # No deprecation warning for non-entity collections
    mock_logger.warning.assert_not_called()


# --- R2: search(collection="entities") include 参数 ---

@pytest.mark.spec("AC-MCPINC-10")
@pytest.mark.asyncio
async def test_ac_mcpinc_10_search_no_include_eager_dump_with_warning():
    """AC-MCPINC-10: search(no include) on entities → eager dump + warning (once per call)."""
    entity = _make_entity()

    mock_os = AsyncMock()
    mock_os.list_entities = AsyncMock(return_value=[entity])

    patches = [
        patch("zenos.interface.mcp._ensure_services", new=AsyncMock(return_value=None)),
        patch("zenos.interface.mcp.ontology_service", new=mock_os),
    ]

    with patch("zenos.interface.mcp._include.logger") as mock_logger:
        result = await _call_search(patches, collection="entities")

    data = _ok_data(result)
    assert "entities" in data
    assert len(data["entities"]) == 1

    # Eager dump: each entity has all fields (not just summary shape)
    entity_item = data["entities"][0]
    assert "id" in entity_item
    assert "summary" in entity_item
    assert "tags" in entity_item  # present in full serialize
    assert "sources" in entity_item

    # Must log deprecation warning exactly once per call (not per-result)
    mock_logger.warning.assert_called_once()
    warning_body = json.loads(mock_logger.warning.call_args[0][0])
    assert warning_body["tool"] == "search"
    assert warning_body["collection"] == "entities"


@pytest.mark.spec("AC-MCPINC-11")
@pytest.mark.asyncio
async def test_ac_mcpinc_11_search_summary_shape():
    """AC-MCPINC-11: search(include=["summary"]) → summary shape + summary_short ≤120 codepoints."""
    long_summary = "A" * 130  # 130 codepoints → must be truncated
    entity = _make_entity(summary=long_summary, sources=[{"uri": "https://x.com"}])
    entity_short = _make_entity(eid="ent-2", summary="Short")

    mock_os = AsyncMock()
    mock_os.list_entities = AsyncMock(return_value=[entity, entity_short])

    patches = [
        patch("zenos.interface.mcp._ensure_services", new=AsyncMock(return_value=None)),
        patch("zenos.interface.mcp.ontology_service", new=mock_os),
    ]
    result = await _call_search(patches, collection="entities", include=["summary"])

    data = _ok_data(result)
    items = data["entities"]
    assert len(items) == 2

    # Check summary shape: exactly {id, name, type, level, summary_short, score}
    long_item = items[0]
    expected_keys = {"id", "name", "type", "level", "summary_short", "score"}
    assert set(long_item.keys()) == expected_keys
    # summary_short must be ≤ 121 codepoints (120 + ellipsis)
    assert long_item["summary_short"].endswith("…")
    assert len(long_item["summary_short"]) == 121
    # Must NOT have forbidden fields
    assert "tags" not in long_item
    assert "sources" not in long_item
    assert "status" not in long_item
    assert "owner" not in long_item

    short_item = items[1]
    assert short_item["summary_short"] == "Short"
    assert not short_item["summary_short"].endswith("…")


@pytest.mark.spec("AC-MCPINC-12")
@pytest.mark.asyncio
async def test_ac_mcpinc_12_search_summary_plus_tags():
    """AC-MCPINC-12: search(include=["summary","tags"]) → summary shape + tags."""
    entity = _make_entity()

    mock_os = AsyncMock()
    mock_os.list_entities = AsyncMock(return_value=[entity])

    patches = [
        patch("zenos.interface.mcp._ensure_services", new=AsyncMock(return_value=None)),
        patch("zenos.interface.mcp.ontology_service", new=mock_os),
    ]
    result = await _call_search(patches, collection="entities", include=["summary", "tags"])

    data = _ok_data(result)
    item = data["entities"][0]
    assert "tags" in item
    assert "summary_short" in item
    assert "sources" not in item
    assert "status" not in item


@pytest.mark.spec("AC-MCPINC-13")
@pytest.mark.asyncio
async def test_ac_mcpinc_13_search_include_full_eager_no_warning():
    """AC-MCPINC-13: search(include=["full"]) → full payload, no warning."""
    entity = _make_entity(sources=[{"uri": "https://x.com"}])

    mock_os = AsyncMock()
    mock_os.list_entities = AsyncMock(return_value=[entity])

    patches = [
        patch("zenos.interface.mcp._ensure_services", new=AsyncMock(return_value=None)),
        patch("zenos.interface.mcp.ontology_service", new=mock_os),
    ]

    with patch("zenos.interface.mcp._include.logger") as mock_logger:
        result = await _call_search(patches, collection="entities", include=["full"])

    data = _ok_data(result)
    item = data["entities"][0]
    # Full serialize: should have all entity fields including sources
    assert "sources" in item
    assert "id" in item
    assert "summary" in item

    # Must NOT log deprecation warning
    mock_logger.warning.assert_not_called()


@pytest.mark.spec("AC-MCPINC-14")
@pytest.mark.asyncio
async def test_ac_mcpinc_14_search_unknown_include_rejected():
    """AC-MCPINC-14: search(include=["xyz"]) → error with supported values."""
    patches = [
        patch("zenos.interface.mcp._ensure_services", new=AsyncMock(return_value=None)),
    ]
    result = await _call_search(patches, collection="entities", include=["xyz"])

    assert result["status"] == "rejected"
    assert result["data"]["error"] == "INVALID_INCLUDE"
    message = result["data"]["message"]
    for v in ["summary", "tags", "full"]:
        assert v in message


@pytest.mark.spec("AC-MCPINC-15")
@pytest.mark.asyncio
async def test_ac_mcpinc_15_search_non_entity_collection_include_ignored():
    """AC-MCPINC-15: search(collection≠entities, include=[...]) → include ignored, no warning."""
    from zenos.domain.action import Task

    task = Task(
        id="task-1",
        title="Fix login",
        status="todo",
        priority="high",
        created_by="architect",
        description="desc",
        assignee="developer",
        created_at=datetime(2026, 1, 1, tzinfo=timezone.utc),
        updated_at=datetime(2026, 1, 2, tzinfo=timezone.utc),
    )

    mock_ts = AsyncMock()
    mock_ts.list_tasks = AsyncMock(return_value=[task])
    mock_ts.enrich_task = AsyncMock(return_value={"expanded_entities": []})

    patches = [
        patch("zenos.interface.mcp._ensure_services", new=AsyncMock(return_value=None)),
        patch("zenos.interface.mcp.task_service", new=mock_ts),
    ]

    with patch("zenos.interface.mcp._include.logger") as mock_logger:
        result = await _call_search(patches, collection="tasks", include=["summary"])

    assert result["status"] == "ok"
    assert "tasks" in result["data"]
    # include was ignored — no warning
    mock_logger.warning.assert_not_called()


# --- R3: Dashboard REST 路徑不受影響 ---

@pytest.mark.spec("AC-MCPINC-16")
@pytest.mark.asyncio
async def test_ac_mcpinc_16_dashboard_rest_payload_fields_unchanged():
    """AC-MCPINC-16: Dashboard REST GET /api/data/entities/{id} response fields unchanged.

    We call the dashboard REST handler directly (not via HTTP) and assert that:
    - The response body contains "entity" key with expected field set
    - The response body contains "impact_chain" and "reverse_impact_chain"
    - The entity sub-dict includes "sources" array

    No MCP code is involved in this path — this verifies zero cross-contamination.
    """
    import json as _json
    from zenos.interface.dashboard_api import get_entity
    from unittest.mock import MagicMock

    entity = Entity(
        id="ent-dashboard-1",
        name="Dashboard Test Entity",
        type="module",
        level=2,
        parent_id=None,
        status="active",
        summary="Dashboard entity",
        tags=Tags(what=["ui"], why="testing", how="REST", who=["qa"]),
        confirmed_by_user=True,
        owner="Barry",
        sources=[{"uri": "https://example.com", "label": "docs"}],
        visibility="public",
        created_at=datetime(2026, 1, 1, tzinfo=timezone.utc),
        updated_at=datetime(2026, 1, 2, tzinfo=timezone.utc),
    )

    fwd_chain = [{"entity_id": "ent-x", "entity_name": "X", "depth": 1}]
    rev_chain = [{"entity_id": "ent-y", "entity_name": "Y", "depth": 1}]

    _PARTNER = {
        "id": "p1",
        "email": "test@test.com",
        "displayName": "Test",
        "apiKey": "key-123",  # pragma: allowlist secret
        "authorizedEntityIds": [],
        "status": "active",
        "accessMode": "internal",
        "isAdmin": True,  # admin sees everything
        "sharedPartnerId": None,
        "defaultProject": None,
        "invitedBy": None,
        "roles": [],
        "department": "all",
    }

    request = MagicMock()
    request.method = "GET"
    request.headers = {"authorization": "Bearer fake-token"}
    request.path_params = {"id": "ent-dashboard-1"}
    request.query_params = {}

    with patch("zenos.interface.dashboard_api._auth_and_scope",
               new=AsyncMock(return_value=(_PARTNER, "p1"))), \
         patch("zenos.interface.dashboard_api._ensure_repos", new=AsyncMock(return_value=None)), \
         patch("zenos.interface.dashboard_api._entity_repo") as mock_er, \
         patch("zenos.interface.dashboard_api._compute_impact_chains_with_context",
               new=AsyncMock(return_value=(fwd_chain, rev_chain))):

        mock_er.get_by_id = AsyncMock(return_value=entity)

        resp = await get_entity(request)

    assert resp.status_code == 200
    body = _json.loads(resp.body)

    # Top-level structure must have "entity", "impact_chain", "reverse_impact_chain"
    assert "entity" in body, f"Missing 'entity' key. Got: {list(body.keys())}"
    assert "impact_chain" in body, "Missing 'impact_chain'"
    assert "reverse_impact_chain" in body, "Missing 'reverse_impact_chain'"

    # Entity sub-dict field set must include all expected keys (camelCase for REST)
    entity_payload = body["entity"]
    required_entity_fields = {
        "id", "name", "type", "level", "parentId", "status", "summary",
        "tags", "confirmedByUser", "owner", "sources",
    }
    missing = required_entity_fields - set(entity_payload.keys())
    assert not missing, f"Missing entity fields in REST response: {missing}"

    # sources must be an array (complete)
    assert isinstance(entity_payload["sources"], list)
    assert len(entity_payload["sources"]) == 1

    # impact_chain must match what the service returned
    assert body["impact_chain"] == fwd_chain
    assert body["reverse_impact_chain"] == rev_chain


@pytest.mark.spec("AC-MCPINC-17")
@pytest.mark.asyncio
@pytest.mark.skip(reason="architect-verified: E2E UI regression verified by Architect in Phase 3 deploy")
async def test_ac_mcpinc_17_dashboard_ui_no_regression():
    """AC-MCPINC-17: Dashboard UI regression — Architect Phase 3 human verification.

    Note: 此 AC 為 E2E 層驗證, 由 Architect 在部署後人工驗證 + playwright smoke test 覆蓋.
    """
    pytest.fail("NOT IMPLEMENTED — Developer must fill this test")


# --- R4: Tool docstring 更新 ---

@pytest.mark.spec("AC-MCPINC-18")
@pytest.mark.asyncio
async def test_ac_mcpinc_18_tool_docstring_has_include_examples():
    """AC-MCPINC-18: get and search docstrings contain include keyword + example usages."""
    import inspect
    from zenos.interface.mcp.get import get
    from zenos.interface.mcp.search import search

    get_doc = inspect.getdoc(get) or ""
    search_doc = inspect.getdoc(search) or ""

    # Both docstrings must mention "include"
    assert "include" in get_doc, "get docstring missing 'include'"
    assert "include" in search_doc, "search docstring missing 'include'"

    # Must contain specific examples
    assert 'include=["summary"]' in get_doc, "get docstring missing include=[\"summary\"] example"
    assert 'include=["all"]' in get_doc, "get docstring missing include=[\"all\"] example"
    assert 'include=["summary"]' in search_doc, "search docstring missing include=[\"summary\"] example"


# --- R5: Deprecation warning 可追蹤 ---

@pytest.mark.spec("AC-MCPINC-20")
@pytest.mark.asyncio
async def test_ac_mcpinc_20_docstring_include_use_case_mapping():
    """AC-MCPINC-20: get docstring maps each include value to a use case."""
    import inspect
    from zenos.interface.mcp.get import get
    from zenos.interface.mcp.search import search

    get_doc = inspect.getdoc(get) or ""
    search_doc = inspect.getdoc(search) or ""

    # get must document each include value with use case
    for phrase in [
        "summary",
        "relationships",
        "impact_chain",
        "sources",
        "entries",
        "all",
    ]:
        assert phrase in get_doc, f"get docstring missing include value: {phrase}"

    # get docstring must include use case hints
    assert "capture" in get_doc or "辨識" in get_doc, "get docstring missing capture/辨識 use case"
    assert "鄰居" in get_doc or "neighbor" in get_doc.lower() or "沿圖" in get_doc, \
        "get docstring missing relationships use case"
    assert "影響" in get_doc or "impact" in get_doc.lower(), "get docstring missing impact use case"
    assert "L3" in get_doc or "文件" in get_doc, "get docstring missing sources/L3 use case"
    assert "decision" in get_doc or "insight" in get_doc or "entries" in get_doc, \
        "get docstring missing entries use case"

    # search must document its three include values with use cases
    for phrase in ["summary", "tags", "full"]:
        assert phrase in search_doc, f"search docstring missing include value: {phrase}"


@pytest.mark.spec("AC-MCPINC-19")
@pytest.mark.asyncio
async def test_ac_mcpinc_19_warning_log_structured():
    """AC-MCPINC-19: deprecation warning log is structured JSON with required fields."""
    entity = _make_entity()
    ewr = EntityWithRelationships(entity=entity, relationships=[])

    mock_os = AsyncMock()
    mock_os.get_entity = AsyncMock(return_value=ewr)
    mock_os.compute_impact_chain = AsyncMock(return_value=[])
    mock_entry = AsyncMock()
    mock_entry.list_by_entity = AsyncMock(return_value=[])

    patches = _mock_get_bootstrap(ontology_service=mock_os, entry_repo=mock_entry)

    with patch("zenos.interface.mcp._include.logger") as mock_logger:
        await _call_get(patches, collection="entities", name="Paceriz")  # no include → triggers warning

    mock_logger.warning.assert_called_once()
    raw_message = mock_logger.warning.call_args[0][0]

    # Must be valid JSON
    log_data = json.loads(raw_message)

    # Required fields per TD
    assert log_data["event"] == "mcp_include_deprecation"
    assert log_data["tool"] in ("get", "search")
    assert log_data["collection"] == "entities"
    assert "caller_id" in log_data  # can be None
    assert "timestamp" in log_data
    assert "message" in log_data
    # Message must contain the specified text
    assert "caller not using include, defaulting to full payload" in log_data["message"]
    assert "Phase B" in log_data["message"]
    # Timestamp must be a valid ISO 8601 string
    datetime.fromisoformat(log_data["timestamp"])  # raises if invalid
