import { test as setup, expect } from '@playwright/test';
import { execSync } from 'child_process';
import * as fs from 'fs';
import * as path from 'path';

const authDir = path.join(__dirname, '.auth');
const authFile = path.join(authDir, 'storageState.json');
const initScriptFile = path.join(authDir, 'firebase-init.js');

// Firebase project config — values baked into the static build via NEXT_PUBLIC_* env vars
const FIREBASE_API_KEY = process.env.NEXT_PUBLIC_FIREBASE_API_KEY ?? 'AIzaSyDjAsF7t4nR34RuouBDcMOnYi6kIjVDxRA'; // pragma: allowlist secret
const FIREBASE_APP_NAME = '[DEFAULT]';
const AUTH_STORAGE_KEY = `firebase:authUser:${FIREBASE_API_KEY}:${FIREBASE_APP_NAME}`;

setup('authenticate', async ({ page, request }) => {
  // Ensure .auth directory exists
  if (!fs.existsSync(authDir)) {
    fs.mkdirSync(authDir, { recursive: true });
  }

  // Step 1: Generate Firebase custom token via service account
  const customToken = execSync(
    'node scripts/gen-test-token.js',
    { cwd: path.join(__dirname, '..'), encoding: 'utf-8' }
  ).trim();

  // Step 2: Exchange custom token → idToken + refreshToken via Firebase Auth REST API
  const exchangeRes = await request.post(
    `https://identitytoolkit.googleapis.com/v1/accounts:signInWithCustomToken?key=${FIREBASE_API_KEY}`,
    {
      data: { token: customToken, returnSecureToken: true },
      headers: { 'Content-Type': 'application/json' },
    }
  );
  if (!exchangeRes.ok()) {
    const body = await exchangeRes.text();
    throw new Error(`Firebase custom token exchange failed (${exchangeRes.status()}): ${body}`);
  }
  const { idToken, refreshToken } = await exchangeRes.json();

  // Decode UID from idToken JWT (signInWithCustomToken API doesn't return localId)
  const jwtPayload = JSON.parse(Buffer.from(idToken.split('.')[1], 'base64url').toString());
  const uid = jwtPayload.sub;

  const persistedUser = buildPersistedUser(uid, idToken, refreshToken, FIREBASE_API_KEY);

  // Step 3: Generate the per-test Firebase IndexedDB seed script with embedded real tokens.
  // This file is used as addInitScript in playwright.config.ts for the chromium project.
  writeFirebaseInitScript(initScriptFile, AUTH_STORAGE_KEY, persistedUser);

  // Step 4: Validate auth works by navigating with the IndexedDB shim active.
  await page.addInitScript({ path: initScriptFile });
  await page.goto('/knowledge-map');
  await expect(page.locator('header')).toBeVisible({ timeout: 25000 });

  // Save a minimal storageState (empty origins — auth is managed by the init script)
  await page.context().storageState({ path: authFile });
});

/**
 * Generates a browser-side init script that intercepts indexedDB.open and wraps
 * Firebase's success handler to ensure the auth user is written BEFORE Firebase reads.
 *
 * Key insight: By wrapping addEventListener('success') on the IDBOpenDBRequest,
 * we delay calling Firebase's success callback until our write transaction commits.
 * This eliminates the race condition between our IDB write and Firebase's IDB read.
 */
function writeFirebaseInitScript(
  filePath: string,
  storageKey: string,
  persistedUser: object
): void {
  const IDB_DB_NAME = 'firebaseLocalStorageDb';
  const IDB_STORE_NAME = 'firebaseLocalStorage';
  const IDB_KEY_PATH = 'fbase_key'; // pragma: allowlist secret

  const script = `
// Auto-generated by playwright/auth.setup.ts — do not edit manually.
// Seeds Firebase IndexedDB with real auth tokens before each Playwright test.
//
// Strategy: intercept indexedDB.open and wrap addEventListener('success') on the
// IDBOpenDBRequest. When the success event fires, we seed the auth record FIRST
// and only call Firebase's original success handler AFTER our write transaction commits.
// This eliminates the race between our IDB write and Firebase's IDB read.
(function () {
  var IDB_DB_NAME = ${JSON.stringify(IDB_DB_NAME)};
  var IDB_STORE_NAME = ${JSON.stringify(IDB_STORE_NAME)};
  var IDB_KEY_PATH = ${JSON.stringify(IDB_KEY_PATH)};
  var STORAGE_KEY = ${JSON.stringify(storageKey)};
  var PERSISTED_USER = ${JSON.stringify(persistedUser)};

  var originalOpen = indexedDB.open.bind(indexedDB);
  indexedDB.open = function (name, version) {
    var req = originalOpen(name, version);
    if (name !== IDB_DB_NAME) return req;

    // Wrap addEventListener to intercept Firebase's 'success' handler registration.
    // Our wrapper ensures our seed write completes before Firebase's success handler runs.
    var origAddEventListener = req.addEventListener.bind(req);
    req.addEventListener = function (type, listener, options) {
      if (type !== 'success') {
        return origAddEventListener(type, listener, options);
      }
      // Replace with a wrapper that seeds IDB before calling original listener
      var wrapper = function (event) {
        var db = req.result;
        if (!db || !db.objectStoreNames.contains(IDB_STORE_NAME)) {
          return listener.call(this, event);
        }
        try {
          var tx = db.transaction([IDB_STORE_NAME], 'readwrite');
          var store = tx.objectStore(IDB_STORE_NAME);
          var record = {};
          record[IDB_KEY_PATH] = STORAGE_KEY;
          record['value'] = PERSISTED_USER;
          store.put(record);
          var self = this;
          tx.oncomplete = function () { listener.call(self, event); };
          tx.onerror = function () { listener.call(self, event); };
          tx.onabort = function () { listener.call(self, event); };
        } catch (e) {
          listener.call(this, event);
        }
      };
      return origAddEventListener('success', wrapper, options);
    };

    return req;
  };
})();
`.trim();

  fs.writeFileSync(filePath, script, 'utf-8');
}

/**
 * Build a Firebase SDK v9+ compatible persisted user object.
 */
function buildPersistedUser(uid: string, idToken: string, refreshToken: string, apiKey: string) {
  return {
    uid,
    email: null,
    emailVerified: false,
    isAnonymous: false,
    providerData: [],
    stsTokenManager: {
      refreshToken,
      accessToken: idToken,
      expirationTime: Date.now() + 3600 * 1000,
    },
    createdAt: String(Date.now()),
    lastLoginAt: String(Date.now()),
    apiKey,
    appName: '[DEFAULT]',
  };
}
