/**
 * AC test stubs generated from SPEC-docs-l3-nav-ui.
 * Auto-generated by Architect — Developer fills implementation.
 * Red = gap, Green = verified.
 *
 * ACs covered:
 * - AC-DOCNAV-01: 文件分頁顯示可展開 L3 列表，不是扁平 grid
 * - AC-DOCNAV-02: 點 L3 row → 展開 sources 子列表
 * - AC-DOCNAV-03: 點 source → inline preview (metadata + snapshot_summary)
 * - AC-DOCNAV-04: 0 sources → 「尚無來源」空狀態
 * - AC-DOCNAV-05: /docs sidebar L3 展開 sources 子列表
 * - AC-DOCNAV-06: sidebar source click → onSelect(doc.id)
 * - AC-DOCNAV-07: single doc 點名稱 → 直接 onSelect
 * - AC-DOCNAV-08: index doc 點名稱 → 展開 sources，不直接 onSelect
 * - AC-DOCNAV-09: L3 row 顯示 N sources badge
 */

import { describe, it, expect, vi, afterEach } from "vitest";
import { render, screen, fireEvent, cleanup } from "@testing-library/react";
import React from "react";
import type { Entity } from "@/types";
import { DocL3AccordionList } from "@/features/docs/DocL3AccordionList";
import { DocListSidebar } from "@/features/docs/DocListSidebar";

// ─── Mock next/navigation ─────────────────────────────────────────────────────

vi.mock("next/navigation", () => ({
  useRouter: () => ({ push: vi.fn(), back: vi.fn() }),
}));

// ─── Mock useInk ──────────────────────────────────────────────────────────────

vi.mock("@/lib/zen-ink/tokens", () => ({
  useInk: () => ({
    c: {
      ink: "#1a1a1a",
      inkSoft: "#555",
      inkFaint: "#999",
      inkHair: "#e0e0e0",
      inkMuted: "#777",
      surface: "#fafafa",
      paperWarm: "#f5f4f0",
      vermillion: "#be3c32",
      vermSoft: "rgba(190,60,50,0.08)",
      vermLine: "rgba(190,60,50,0.25)",
      jade: "#2e7d5a",
      ocher: "#b48432",
    },
    fontHead: "serif",
    fontMono: "monospace",
    fontBody: "sans-serif",
  }),
}));

// ─── Stub Icon component to avoid SVG rendering issues ────────────────────────

vi.mock("@/components/zen/Icons", () => ({
  Icon: ({ style }: { d?: string; size?: number; style?: React.CSSProperties }) => (
    <span data-testid="icon" style={style} />
  ),
  ICONS: {
    chev: "chev-path",
    doc: "doc-path",
    search: "search-path",
    plus: "plus-path",
  },
}));

// ─── Stub Btn component ────────────────────────────────────────────────────────

vi.mock("@/components/zen/Btn", () => ({
  Btn: ({ children, onClick, ...rest }: React.PropsWithChildren<{ onClick?: () => void; [key: string]: unknown }>) => (
    <button onClick={onClick} {...rest}>{children}</button>
  ),
}));

afterEach(() => {
  cleanup();
  vi.clearAllMocks();
});

// ─── Helpers ──────────────────────────────────────────────────────────────────

function makeDocEntity(overrides: Partial<Entity> = {}): Entity {
  return {
    id: "doc-" + Math.random().toString(36).slice(2, 8),
    name: "Test Doc",
    type: "document",
    summary: "doc summary",
    tags: { what: [], why: "", how: "", who: [] },
    status: "current",
    level: 3,
    parentId: "parent-l2-id",
    details: null,
    confirmedByUser: false,
    owner: null,
    sources: [],
    visibility: "public",
    createdAt: new Date("2026-04-27"),
    updatedAt: new Date("2026-04-27"),
    lastReviewedAt: null,
    docRole: "single",
    ...overrides,
  };
}

function makeSource(overrides: Partial<Entity["sources"][0]> = {}): Entity["sources"][0] {
  return {
    uri: "https://example.com/doc.md",
    label: "Test Source",
    type: "github",
    source_id: "src-" + Math.random().toString(36).slice(2, 8),
    source_status: "valid",
    doc_type: "SPEC",
    ...overrides,
  };
}

// Shared mock token object for DocL3AccordionList (which takes t as prop)
const mockT = {
  c: {
    ink: "#1a1a1a",
    inkSoft: "#555",
    inkFaint: "#999",
    inkHair: "#e0e0e0",
    inkMuted: "#777",
    surface: "#fafafa",
    paperWarm: "#f5f4f0",
    vermillion: "#be3c32",
    vermSoft: "rgba(190,60,50,0.08)",
    vermLine: "rgba(190,60,50,0.25)",
    jade: "#2e7d5a",
    ocher: "#b48432",
  },
  fontHead: "serif",
  fontMono: "monospace",
  fontBody: "sans-serif",
} as unknown as ReturnType<typeof import("@/lib/zen-ink/tokens").useInk>;

// ─── P0: R1 — 專案文件分頁 L3 accordion list ─────────────────────────────────

describe("DocL3AccordionList (專案文件分頁)", () => {

  it("AC-DOCNAV-01: Given 專案有 L3 document entities, When 文件分頁渲染, Then 顯示可展開列表不是扁平 grid", () => {
    const docs = [makeDocEntity({ docRole: "index", sources: [makeSource()] })];
    render(<DocL3AccordionList documents={docs} t={mockT} />);

    expect(screen.getByTestId("doc-l3-accordion-list")).toBeTruthy();
    expect(screen.getByTestId(`doc-l3-row-${docs[0].id}`)).toBeTruthy();

    // Should NOT render a 2-column CSS grid (the old flat grid is gone)
    const list = screen.getByTestId("doc-l3-accordion-list");
    const gridCols = (list as HTMLElement).style.gridTemplateColumns;
    expect(gridCols).not.toContain("repeat(2");
  });

  it("AC-DOCNAV-02: Given L3 row 已渲染, When 點擊 row, Then 展開 sources 子列表", () => {
    const source = makeSource();
    const doc = makeDocEntity({ docRole: "index", sources: [source] });
    render(<DocL3AccordionList documents={[doc]} t={mockT} />);

    // Sources should not be visible before clicking
    expect(screen.queryByTestId(`doc-l3-sources-${doc.id}`)).toBeNull();

    // Click the row
    fireEvent.click(screen.getByTestId(`doc-l3-row-${doc.id}`));

    // Sources should now be visible
    expect(screen.getByTestId(`doc-l3-sources-${doc.id}`)).toBeTruthy();
    expect(screen.getByTestId(`doc-l3-source-item-${source.source_id}`)).toBeTruthy();
  });

  it("AC-DOCNAV-03: Given sources 展開, When 點擊 source, Then 顯示 inline preview 含 metadata + snapshot", () => {
    const source = makeSource({ snapshot_summary: "This is the snapshot" });
    const doc = makeDocEntity({ docRole: "index", sources: [source] });
    render(<DocL3AccordionList documents={[doc]} t={mockT} />);

    // Expand the row
    fireEvent.click(screen.getByTestId(`doc-l3-row-${doc.id}`));

    // Click the source
    fireEvent.click(screen.getByTestId(`doc-l3-source-item-${source.source_id}`));

    // Inline preview should appear
    const preview = screen.getByTestId("doc-l3-inline-preview");
    expect(preview).toBeTruthy();
    // Preview contains the source label (may appear more than once in DOM, check within preview)
    expect(preview.textContent).toContain("Test Source");
    expect(screen.getByText("This is the snapshot")).toBeTruthy();
  });

  it("AC-DOCNAV-03 (fallback): Given snapshot_summary is null, When preview opened, Then shows entity.summary", () => {
    const source = makeSource({ snapshot_summary: null });
    const doc = makeDocEntity({ docRole: "index", sources: [source], summary: "entity summary fallback" });
    render(<DocL3AccordionList documents={[doc]} t={mockT} />);

    fireEvent.click(screen.getByTestId(`doc-l3-row-${doc.id}`));
    fireEvent.click(screen.getByTestId(`doc-l3-source-item-${source.source_id}`));

    expect(screen.getByTestId("doc-l3-inline-preview")).toBeTruthy();
    expect(screen.getByText("entity summary fallback")).toBeTruthy();
  });

  it("AC-DOCNAV-04: Given L3 entity 有 0 sources, When 展開, Then 顯示「尚無來源」", () => {
    const doc = makeDocEntity({ sources: [], docRole: "index" });
    render(<DocL3AccordionList documents={[doc]} t={mockT} />);

    // Click to expand
    fireEvent.click(screen.getByTestId(`doc-l3-row-${doc.id}`));

    expect(screen.getByText("尚無來源")).toBeTruthy();
  });

  it("AC-DOCNAV-09 (P1): Given L3 entity 有 N sources, When 渲染, Then 顯示 N sources badge", () => {
    const doc2 = makeDocEntity({ sources: [makeSource(), makeSource()], docRole: "index" });
    const doc0 = makeDocEntity({ sources: [], docRole: "index" });
    render(<DocL3AccordionList documents={[doc2, doc0]} t={mockT} />);

    expect(screen.getByTestId(`doc-l3-source-count-${doc2.id}`).textContent).toBe("2 sources");
    expect(screen.getByTestId(`doc-l3-source-count-${doc0.id}`).textContent).toBe("—");
  });

});

// ─── P0: R2 — /docs sidebar 展開行為 ─────────────────────────────────────────

describe("DocListSidebar L3 expand", () => {

  it("AC-DOCNAV-05: Given sidebar 有 L3 index entity, When 點展開箭頭, Then 顯示 sources 子列表", () => {
    const source = makeSource();
    const doc = makeDocEntity({ docRole: "index", sources: [source] });
    const onSelect = vi.fn();
    render(
      <DocListSidebar
        docs={[doc]}
        selectedId={null}
        onSelect={onSelect}
      />
    );

    // Source sub-item should NOT be visible initially
    expect(screen.queryByTestId(`sidebar-source-item-${source.source_id}`)).toBeNull();

    // Click the chevron to expand
    fireEvent.click(screen.getByTestId(`doc-expand-chevron-${doc.id}`));

    // Source sub-item should now be visible
    expect(screen.getByTestId(`sidebar-source-item-${source.source_id}`)).toBeTruthy();
  });

  it("AC-DOCNAV-06: Given source 子項目已展開, When 點擊 source, Then 呼叫 onSelect(doc.id)", () => {
    const source = makeSource();
    const doc = makeDocEntity({ docRole: "index", sources: [source] });
    const onSelect = vi.fn();
    render(
      <DocListSidebar
        docs={[doc]}
        selectedId={null}
        onSelect={onSelect}
      />
    );

    // Expand
    fireEvent.click(screen.getByTestId(`doc-expand-chevron-${doc.id}`));

    // Click source
    fireEvent.click(screen.getByTestId(`sidebar-source-item-${source.source_id}`));

    expect(onSelect).toHaveBeenCalledWith(doc.id);
    expect(onSelect).not.toHaveBeenCalledWith(source.source_id);
  });

  it("AC-DOCNAV-07: Given doc_role=single, When 點擊 entity 名稱, Then 直接呼叫 onSelect(doc.id)", () => {
    const source = makeSource();
    const doc = makeDocEntity({ docRole: "single", sources: [source] });
    const onSelect = vi.fn();
    render(
      <DocListSidebar
        docs={[doc]}
        selectedId={null}
        onSelect={onSelect}
      />
    );

    // For single doc: the doc-item div contains one button (the name button, no chevron)
    const docItem = screen.getByTestId(`doc-item-${doc.id}`);
    const nameBtn = docItem.querySelector("button");
    expect(nameBtn).toBeTruthy();
    fireEvent.click(nameBtn!);

    expect(onSelect).toHaveBeenCalledWith(doc.id);
    // No source sub-items should appear
    expect(screen.queryByTestId(`sidebar-source-item-${source.source_id}`)).toBeNull();
  });

  it("AC-DOCNAV-08: Given doc_role=index, When 點擊 entity 名稱, Then 展開 sources，不呼叫 onSelect", () => {
    const source = makeSource();
    const doc = makeDocEntity({ docRole: "index", sources: [source] });
    const onSelect = vi.fn();
    render(
      <DocListSidebar
        docs={[doc]}
        selectedId={null}
        onSelect={onSelect}
      />
    );

    // For index doc: doc-item contains [chevron button, name button]
    const docItem = screen.getByTestId(`doc-item-${doc.id}`);
    const buttons = docItem.querySelectorAll("button");
    // buttons[0] = chevron, buttons[1] = name
    expect(buttons.length).toBeGreaterThanOrEqual(2);
    fireEvent.click(buttons[1]);

    expect(onSelect).not.toHaveBeenCalled();
    // Source sub-items should now appear
    expect(screen.getByTestId(`sidebar-source-item-${source.source_id}`)).toBeTruthy();
  });

});
