/**
 * AC test stubs for PLAN-entity-simplification-ui-cleanup.
 * Driven by ADR-047 D7 + ADR-048 + CLAUDE.md hard constraint 6.
 *
 * Auto-generated by Architect — Developer fills implementation.
 * Red = gap, Green = verified.
 *
 * Coverage:
 * - AC-ENTSIMP-UI-01: HealthBar counts all L1 types (isL1Entity)
 * - AC-ENTSIMP-UI-02: isPlaceholderCompletedProject does not misfire on company L1
 * - AC-ENTSIMP-UI-03: taskHubCopilot context / prompt uses neutral workspace terms
 * - AC-ENTSIMP-UI-04: No user-visible "產品 / products" outside exemptions
 * - AC-ENTSIMP-UI-05: Renamed showDormantWorkspaces / WorkspaceHealthList
 * - AC-ENTSIMP-UI-06: Projects cards use type-based accent via resolveL1Accent
 * - AC-ENTSIMP-UI-07: KnowledgeGraph node size is level-based
 * - AC-ENTSIMP-UI-08: preview page strategy recorded
 * - AC-ENTSIMP-UI-09: Deploy + 3-scenario smoke pass
 */

import { describe, expect, it } from "vitest";
import type { Entity } from "@/types";

// ─── Fixture helpers ──────────────────────────────────────────────────────────

function makeEntity(overrides: Partial<Entity> = {}): Entity {
  return {
    id: "e-default",
    name: "Default",
    type: "product",
    summary: "",
    tags: { what: [], why: "", how: "", who: [] },
    status: "active",
    level: 1,
    parentId: null,
    details: null,
    confirmedByUser: true,
    owner: null,
    sources: [],
    visibility: "public",
    lastReviewedAt: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    ...overrides,
  };
}

// ─── AC-ENTSIMP-UI-01: HealthBar counts all L1 types ─────────────────────────

import { isL1Entity } from "@/lib/entity-level";

describe("AC-ENTSIMP-UI-01: HealthBar L1 filter", () => {
  it("counts company L1 in active workspaces (not filtered out)", () => {
    const companyL1 = makeEntity({ type: "company", level: 1, parentId: null, status: "active" });
    const personL1 = makeEntity({ id: "e-person", type: "person", level: 1, parentId: null, status: "active" });
    const dealL1 = makeEntity({ id: "e-deal", type: "deal", level: 1, parentId: null, status: "active" });
    const productL1 = makeEntity({ id: "e-product", type: "product", level: 1, parentId: null, status: "active" });

    const entities = [companyL1, personL1, dealL1, productL1];

    // Replicate HealthBar's filter: entities.filter(isL1Entity)
    const l1Entities = entities.filter(isL1Entity);
    expect(l1Entities).toHaveLength(4);
    expect(l1Entities.map((e) => e.type)).toContain("company");
    expect(l1Entities.map((e) => e.type)).toContain("person");
    expect(l1Entities.map((e) => e.type)).toContain("deal");
    expect(l1Entities.map((e) => e.type)).toContain("product");

    // Replicate HealthBar's active filter: entities.filter(e => isL1Entity(e) && e.status === "active")
    const activeL1 = entities.filter((e) => isL1Entity(e) && e.status === "active");
    expect(activeL1).toHaveLength(4);
  });

  it("does not count L2 module entities", () => {
    const moduleL2 = makeEntity({ id: "e-module", type: "module", level: 2, parentId: "parent-1", status: "active" });
    const productL2 = makeEntity({ id: "e-prod-l2", type: "product", level: 2, parentId: "parent-1", status: "active" });

    const entities = [moduleL2, productL2];

    const l1Entities = entities.filter(isL1Entity);
    expect(l1Entities).toHaveLength(0);

    const activeL1 = entities.filter((e) => isL1Entity(e) && e.status === "active");
    expect(activeL1).toHaveLength(0);
  });

  it("product L1 is still counted (regression guard)", () => {
    const productL1 = makeEntity({ id: "e-prod", type: "product", level: 1, parentId: null, status: "active" });
    const l1Entities = [productL1].filter(isL1Entity);
    expect(l1Entities).toHaveLength(1);
  });
});

// ─── AC-ENTSIMP-UI-02: isPlaceholderCompletedProject does not misfire ─────────

// Method B: inline copy of the pure function — avoids exporting from page.tsx.
// Must stay in sync with dashboard/src/app/(protected)/projects/page.tsx:86-93.
function isPlaceholderCompletedProject(entity: Entity): boolean {
  return (
    entity.type === "product" &&
    entity.status === "completed" &&
    entity.confirmedByUser === false &&
    entity.sources.length === 0
  );
}

describe("AC-ENTSIMP-UI-02: isPlaceholderCompletedProject", () => {
  it("hides a completed unconfirmed product with no sources (placeholder)", () => {
    const placeholder = makeEntity({
      type: "product",
      status: "completed",
      confirmedByUser: false,
      sources: [],
    });
    expect(isPlaceholderCompletedProject(placeholder)).toBe(true);
  });

  it("does NOT hide a company L1 that is not a placeholder", () => {
    // type !== "product" → always false regardless of other fields
    const companyL1 = makeEntity({
      type: "company",
      status: "completed",
      confirmedByUser: false,
      sources: [],
    });
    expect(isPlaceholderCompletedProject(companyL1)).toBe(false);
  });

  it("does NOT hide a product L1 that is confirmed or has sources", () => {
    const confirmedProduct = makeEntity({
      type: "product",
      status: "completed",
      confirmedByUser: true,
      sources: [],
    });
    expect(isPlaceholderCompletedProject(confirmedProduct)).toBe(false);

    const productWithSources = makeEntity({
      type: "product",
      status: "completed",
      confirmedByUser: false,
      sources: [{ uri: "https://example.com", label: "src", type: "link" }],
    });
    expect(isPlaceholderCompletedProject(productWithSources)).toBe(false);
  });
});

// ─── AC-ENTSIMP-UI-03: taskHubCopilot uses neutral workspace terms ─────────────

import { buildTaskHubCopilotEntry } from "@/features/tasks/taskHubCopilot";
import type { TaskHubSnapshot } from "@/features/tasks/taskHub";

function makeMinimalSnapshot(overrides: Partial<TaskHubSnapshot> = {}): TaskHubSnapshot {
  return {
    summary: {
      productCount: 1,
      activeMilestoneCount: 0,
      activePlanCount: 0,
      blockedPlanCount: 0,
      overdueWorkCount: 0,
    },
    products: [
      {
        productId: "p-1",
        productName: "Acme Corp",
        productSummary: "A test workspace",
        currentMilestone: null,
        activePlanCount: 0,
        openTaskCount: 0,
        blockedCount: 0,
        reviewCount: 0,
        overdueCount: 0,
        lastUpdatedAt: new Date("2026-01-01"),
        riskLevel: "healthy",
        plans: [],
        milestones: [],
      },
    ],
    radar: [],
    recentChanges: [
      {
        id: "p-1",
        productId: "p-1",
        productName: "Acme Corp",
        title: "Q1 Plan",
        subtitle: "0 open work",
        updatedAt: new Date("2026-01-01"),
      },
    ],
    ...overrides,
  };
}

describe("AC-ENTSIMP-UI-03: taskHubCopilot neutralisation", () => {
  it("context_pack has top_workspaces key (not top_products)", () => {
    const snapshot = makeMinimalSnapshot();
    const entry = buildTaskHubCopilotEntry({ snapshot });
    const pack = entry.context_pack as Record<string, unknown>;

    expect(pack).toHaveProperty("top_workspaces");
    expect(pack).not.toHaveProperty("top_products");
  });

  it("prompt string contains no '產品' or 'products'", () => {
    const snapshot = makeMinimalSnapshot();
    const entry = buildTaskHubCopilotEntry({ snapshot });
    const prompt = entry.build_prompt("");

    expect(prompt).not.toContain("產品");
    expect(prompt).not.toContain("products");
  });

  it("recent_changes items have workspace key (not product)", () => {
    const snapshot = makeMinimalSnapshot();
    const entry = buildTaskHubCopilotEntry({ snapshot });
    const pack = entry.context_pack as Record<string, unknown>;
    const recentChanges = pack.recent_changes as Array<Record<string, unknown>>;

    expect(recentChanges.length).toBeGreaterThan(0);
    for (const item of recentChanges) {
      expect(item).toHaveProperty("workspace");
      expect(item).not.toHaveProperty("product");
    }
  });
});

// ─── AC-ENTSIMP-UI-04: No user-visible 產品 / products outside exemptions ──────

describe("AC-ENTSIMP-UI-04: User-visible copy sweep", () => {
  it.todo("AppNav labels do not contain '產品' — implement in Phase 2 S04");
  it.todo("TaskHubRail placeholder and emptyState do not contain '產品' — implement in Phase 2 S04");
  it.todo("TaskHubMorningPanel status strings do not contain '產品' or 'products' — implement in Phase 2 S04");
});

// ─── AC-ENTSIMP-UI-05: Renamed symbols ────────────────────────────────────────

describe("AC-ENTSIMP-UI-05: Renamed symbols", () => {
  it.todo("WorkspaceHealthList is importable (ProductHealthList renamed) — implement in Phase 2 S05");
});

// ─── AC-ENTSIMP-UI-06: Projects cards type-based accent ──────────────────────

describe("AC-ENTSIMP-UI-06: resolveL1Accent", () => {
  it.todo("returns vermillion for type=product — implement in Phase 3 S06");
  it.todo("returns a different value for type=company — implement in Phase 3 S06");
  it.todo("falls back to vermillion for unknown types — implement in Phase 3 S06");
});

// ─── AC-ENTSIMP-UI-07: KnowledgeGraph level-based sizing ─────────────────────

describe("AC-ENTSIMP-UI-07: KnowledgeGraph node size", () => {
  it.todo("level=1 node size equals level=1 regardless of type — implement in Phase 3 S07");
  it.todo("level=2 node is smaller than level=1 node — implement in Phase 3 S07");
});

// ─── AC-ENTSIMP-UI-08: preview strategy ──────────────────────────────────────

describe("AC-ENTSIMP-UI-08: preview page strategy", () => {
  it.todo("preview strategy decision is recorded in PLAN Decisions — Architect signs off in Phase 4 S08");
});

// ─── AC-ENTSIMP-UI-09: Deploy + smoke ────────────────────────────────────────

describe("AC-ENTSIMP-UI-09: End-to-end smoke", () => {
  it.todo("product-only workspace: Task Hub recap renders correctly — covered by QA Verdict in Phase 4 S09");
  it.todo("CRM-only workspace: Task Hub copilot output has no '產品' — covered by QA Verdict in Phase 4 S09");
  it.todo("mixed workspace: HealthBar count includes all L1 types — covered by QA Verdict in Phase 4 S09");
});
