/**
 * AC test stubs generated from SPEC-task-governance §2026-04-22 Task Ownership SSOT 收斂.
 *
 * Auto-generated by Architect (ADR-044) — Developer fills implementation.
 * Red = gap, Green = verified.
 *
 * Frontend coverage:
 *   - AC-TOSC-18: Frontend /tasks product filter
 *   - AC-TOSC-19: /projects/[id] create task uses product_id (no linked_entities hack)
 *   - AC-TOSC-20: createTask client type makes product_id required
 */
import { describe, it } from "vitest";

describe.skip("Task Ownership SSOT — Frontend AC", () => {
  it.fails(
    "AC-TOSC-18: 全域 /tasks 的 product filter 改用 product_id, 顯示 product entity name",
    () => {
      throw new Error("NOT IMPLEMENTED — Developer must fill this test");
    },
  );

  it.fails(
    "AC-TOSC-19: 從 /projects/[id] 建 task 時傳遞 product_id=entity.id, 不再偷塞 linked_entities",
    () => {
      throw new Error("NOT IMPLEMENTED — Developer must fill this test");
    },
  );

  it.fails(
    "AC-TOSC-20: createTask client 型別 product_id: string 為必填欄位 (TypeScript 強制)",
    () => {
      throw new Error("NOT IMPLEMENTED — Developer must fill this test");
    },
  );
});
